### ISSUE TITLE
BUG: Not all Installed modules are in local packages

### ISSUE THREAD

**Issue by Schnabulation** [Bee-Mar/mmpm#103]
**Describe the Bug**

I have installed 5 modules (excluding MMPM) using `git clone` and all of them work perfectly fine in the Magic Mirror frontend. However in MMPM only one of these modules are found in "local packages" and therefore MMPM watches for updates.

There seems to be a wiki page regarding this but it states that the issue was fixed in version 2.02. I have here a very fresh install - no upgrade or the like, running the latest version 2.14 but the issue is still present.

The modules are discovered fine in the "Active Modules" part of the control center.

Am I missing something?

**Screenshots**

![Active_modules](https://user-images.githubusercontent.com/1053834/172369896-4ce4fcc3-171e-427e-98ed-df5d503ad1d2.jpg)

![local_packages](https://user-images.githubusercontent.com/1053834/172369913-6d5eb48c-2829-46a0-931f-76e6d3a4d68a.jpg)

**Operating System, Python3 Version, and Web Browser**\
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
Python 3.9.2
```

**MMPM Environment Settings**
```
{
  "MMPM_MAGICMIRROR_ROOT": "/home/steve/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.100.71:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "mm",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}
```

**Comment by Bee-Mar** [comment]
@Schnabulation The issue may be related to with what the name of the module is and the name of the directory. When you ran `git clone` to install the local packages, does the name of each module in your `config.js` match the name of the directory the module was cloned into?

**Comment by Schnabulation** [comment]
Thank you for your help. I have just compared the directories to my `config.js` and can say: yes, the folder names match the name of the module referenced in the config.

Interestingly though all new installed modules show up correctly under Local Packages but the ones that were already installed when installing MMPM do not show up. Do I have to manually index them somehow?

**Comment by Bee-Mar** [comment]
There is no mechanism to manually index them. Also, I didn't clearly explain my previous question. When you cloned each of the repos, did you clone them into an alias directory? Or did you just run "git clone" followed by only the URL?

For example:

git clone https://github.com/bee-mar/mmpm.git

Or did you run something like:

git clone https://github.com/bee-mar/mmpm.git ~/some-alternative-name

**Comment by Bee-Mar** [comment]
Also, it would be best for you to reinstall the modules using the "mmpm" CLI. The way some modules are named doesn't quite match with the repo URL and I have to parse the name from the URL. So MMPM may be looking for a different name than you expect.

**Comment by Schnabulation** [comment]
> When you cloned each of the repos, did you clone them into an alias directory?

I just run the normal `git clone [repo-url]` command without any alias name. But I did install these modules before I installed mmpm. I was of the impression that mmpm would index them.

If I reinstall the repos will my adjustments be overwritten? I have adjusted some CSS files.
