### ISSUE TITLE
Unable to retrieve active modules...  but not quite

### ISSUE THREAD

**Issue by DrJaymz** [Bee-Mar/mmpm#104]
I looked at the documentation and previous postings but my issue seemed a little different.
In the UI it says unable to retrieve  active modules...  but `$mmpm` mm-ctl --status`
shows them all fine.

I am using 0.0.0.0 for everything so should be no issue accessing itself and the module is installed and in the config.

**Comment by wchill** [comment]
I just ran into this too. Try updating `MMPM_MAGICMIRROR_URI` to the actual IP of your device instead of 0.0.0.0 - the web ui seems to be using this value to try and query MagicMirror

**Comment by Bee-Mar** [comment]
@DrJaymz You should **not** be using `0.0.0.0`, this is detailed in the [Status, Hide, Show MagicMirror Modules](https://github.com/Bee-Mar/mmpm/wiki/Status,-Hide,-Show-MagicMirror-Modules) wiki page.

**Comment by Bee-Mar** [comment]
@wchill any update on this?

**Comment by Bee-Mar** [comment]
@wchill I'm going to close this issue since there isn't an update. Feel free to reopen if there is still a problem.

**Comment by wchill** [comment]
I'm not the original issue creator, but essentially there's some step that asks for the listening IP of MM, if I remember correctly. 0.0.0.0 is technically a correct input in this case.
