### ISSUE TITLE
BUG: Fatal Python error: initfsencoding: unable to load the file system codec

### ISSUE THREAD

**Issue by kaustubhcs** [Bee-Mar/mmpm#105]
Installation bug. Tried installing with the command `python3 -m pip install --upgrade --no-cache-dir mmpm`,
Got the error:
```
$> python3 -m pip install --upgrade --no-cache-dir mmpm
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x76f3f000 (most recent call first):
[1]    1959 abort      python3 -m pip install --upgrade --no-cache-dir mmpm
```

Using vanilla magic mirror. First thing I tried to install was MMPM package. Using Raspberry Pi 3 Model B with OS: Raspbian GNU/Linux 9.13 (stretch).

**Comment by Bee-Mar** [comment]
@kaustubhcs what version of Python3 is it?

**Comment by kaustubhcs** [comment]
Thanks @Bee-Mar . The problem fixed itself. I did a clean reinstall of Raspbian OS, and it worked swimmingly :D
