### ISSUE TITLE
BUG: No connection to Config.js file 

### ISSUE THREAD

**Issue by lmhmm** [Bee-Mar/mmpm#106]
**Describe the Bug**

Is this an issue with the CLI or GUI?

GUI

Is this something that should be put in the Wiki?

?

**To Reproduce**

Installed twice now and everything else works, I can install modules, hide etc. however in Config I get 1 showing and that’s it!?! 

**Expected behavior**

**Screenshots**

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`

- output from `python3 --version`

- Web Browser (firefox, chrome, safari, chromium, etc)

**MMPM Environment Settings**

- output from `mmpm env`

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by Bee-Mar** [comment]
@lmhmm I'm unclear on what the issue is based on the information above. Can you clarify?

**Comment by lmhmm** [comment]
It’s okay, it’s me being silly I found out that you have to CHOOSE the file to see. It works perfectly so sorry to have bothered you!

Great app!

Lorraine 



Lorraine Hodgkinson AHG MRCHM HERBS AND HELPERS ®️
43A, Melbreak Avenue, Cockermouth,
Cumbria, CA13 9AE. UK.
Tel: +44 (0) 1900 826392
Mobile: 07761 489838 (O2)
www.herbalmedicineuk.com
VAT Number: GB 366828748


On 17 Jul 2022, at 17:37, Brandon Marlowe ***@***.***> wrote:

﻿
@lmhmm I'm unclear on what the issue is based on the information above. Can you clarify?

**Comment by Bee-Mar** [comment]
No problem! There are definitely some things that can be improved and that may be something I adjust in a future release.

Thanks!
