### ISSUE TITLE
BUG: Module is stuck hidden

### ISSUE THREAD

**Issue by macaday** [Bee-Mar/mmpm#107]
**Describe the Bug**

Is this an issue with the CLI or GUI? - Both

Is this something that should be put in the Wiki? - The commands shown in the wiki do not work.

A clear and concise description of what the bug is:

At some point I had hidden the MMM-Powerwall module in my Magic Mirror.  Now it's stuck hidden.  When I toggle visibility in the GUI and refresh it goes back to being hidden.  When I try to use the CLI to show the module I get an error "FATAL: Module key(s) must all be integers."

**To Reproduce**
1. Open the MMPM GUI
2. Toggle visibility on MMM-Powerwall module to shown
3. Refresh MMPM GUI
4. See that toggle has reverted back to hidden5. 
5. Run "mmpm mm-ctl --status" to get module key
6. Run "mmpm mm-ctl --show 8"
7. Get error "FATAL: Module key(s) must all be integers."
8. Run "mmpm mm-ctl --show MMM-Powerwall"
9. Get error "FATAL: Module key(s) must all be integers."10. 

**Expected behavior**
The module should be shown when using the GUI.  CLI command should accept module name (as shown in wiki) or module key.

**Screenshots**

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- output from `python3 --version`:
Python 3.8.13

- Web Browser (firefox, chrome, safari, chromium, etc)
Safari, Chrome, Edge

**MMPM Environment Settings**
GPG_KEY | E3FF2839C048B25C084DEBE9B26995E310250568
LANG | C.UTF-8
PATH | /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.local/bin
PYTHON_GET_PIP_SHA256 | d077d469ce4c0beaf9cc97b73f8164ad20e68e0519f14dd886ce35d053721501
PYTHON_GET_PIP_URL | https://github.com/pypa/get-pip/raw/49ca29908cfd49683da12f2d5a4fa5689539f9d9/public/get-pip.py
PYTHON_PIP_VERSION | 22.0.4
PYTHON_SETUPTOOLS_VERSION | 57.5.0
PYTHON_VERSION | 3.8.13

- output from `mmpm env`:
{
  "MMPM_MAGICMIRROR_ROOT": "/home/node/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://10.0.1.183:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": true
}

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`: In log zip
[mmpm-logs-2022-7-1.zip](https://github.com/Bee-Mar/mmpm/files/9235970/mmpm-logs-2022-7-1.zip)

**Comment by Bee-Mar** [comment]
There is a plan to reintroduce the ability to hide/show modules based on key names, but it was changed to integer values in the most recent update because other users had issues controlling the duplicate built-in weather modules. As it stands, you would need to list the existing modules using `mmpm mm-ctl --status` to get the key for that module and then hide/show whichever ones you want.
