### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by rroach3753** [Bee-Mar/mmpm#108]
I have recently added HTTPS support to my magic mirror (it's a public wildcard cert), however, when enabling HTTPS support in MM I can no longer use the FQDN and port for MMPM.  If I switch to the IP address for the RPi running MM/MMPM with the port for MMPM I can access the MMPM interface.

**Comment by Bee-Mar** [comment]
Can you provide the configuration file as well as your MMPM environment setup using the `mmpm env` command?
