### ISSUE TITLE
Feature request: support multiple sources.

### ISSUE THREAD

**Issue by AndrewSav** [Bee-Mar/mmpm#11]
_If this is already possible, please let me know, may be I overlooked something!_

As it stands the only source of the package currently is the "official list" on the github page. It means that if a module is not there, I cannot install and update it with mmpm.

Why a module would not be there? Well there could be a few reasons. It could be a private module, hosted on an internal git server. Or it could be a fork of existing module, where maintainer did not agree to merge changes for whatever reason (e.g. poor quality).

I want to be able to add an additional source (like you can in apt, or scoop, etc) so that modules could be pulled form other places than official list points to.

**Comment by Bee-Mar** [comment]
@AndrewSav That certainly seems doable. I'm thinking of adding configuration commands, and the values provided would be stored within a hidden JSON file. So, this could be lumped into that. 

...perhaps something like `--add-ext-module-src`, to somewhat mirror `--add-apt-repository`within apt

**Comment by AndrewSav** [comment]
In my opinion, more interesting question, is what would be the value of that option. I think something more generic than a module wiki page would be good, but since that's the only think we have now, it's not immideately obvious what could make a good custom source.

**Comment by Bee-Mar** [comment]
@AndrewSav at the moment, it is difficult to justify the necessity of this, considering there isn't any single server hosting the package list. I've considered reaching out to the creator of MagicMirror and seeing what they think about something like this, but at the moment, since the github repos are the only sources available. If someone wants to add an additional source with experimental packages, it might just be better leave the manual installation with those sources up to them, since it's probably fair to assume the user would be a bit more savvy anyway.

**Comment by AndrewSav** [comment]
> it is difficult to justify the necessity of this

Sorry, nescessity of what in particular? Justification of this feature request is contained in it's body, let me know what it's unconvincing, if you feel that it is.

>  there isn't any single server hosting the package list
This is because mmpm or any other toold does not support it. Let's fix it right here.

> If someone wants to add an additional source with experimental packages, it might just be better leave the manual installation with those sources up to them

In which way is it better? I think it's just less convinient and create more work for every individual who'd like to that. mmpm is in possition to solve this for everyone at once.

> it's probably fair to assume the user would be a bit more savvy anyway
Sure. But that does not mean they would feel that replicating each other work would be _better_ solution. Do not you agree?

**Comment by Bee-Mar** [comment]
@AndrewSav I'm going to begin working on this shortly, and should have something usable rather soon.

**Comment by Bee-Mar** [comment]
@AndrewSav If you still have the repo saved on disk, run a `git fetch` and then checkout the develop branch. I've added the ability to add external sources. You'll need to specify the exact url when prompted for the the `Repository`. This hasn't been tested all that thoroughly, but let me know if this is what you had in mind.

**Comment by AndrewSav** [comment]
@Bee-Mar thank you very much. As it happens, I'm going to be on holiday until the end of next week, and will have a limited access to the hardware I'm running MM on. I appreciate your changes very much, that would allow me personally to make a few important for me changes in the plugins that are no longer maintained and have an automated way for setting them up and updating. It's unfortunate that I won't be able to work on it in the immediate future. I'm also sorry if this is disappointing.

**Comment by Bee-Mar** [comment]
@AndrewSav not a problem, whenever you get a chance, feel free to try it out and give feedback. Enjoy your holiday!

**Comment by Bee-Mar** [comment]
@AndrewSav I'm going to close this for now. Let me know if anything seems to be off in behavior
