### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by n4tur3502** [Bee-Mar/mmpm#110]
Is this an issue with the CLI or GUI?
CLI

When I run the guided setup after install i get an error that says "ERROR: Failed to start MMPM SystemD service. See `mmpm log` for details
Remove the MMPM GUI?"
Run mmpm --guided-setup

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release` 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
- output from `python3 --version`
Python 3.10.4
- Web Browser (firefox, chrome, safari, chromium, etc)
n.a

**MMPM Environment Settings**

- output from `mmpm env`
- {
  "MMPM_MAGICMIRROR_ROOT": "/home/mom/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://127.0.1.1:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by Bee-Mar** [comment]
You're asking how to remove the gui? The option is in the Wiki:

mmpm uninstall --gui
