### ISSUE TITLE
What is the URL to reach the package manager?

### ISSUE THREAD

**Issue by jwillmer** [Bee-Mar/mmpm#118]
I can't find it in the WIKI -.-

**Comment by Bee-Mar** [comment]
mmpm list --gui-url

**Comment by jwillmer** [comment]
Can I also make it accessible from outside? I like to manage the packages remotely .

**Comment by Bee-Mar** [comment]
That's not something I ever intend to support. 

If you want to go about configuring the nginx server and setting up https with a proper certificate and all the rest with MagicMirror, go for it.

**Comment by jwillmer** [comment]
No problem. I just tunnel through SSH. But please add this information to the README. It is the only thing missing to test out the module ;-)
