### ISSUE TITLE
Unable to retrieve active modules and getting an error on open in the GUI

### ISSUE THREAD

**Issue by JeremyGarrard** [Bee-Mar/mmpm#119]
I have IPwhitelist set to [], installed the module, added to config, etc etc as far as I can see others having had issues and solved them.  No matter what I do I'm making no progress on this.  When I open it tells me 'unable to retrieve active modules' on the left and gives the me below error in counsel on open. 

Any help would be greaT!!

DevTools failed to load source map: Could not load content for http://127.0.1.1:7890/static/assets/min-maps/vs/base/worker/workerMain.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Bee-Mar** [comment]
@JeremyGarrard there is a new version, 3.0 which should solve the problem that was happening

**Comment by M3GNOON** [comment]
> @JeremyGarrard there is a new version, 3.0 which should solve the problem that was happening

Hi!  I have went through all resolutions revolving around this issue back to 2020 and have not come to a fix for this.  I am also on version 3.0.  Any directives or advice is appreciated.  Thank you for your time!

**Comment by dahenson54** [comment]
> @JeremyGarrard there is a new version, 3.0 which should solve the problem that was happening

I'm also having issues with "Unable to retrieve active modules" on version 3.0. I've tried correcting the things it lists out to correct, and it yielded no change.

**Comment by Bee-Mar** [comment]
@JeremyGarrard @M3GNOON @dahenson54 version 4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
