### ISSUE TITLE
BUG: Where is Version 2.15?

### ISSUE THREAD

**Issue by frizat82** [Bee-Mar/mmpm#122]
I keep seeing version 2.15 as the "solution" to the http/ipv6 issues - but the code here stops on April 2022?  Where is 2.15 or greater?

**Comment by Bee-Mar** [comment]
I'm going to publish a new version (2.15) tomorrow. I can't quite say if it'll be the solution to the IPV6 problem, but it'll solve other issues.

**Comment by MarkEnverus** [comment]
Thanks

**Comment by Bee-Mar** [comment]
@MarkEnverus that release will actually need to be pushed back a couple days. Some unexpected family stuff needs attention.

**Comment by MarkEnverus** [comment]
no rush - i have a workaround!

**Comment by Bee-Mar** [comment]
@MarkEnverus 2.15 is available now

`pip install --upgrade --no-cache-dir mmpm`

or 

`pip install mmpm==2.15`

**Comment by Bee-Mar** [comment]
@MarkEnverus sorry, install version 2.16. There was a small typo in an API url and it causes the GUI to not load properly. 2.16 is currently running through the pipeline  and should be available within a few minutes

**Comment by Bee-Mar** [comment]
@MarkEnverus version 2.16 is now available

**Comment by Bee-Mar** [comment]
@MarkEnverus small snafoo again lol. Version 2.17 is what you'll want to download/upgrade to

`pip uninstall mmpm; pip install mmpm==2.17`

just to make sure all the files are cleaned
