### ISSUE TITLE
Failed to start A high performance web server and a reverse proxy server.

### ISSUE THREAD

**Issue by kibotu** [Bee-Mar/mmpm#13]
how do you install this with different port?

**Comment by Bee-Mar** [comment]
@kibotu would it be possible to post some relevant information from `journalctl -xe` as well?

The nginx settings can be configured in the `configs/mmpm.conf` file. However, note that changing that port will also require modifying the api url in the web interface.

**Comment by Bee-Mar** [comment]
@kibotu Hopefully this guide I threw together will be of use to you, and anyone else that might have the same issue.

https://github.com/Bee-Mar/mmpm/wiki/Changing-NGINX-Port-Numbers

**Comment by kibotu** [comment]
thanks for your replies 

so it turns out you need to disable all running nginx instances e.g. pi-hole during installation and I missed that ^^'

**Comment by Bee-Mar** [comment]
@kibotu Thanks for the heads up on that! I'll make a quick note of that on the installation wiki page for other users.

**Comment by kibotu** [comment]
I could install mmpm successfully and configure the magic mirror via the browser gui however after rebooting the pi, it wouldn't reboot the mmpm service, so I ran

```shell
sudo systemctl status nginx.service
```
```shell
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-03-26 18:50:46 CET; 9s ago
     Docs: man:nginx(8)
  Process: 3581 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 3582 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Mar 26 18:50:44 hal9000 nginx[3582]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Mar 26 18:50:44 hal9000 nginx[3582]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Mar 26 18:50:45 hal9000 nginx[3582]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Mar 26 18:50:45 hal9000 nginx[3582]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Mar 26 18:50:45 hal9000 nginx[3582]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Mar 26 18:50:45 hal9000 nginx[3582]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Mar 26 18:50:46 hal9000 nginx[3582]: nginx: [emerg] still could not bind()
Mar 26 18:50:46 hal9000 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 26 18:50:46 hal9000 systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 26 18:50:46 hal9000 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

found a fix on [stackoverflow](https://stackoverflow.com/a/52894517):

change the port may help as 80 port is already using somewhere

```shell
vi /etc/nginx/sites-available/default
```

Change the port: (note: I ended up using 8181, since 8080 was already taken too)

```shell
listen 8080 default_server;
listen [::]:8080 default_server;
```

And then restart the nginx server

```shell
nginx -t
service nginx restart
```

so now pi-hole, magic-mirror and mmpm run together thanks for pointing in right direction, also thanks for the awesome ui

**Comment by Bee-Mar** [comment]
@kibotu You're quite welcome! Feel free to give any feedback on the interface, and CLI.

**Comment by kibotu** [comment]
not sure where to put this but loving the ui, the only thing i found curious was that you can show only up to 10 packages per page, also  as enhancement out of the box and probably out of scope of the project would be a merge of concept for https://github.com/Jopyth/MMM-Remote-Control where you can enable added modules easier

**Comment by Bee-Mar** [comment]
@kibotu I chose to leave the max as 10 for now just because i was trying to get a basic layout where all the pages lined up cleanly when switching between tabs. This can be modified in future updates. Hmm, there might be a way handling that sort of addition. My first thought is adding a conditional tab with an embedded iframe, and seeing if that ip address can be brought in from the config file, but again, this is all theoretical...but it certainly looks like it would be a cool addition. You can throw that under the issues as an enhancement idea

**Comment by Bee-Mar** [comment]
@kibotu also, thank you for the complement! Feel free to spread the word of this project to any other users you may know :)
