### ISSUE TITLE
BUG: unable to see config editor, marketplace in gui

### ISSUE THREAD

**Issue by fpy-homeb** [Bee-Mar/mmpm#130]
**Describe the Bug**

Is this an issue with the CLI or GUI?

Is this something that should be put in the Wiki?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`

- output from `python3 --version`

- Web Browser (firefox, chrome, safari, chromium, etc)

**MMPM Environment Settings**

- output from `mmpm env`

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

Hey, 
This might be a "me" issue, I have got the control centre working, I can show hide modules. But anything which involves the pi eg restart, config editor, marketplace etc don't work or show a blank screen? 

Might I have missed something within the setup? 

Any help on a install step I might have missed would be great! 
Thanks

**Comment by Bee-Mar** [comment]
Please include the list of steps, any errors that were displayed, as well as the log files as requested in the bug report template.

**Comment by fpy-homeb** [comment]
Hey, sorry, this will be a bit piecemeal 


sudo apt update
sudo apt full-upgrade

Install MM

1. download and install the latest Node.js version:
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt install -y nodejs
2. Clone the repository and check out the master branch: 
3. git clone https://github.com/MichMich/MagicMirror
4. Enter the repository: cd MagicMirror/
5. Install the application: npm run install-mm
6. Make a copy of the config sample file: cp config/config.js.sample config/config.js
7. Start the application: npm run start 

Install Pm2 

sudo npm install -g pm2
pm2 startup
cd ~
nano mm.sh

cd ./MagicMirror
DISPLAY=:0 npm start


chmod +x mm.sh

pm2 start mm.sh
pm2 save

Install MMPM 

sudo apt install libffi-dev nginx-full -y
python3 -m pip install --upgrade --no-cache-dir mmpm
mmpm --guided-setup
echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
source ~/.bashrc 


That's my installation guide

I have modified the config file in mm to accept all internal traffic

**Comment by Bee-Mar** [comment]
@fpy-homeb when you open the GUI for MMPM, can you press F12 to open the dev-console, then try to navigate to the editor page and see if there's any error ouput

**Comment by Bee-Mar** [comment]
@fpy-homeb version 4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
