### ISSUE TITLE
BUG: Unable to retrieve active modules and can't edit config files in the web interface

### ISSUE THREAD

**Issue by LightTemplar** [Bee-Mar/mmpm#132]
**Describe the Bug**
In the web Interface of MMPM there is a message "Unable to retrieve active modules" and I can't edit config files in the web interface - they all are shown empty.

**To Reproduce**
1. I installed Magic Mirror and MMPM in Docker using docker compose from this template: https://gitlab.com/khassel/magicmirror/-/blob/master/run/serveronly_mmpm.yml, set own volume and ports.
2. in the `~/.config/mmpm/mmpm-env.json` I tried many values for `MMPM_MAGICMIRROR_URI`:  `http://172.23.0.2:8080` (ip from docker container), `http://mm:8080` (container name), `http://myserver:10080` (my server with docker containers and outter port) and restarted both containers - nothing helped.

**Expected behavior**
I wanted to manage plugins of Magic Mirror 

**Operating System, Python3 Version, and Web Browser**\

_- output from `cat /etc/os-release`_
couldn't login into container shell.
_- output from `python3 --version`_
couldn't login into container shell.

_- Web Browser (firefox, chrome, safari, chromium, etc)_
Brave: [Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)]

**MMPM Environment Settings**

_- output from `mmpm env`_ 
couldn't login into container shell. So I attached a `mmpm-env.json`

**MMPM Log Files**

_- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`_ 
Downloading MMPM log files doesn't work as well - hitting the button does nothing. But I attached a non empty file from `~/.config/mmpm/log` folder.

**MagicMirror Config**

_- your MagicMirror `config.js`_
see attachment.
[mmpm.zip](https://github.com/Bee-Mar/mmpm/files/10558171/mmpm.zip)

**Comment by M3GNOON** [comment]
> "Unable to retrieve active modules"

Hi!  I also am experiencing this issue "Unable to retrieve active modules" in GUI. Please let me know if you have found a solution for this. Thanks!

**Comment by loguk** [comment]
I also have this problem.

I can start - stop - restart, but config show an empty instance - I have installed the "module" mmpm - I have tried all sorts of mm and mmpm configurations (using the direct copies from the examples just changing my own LAN ip address for the pi.

Running in CLI, any attempt to use mm-ctl fails asking "Is MagicMirror running" - it is and I have it displaying in a browser on my PC as well as on the pi display device

**Comment by Bee-Mar** [comment]
if you open MagicMirror in your browser, press the F12 key. You'll see the dev-console. Can you see if there are any errors related to the `mmpm` module?

**Comment by Bee-Mar** [comment]
@LightTemplar since you're running MMPM as a docker image, what is your configuration like for running it? Are you passing the host network through the `docker run` command?

**Comment by Bee-Mar** [comment]
@M3GNOON can you please provide the same information @LightTemplar did? 

- output from `mmpm env` (the file is located in `~/.config/mmpm/mmpm-env.json`)
- your `config.js`
- and log file output `mmpm log --zip`

**Comment by LightTemplar** [comment]
> @LightTemplar since you're running MMPM as a docker image, what is your configuration like for running it? Are you passing the host network through the `docker run` command?

No `docker run`s, only `docker-compose up -d`. Link to template, I used, is in the issue description. 

Today, while I run it again, there was an error popup, that it can't connect to `my_server:7890` - which was wrong, because I remapped port to `17890`. 
So I checked if it will work without port remapping, with default `7890` and `7892` - and it worked. 
Is there a way to make it work with remapped ports?

**Comment by Aasikki** [comment]
For me, editing config files works fine, but retrieving active modules does not, these are the error messages in my browsers console
![image](https://user-images.githubusercontent.com/58399890/223713255-d592a1de-23b6-47fa-96fc-895408c9a9ee.png)

**Comment by masseym** [comment]
same here for me

**Comment by Bee-Mar** [comment]
@Aasikki @loguk @masseym version 4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
