### ISSUE TITLE
BUG: Active Modules  not showing on GUI

### ISSUE THREAD

**Issue by MikeBiggerstaff** [Bee-Mar/mmpm#135]
**Describe the Bug**
Active Modules not showing up in webgui.

Is this an issue with the CLI or GUI?
 GUI

Is this something that should be put in the Wiki?
IDK

1.Installed MagicMirror on PI4b 4gb 32BIT Raspbian
2.Installed MMPM using script
sudo apt install libffi-dev nginx-full -y
python3 -m pip install --upgrade --no-cache-dir mmpm
mmpm --guided-setup
echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
source ~/.bashrc
3.installed mmpm module 
4. added mmpm module to config.js
5. made sure ENV Variables are all correct
6. forwarded necessary ports on my PFSense
7. accessed GUI

**Expected behavior**
to access the ability to install modules and administer them via webgui

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
Mike@MagicMirror:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- output from `python3 --version`
Python 3.9.2
- Web Browser (firefox, chrome, safari, chromium, etc)
chromium
**MMPM Environment Settings**
{
  "MMPM_MAGICMIRROR_ROOT": "/home/Mike/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.0.225:8081",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}

**MMPM Log Files**

- Attach the file produced `Download MMPM log
[mmpm-logs-2023-4-6.zip](https://github.com/Bee-Mar/mmpm/files/11470922/mmpm-logs-2023-4-6.zip)
 files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`
/* MagicMirror² Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 *
 * You can use environment variables using a `config.js.template` file instead of `config.js`
 * which will be converted to `config.js` while starting. For more information
 * see https://docs.magicmirror.builders/configuration/introduction.html#enviromnent-variables
 */
let config = {
	address: "192.168.0.225",	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8081,
	basePath: "/",			// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
					  		// you must set the sub path here. basePath must end with a /
	ipWhitelist: [],	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 12,
	units: "imperial",

	modules: [
        {
        module: "alert"
        },
        // ... other modules in the array
        // ... more modules
        // now add the MMPM module
        {
        module: "MMM-mmpm"
        },
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
			
		{
    module: 'MMM-GoogleCalendar',
    header: "Upcoming Things",
    position: "top_left",
    config: {
        calendars: [
            {
              symbol: "calendar-week",
              calendarID: "mike@mikebiggerstaff.me"
            },
            // add another calendar HERE if needed
        ],
    }
},
		
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "Mexico MO",
				locationID: "4398103", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "41e3ceadce3b35fa41a3cd2a7358c7a0"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "Mexico MO",
				locationID: "4398103", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "41e3ceadce3b35fa41a3cd2a7358c7a0"
			}
		},
			
		
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
	         		{
						title: "Mexico KXEO News",
						url: "https://kxeo.com/category/mexico-news/feed/"
					},
					{
						title: "Mexico Ledger News",
						url: "https://mexicoledger.com/browse.rss"
					},
										
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		
		 {
			module: "MMM-DailyPower",
			position: "bottom_bar",       // This can be any region
			config: {
				// See 'Configuration options' for more information.
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by MikeBiggerstaff** [comment]
ive also noticed these in console in chrome attached is console log
i changed the names for the files it couldnt find in console from mmpm to MMM-mmpm but active modules still didnt load but the missing files did.
[192.168.0.225-1684027762325.log](https://github.com/Bee-Mar/mmpm/files/11470926/192.168.0.225-1684027762325.log)

**Comment by MikeBiggerstaff** [comment]
this is the console log from the MMPM GUI homepage

[192.168.0.225-1684028006630.log](https://github.com/Bee-Mar/mmpm/files/11470927/192.168.0.225-1684028006630.log)

**Comment by MikeBiggerstaff** [comment]
from mmpm config gui page console output
[192.168.0.225-1684028149845.log](https://github.com/Bee-Mar/mmpm/files/11470928/192.168.0.225-1684028149845.log)

**Comment by MikeBiggerstaff** [comment]
also cannot install any modules from mmpm marketplace i can check the module and click install but nothing happens.

**Comment by MikeBiggerstaff** [comment]
was able to get it working by renaming files from mmpm to MMM-mmpm then back to mmpm then restarted MM and then stuff started to work. theres a naming convention issue somewhere in the js

**Comment by MikeBiggerstaff** [comment]
still cant install anything from marketplace though

**Comment by Bee-Mar** [comment]
@MikeBiggerstaff I was out of town for work, but will take a closer look into your issue later today

**Comment by MikeBiggerstaff** [comment]
Thanks if you need to remote in let me know. I can donate for your time.

**Comment by bannert1337** [comment]
This issue might be related to #132, #119 and #130. I am experiencing the same problem right now. 
I run MagicMirror and MMPM inside Docker containers and use NGINX Proxy Manager to forward requests from subdomains to the corresponding Docker container and port. 
The following error messages are displayed in the console when I visit MMPM's website:

`Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.`

`Mixed Content: The page at 'https://mmpm.domain.tld/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mmpm.domain.tld:7890/api/mmpm/environment-vars'. This request has been blocked; the content must be served over HTTPS.`

This implies that MMPM does not respect incoming HTTPS connections and is hardcoded to use HTTP and port `7890` when making requests to the API. I could not find any setting to change the connection type or port. I tried to rewrite/redirect the incoming request to HTTPS and the exposed port, but failed.

**Comment by devtobi** [comment]
@bannert1337 I opened a small PR that should fix the problem if MMPM is served behind a reverse proxy. @Bee-Mar please take a look! :)

**Comment by Bee-Mar** [comment]
> @bannert1337 I opened a small PR (see https://github.com/Bee-Mar/mmpm/pull/136) that should fix the problem if MMPM is served behind a reverse proxy. @Bee-Mar please take a look! :)

Sorry for the delay, I just merged your PR. Thanks for contributing! I'm still in the the process of a total rewrite and will structure things much better and address some of the issues experienced along the way.

**Comment by masseym** [comment]
i have the same problem with "Unable to retrieve active modules" but I am able to install new modules without issue.

**Comment by Bee-Mar** [comment]
@masseym @MikeBiggerstaff @bannert1337 version 4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
