### ISSUE TITLE
BUG: MM won't launch after installing modules

### ISSUE THREAD

**Issue by rroach3753** [Bee-Mar/mmpm#144]
**Describe the Bug**

Is this an issue with the CLI or GUI? N/A

Is this something that should be put in the Wiki? Maybe

**To Reproduce**
Install a module from Marketplace and then restart MM.  MM does not load until I uninstall the module.

**Expected behavior**
MM Starts after installing a module (regardless of whether config is setup to call it or not).

**Screenshots**
N/A

**Operating System, Python3 Version, and Web Browser**\

- output from `cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- output from `python3 --version`
Python 3.11.2

- Web Browser (firefox, chrome, safari, chromium, etc)
Chromium (latest available as of 19OCT23)

**MMPM Environment Settings**

- output from `mmpm env`
"MMPM_MAGICMIRROR_ROOT": "/home/xxxxx/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://10.0.0.16:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`
Currently using the default config.js

[mmpm-logs-2023-9-4.zip](https://github.com/Bee-Mar/mmpm/files/13048033/mmpm-logs-2023-9-4.zip)

**Comment by Bee-Mar** [comment]
@rroach3753 I'll be resolving these issues shortly

**Comment by rroach3753** [comment]
@Bee-Mar , you sir... are a gentleman and a scholar!  Many thanks to you!

**Comment by Bee-Mar** [comment]
@rroach3753 Sorry to have not gotten around to resolving this, but I'm currently in the midst of completely reworking the application and will have this issue resolved in the 4.0.0 release. The branch with all active changes can be found on code-cleanup and it will be release soon.

**Comment by Bee-Mar** [comment]
@rroach3753  4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)

**Comment by rroach3753** [comment]
Following your guidance: python3 -m pip uninstall mmpm
![image](https://github.com/Bee-Mar/mmpm/assets/74986787/5afb2d91-2883-44bf-ad9e-e4ffe5aa57ad)

**Comment by Bee-Mar** [comment]
@rroach3753 what version of python are you using? This is unfortunately not a `mmpm` problem, but something that's very annoying nonetheless. 

This thread has a few different possible solutions:


https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3

**Comment by rroach3753** [comment]
> @rroach3753 what version of python are you using? This is unfortunately not a `mmpm` problem, but something that's very annoying nonetheless.
> 
> This thread has a few different possible solutions:
> 
> https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3

python3-pip is already the newest version (23.0.1+dfsg-1+rpt1)

**Comment by Bee-Mar** [comment]
@rroach3753 sorry, not the version of `pip`, the `python3 --version`

**Comment by Bee-Mar** [comment]
@rroach3753 also, that output happens during `uninstall` of `mmpm`?

**Comment by rroach3753** [comment]
> @rroach3753 sorry, not the version of `pip`, the `python3 --version`

My bad, 3.11.2

**Comment by rroach3753** [comment]
> @rroach3753 also, that output happens during `uninstall` of `mmpm`?

When I run the last two lines of the four lines you provided in your upgrade link, yes that is the result.

**Comment by rroach3753** [comment]
This has resolved my issue: 
sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old

**Comment by Bee-Mar** [comment]
> This has resolved my issue: sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old

@rroach3753 great! Honestly, I don't know why python 3.11 seems to be causing these problems. I personally have never encountered this issue, but have seen a coworker deal with it

**Comment by rroach3753** [comment]
However, I'm getting "invalid requirment: '--no-cache-dir' on python3 -m pip install —-no-cache-dir mmpm

**Comment by rroach3753** [comment]
> > This has resolved my issue: sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old
> 
> @rroach3753 great! Honestly, I don't know why python 3.11 seems to be causing these problems. I personally have never encountered this issue, but have seen a coworker deal with it

Right, such a pain.  Sometimes I find it easier just to wipe and start from scratch (I have a copy of my config file).

**Comment by rroach3753** [comment]
If I remove the --no-cache-dir piece from the cmd it runs fine.

**Comment by Bee-Mar** [comment]
@rroach3753 That's also strange. Pip 23 has that option, and it should work just fine. I'll update the instructions to exclude that argument. It's odd because the build pipeline tests with 3.8, 3.9, 3.10, and 3.11 with those options lol

**Comment by rroach3753** [comment]
So weird, and I'm not stuck with a bad gateway error.  
![image](https://github.com/Bee-Mar/mmpm/assets/74986787/2a9ad4b7-f360-49c5-8faf-7667cbe9a47a)

**Comment by Bee-Mar** [comment]
@rroach3753 oh, I would definitely not recommend using `sudo` when installing python packages. You'll get stuck with some conflicting dependency issues

**Comment by Bee-Mar** [comment]
@rroach3753 I also can't guarantee features will work as expected when installing with sudo

**Comment by rroach3753** [comment]
> @rroach3753 oh, I would definitely not recommend using `sudo` when installing python packages. You'll get stuck with some conflicting dependency issues

Yeah, I'm not a python guy (just enough to get past an entry (very entry) level class....lol...that was open book tested.

**Comment by Bee-Mar** [comment]
> > @rroach3753 oh, I would definitely not recommend using `sudo` when installing python packages. You'll get stuck with some conflicting dependency issues
> 
> Yeah, I'm not a python guy (just enough to get past an entry (very entry) level class....lol...that was open book tested.

@rroach3753 haha no worries. If you can, I would recommend uninstalling and reinstalling without `sudo`. Also thank you for being one of the first adopters of the new version. It should _hopefully_ be much more stable, and easier to work with

**Comment by rroach3753** [comment]
> > > @rroach3753 oh, I would definitely not recommend using `sudo` when installing python packages. You'll get stuck with some conflicting dependency issues
> > 
> > 
> > Yeah, I'm not a python guy (just enough to get past an entry (very entry) level class....lol...that was open book tested.
> 
> @rroach3753 haha no worries. If you can, I would recommend uninstalling and reinstalling without `sudo`. Also thank you for being one of the first adopters of the new version. It should _hopefully_ be much more stable, and easier to work with

My pleasure.  Trying that now.

**Comment by rroach3753** [comment]
Re-run: but still getting a 502 Bad Gateway error: 
![image](https://github.com/Bee-Mar/mmpm/assets/74986787/da307b64-9d8d-4f32-b8bd-c3e6eb4ee8ea)

**Comment by Bee-Mar** [comment]
@rroach3753 oh, sorry you're talking about accessing the UI? To install the UI you need `pm2` installed, and then you can run `mmpm ui install -y`

`npm install -g pm2`

`mmpm ui install -y`

**Comment by rroach3753** [comment]
Yeah, I use the UI.  I do have pm2 installed.  unless it's uninstalled with the upgrade process.

**Comment by Bee-Mar** [comment]
@rroach3753 if you had installed , then it should still be there. MMPM doens't manipulate anything with that package, just makes use of it

**Comment by rroach3753** [comment]
> @rroach3753 if you had installed , then it should still be there. MMPM doens't manipulate anything with that package, just makes use of it

Got it.  After running the install of the UI I'm getting "the requested URL was not found on the server."  LOL.  I may just rebuild tomorrow night when I get home from work.

**Comment by Bee-Mar** [comment]
could you try running the following:

`pm2 list`

`curl 0.0.0.0:7891/api/index`

`curl 0.0.0.0:7890`

`mmpm list -a`

**Comment by Bee-Mar** [comment]
@rroach3753 also, try running `sudo systemctl daemon-reload`

**Comment by rroach3753** [comment]
> could you try running the following:
> 
> you don't need to post the info from these
> 
> `pm2 list` (are all the mmpm services online?)
> 
> `curl 0.0.0.0:7891/api/index` (does this give you a JSON formatted list of endpoints?) If you use firefox, it will pretty print the information for you
> 
> `curl 0.0.0.0:7890` (does this give you anything?)
> 
> `mmpm list -a` (do you get a list of packages?)

![image](https://github.com/Bee-Mar/mmpm/assets/74986787/dac2a0db-bcc7-45f8-a223-c76905451c9c)

**Comment by rroach3753** [comment]
I've got to get some dinner.  Back in like 30 minutes.  You don't have to keep troubleshooting with me.  I can do a fresh install of MM and MMPM tomorrow.

**Comment by Bee-Mar** [comment]
hmm, so after you uninstalled `mmpm`, and did it without `sudo`, it must have been installed in your `--user` path, which should be in `~/.local/bin`, and I'm guessing that's not in your `PATH`. Can you run `~/.local/bin/mmpm` to see if that prints out the file name? If so, you'll need to add that directory to your path based on the small instruction listed on the README.

**Comment by rroach3753** [comment]
Sure, stand by

**Comment by Bee-Mar** [comment]
@rroach3753 my bad I meant `ls ~/.local/bin/mmpm` lol

**Comment by Bee-Mar** [comment]
either one would work though, if you did it without `ls`, then you'll just get the help message, assuming that's where it is

**Comment by rroach3753** [comment]
> @rroach3753 my bad I meant `ls ~/.local/bin/mmpm` lol

![image](https://github.com/Bee-Mar/mmpm/assets/74986787/f618505b-aec1-4780-8cf4-59c120c09c8d)

**Comment by rroach3753** [comment]
> @rroach3753 my bad I meant `ls ~/.local/bin/mmpm` lol

![image](https://github.com/Bee-Mar/mmpm/assets/74986787/08667166-0a3b-4a3e-8a03-337eea49eb9e)

**Comment by Bee-Mar** [comment]
@rroach3753 great, so if you do this 


```sh
echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc && source ~/.bashrc
```

You'll be setup

**Comment by Bee-Mar** [comment]
@rroach3753 also, it might be worthwhile doing this `sudo systemctl stop nginx; sudo systemctl disable nginx` unless you need `nginx` for something else.

**Comment by rroach3753** [comment]
> @rroach3753 also, it might be worthwhile doing this `sudo systemctl stop nginx; sudo systemctl disable nginx` unless you need `nginx` for something else.

This pi is only running MM.

**Comment by Bee-Mar** [comment]
> > @rroach3753 great, so if you do this
> > ```shell
> > echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc && source ~/.bashrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You'll be setup
> 
> That gives me: ![image](https://private-user-images.githubusercontent.com/74986787/291438952-0a418e9d-0d99-4ba0-a4ef-8a341591299a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NDUyMDUsIm5iZiI6MTcwMjk0NDkwNSwicGF0aCI6Ii83NDk4Njc4Ny8yOTE0Mzg5NTItMGE0MThlOWQtMGQ5OS00YmEwLWE0ZWYtOGEzNDE1OTEyOTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAwMTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOGI1MGE5YjAzNzdiZmU2ZGUyYzM5NjA1NTc2YWVkMmI4ZWRlMzg2M2E2MjcwMTNlNDI3ODEzODJlNjVmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49aopOgvfF9zkJUi_BGga86WpIzHWAc_pQY24c0Xu2s)
> 
> I think it may be best for me to build a fresh install if it's this mucked up.

@rroach3753 also, it might be worthwhile doing this `sudo systemctl stop nginx; sudo systemctl disable nginx` unless you need `nginx` for something else.

**Comment by Bee-Mar** [comment]
> > @rroach3753 also, it might be worthwhile doing this `sudo systemctl stop nginx; sudo systemctl disable nginx` unless you need `nginx` for something else.
> 
> This pi is only running MM.

then you should be good to get rid of nginx, We'll figure this out when you get another chance. Thanks for helping me learn more issues that might arise lol

**Comment by rroach3753** [comment]
I can ping you tomorrow after I get home from work and the doc (7pm-ish Eastern).

**Comment by rroach3753** [comment]
> > > @rroach3753 also, it might be worthwhile doing this `sudo systemctl stop nginx; sudo systemctl disable nginx` unless you need `nginx` for something else.
> > 
> > 
> > This pi is only running MM.
> 
> then you should be good to get rid of nginx, We'll figure this out when you get another chance. Thanks for helping me learn more issues that might arise lol

I'm home and free for a couple hours.

**Comment by rroach3753** [comment]
Just an FYI, I shutdown my MM for the holiday as I was away.  I powered it back on when I got home and the MMPM interface no longer loads reglardless of what I do.  MM is running.  I think I'm going to perform a fresh install of MM, modules, and MMPM this weekend.

**Comment by rroach3753** [comment]
Fresh install completed.  MMPM gui now loads, but unable to install any packages/modules.

**Comment by Bee-Mar** [comment]
There's been a patched version 4.0.4 uploaded. Try upgrading and see the wiki on how to enable the UI to restart on reboots. It's under the page about installing the UI.

**Comment by Bee-Mar** [comment]
Also, if the problem persists can you open a new issue with your logs attached as well

**Comment by landaisbenj** [comment]
https://github.com/Bee-Mar/mmpm/issues/144#issuecomment-1861851151 

Work for me too
