### ISSUE TITLE
BUG: GUI unable to connect to MM (MM is refusing connection) causing Active Modules to no show up

### ISSUE THREAD

**Issue by refy02** [Bee-Mar/mmpm#145]
**Describe the Bug**

Is this an issue with the CLI or GUI?
GUI

Is this something that should be put in the Wiki?

The MMPM is unable to connect to MagicMirror. All settings have been made according to the documentation. For some reason the MagicMirror seems to refuse the connection to MMPM, altough my IP whitelist is blank. This error causes my MMPM Gui to show no active modules. This bug has already been discussed in #60 and #67 2 years ago. And more recently in #135. @Bee-Mar If I got it right (from #135) you are currently working on fixing the issue? Maybe my following input will be helpful for you. I am not using Docker btw 

**To Reproduce**
Fresh installment of MM and MMPM. Usage of PM2.

**Expected behavior**
GUI shows me Active modules

**Screenshots**
![ActiveModules](https://github.com/Bee-Mar/mmpm/assets/93187270/ffb57124-121b-4634-b9af-1f5e9eccea62)

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
`PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
`

- output from `python3 --version`
`Python 3.9.2`

- Web Browser (firefox, chrome, safari, chromium, etc)
Chromium

**MMPM Environment Settings**

- output from `mmpm env`
`
  "MMPM_MAGICMIRROR_ROOT": "/home/fynn/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.2.188:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}
`

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`
[mmpm-logs-2023-11-5.zip](https://github.com/Bee-Mar/mmpm/files/13259172/mmpm-logs-2023-11-5.zip)

**MagicMirror Config**

- your MagicMirror `config.js`
![MM-Config_1](https://github.com/Bee-Mar/mmpm/assets/93187270/372b60d0-6046-494c-a89d-b3c81edb81e4)
![MM-Config_2](https://github.com/Bee-Mar/mmpm/assets/93187270/e612aa54-f130-4e0f-97d9-5393ac3288e6)

**Comment by Bee-Mar** [comment]
@refy02 @istvanfedak @khassel @devtobi  4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
