### ISSUE TITLE
Error-code 500 on webGUI: http failure

### ISSUE THREAD

**Issue by Pip32** [Bee-Mar/mmpm#15]
Hey folks,

if i try to connect via webGUI, I get instantly following error message:

Error Code: 500
Message: Http failure response for http://localhost:7890/api/all-installed-modules: 500 INTERNAL SERVER ERROR

GUI then loading, but all chapters are empty besides MM-config

When try to list installed packages via terminal, works so far, only web GUI somehow crashes.

Did someone had the same problem? Is there a fix? Couldn't find anything in the wiki.

Running current MM2 on a RP 3+ with Raspbian full, nearly fresh install of MM.

Thanks,

**Comment by Bee-Mar** [comment]
@Pip32 there is a section in the Wiki mentioning this, under “Known Issues.” It’s something unfortunately I cannot directly fix, but am trying to find a viable workaround. There’s a known bug in Eventlet causing this, and the only workaround they suggest is using an older version of Python 3

**Comment by Bee-Mar** [comment]
@Pip32 in the latest release, 1.08, the json file containing all 3rd party modules is populated during the installation. This appears to at least mitigate an initial 500 error when loading the web-application the first time.
