### ISSUE TITLE
BUG:  python3 -m pip install mmpm only installs the 3.1 version

### ISSUE THREAD

**Issue by revere521** [Bee-Mar/mmpm#150]
**Describe the Bug**
It doesn't yet appear to be possible to install version 4.x with pip

**To Reproduce**
I followed the steps (commands) in the wiki to migrate to version 4.x.x and can only install version 3.1.  

` python3 -m pip install mmpm==4
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mmpm==4
  Could not find a version that satisfies the requirement mmpm==4 (from versions: 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 2.11, 2.12, 2.13, 2.14, 2.17, 3.0, 3.1)
No matching distribution found for mmpm==4
`

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
`

- output from `python3 --version` `Python 3.7.3
`

- Web Browser (firefox, chrome, safari, chromium, etc) Firefox

**MMPM Environment Settings**

- output from `mmpm env` `+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/entrypoint.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 51, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1054, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1135, in retrieve_packages
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1135, in <listcomp>
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
  File "/home/pi/.local/lib/python3.7/site-packages/bs4/element.py", line 982, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'contents'`

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by Bee-Mar** [comment]
The version number you're looking for 4.0.0, rather than 4. Also, only Python>=3.8 is supported. Please see the Wiki on how to upgrade your Python version. Once you've done that, you'd want to run 'python3 -m pip install mmpm==4.0.0'

**Comment by revere521** [comment]
Got it! thanks.  Python 3.7.3 is the maximum on raspbian buster, so I'll need to look at bumping up to Bullseye for 3.8+

I'll try again afterward, sorry for the false bug

**Comment by revere521** [comment]
Closing

**Comment by Bee-Mar** [comment]
Sounds good, and thanks!
