### ISSUE TITLE
BUG: Failed to load subcommand modul

### ISSUE THREAD

**Issue by editwentyone** [Bee-Mar/mmpm#151]
version 4.0, on python 3.8.18

I get `[ERROR] Failed to load subcommand module: module 'importlib.resources' has no attribute 'files'
[ERROR] Failed to load subcommand module: module 'importlib.resources' has no attribute 'files'` whenever I use a command.

also I can't get `mmpm ui install -y` to work, this command is not in the list. `mmpm install ui` worth I try but also without luck

**Comment by Bee-Mar** [comment]
@editwentyone I am able to reproduce this and will get a fix out ASAP. It doesn't appear to be an issue on Python >= 3.9.x

**Comment by editwentyone** [comment]
hey sure, thank you for this real quick reaction :) do you want me to stay on 3.8 for testing? no benefits going upwards or are there any?

**Comment by Bee-Mar** [comment]
@editwentyone there shouldn't be any additional "benefits" of going up to a newer version of Python other than knowing that MMPM should work just fine on python>=3.9

**Comment by Bee-Mar** [comment]
@editwentyone a fix is getting pushed shortly

**Comment by Bee-Mar** [comment]
@editwentyone version 4.0.2 is available now and should have that issue fixed

**Comment by Bee-Mar** [comment]
@editwentyone spoke too soon

**Comment by editwentyone** [comment]
4.0.3 did the trick :)
