### ISSUE TITLE
No uninstall script available and unable to open the toolbar

### ISSUE THREAD

**Issue by arnedebeer** [Bee-Mar/mmpm#16]
According to the wiki I should be able to cd into the directory and type in 'uninstall' just like the command 'make', unfortunately this does not work. Also since installing mmpm I can no longer press alt to get the toolbar or F11 to close fullscreen.

**Comment by Bee-Mar** [comment]
In the wiki I mention those are all `make` targets, meaning you need to prepend `make` to all targets listed (ie, `make uninstall`). The effect of not being able to change full screen of your browser has nothing to do with MMPM, this is something I can assure you has nothing to do with any of the code in the application.

**Comment by arnedebeer** [comment]
Ah alright! Sorry for my ignorance!

**Comment by Bee-Mar** [comment]
@arnedebeer no problem, I'll edit the wiki to make sure it's obvious for anyone else.
