### ISSUE TITLE
BUG: 502 Bad Gateway nginx/1.18.0 after migrating to 4.x.x

### ISSUE THREAD

**Issue by andersidahl** [Bee-Mar/mmpm#160]
Followed the Migrating to MMPM‐4.x.x guide without issues, but now my raspberrypi.local:7890 is returning 502 Bad Gateway nginx/1.18.0.

MMPM was working fine before the upgrade on version 3.x.x.
Already tried a couple of reboots of the PI.

Any steps to troubleshoot this?

**Comment by Bee-Mar** [comment]
@andersidahl this seems like the nginx service is still running. The 4.x.x version of MMPM doesn't use NGINX.

Try running:

sudo systemctl disable --now nginx

**Comment by andersidahl** [comment]
Thanks, it did change the error but now it shows from Chrome: error: ERR_CONNECTION_REFUSED
Reboot done inbetween and also tried to reinstall.

**Comment by Bee-Mar** [comment]
Is the UI up and running? You should see it with "pm2 list"

If not, see the directions on how to make sure pm2 restarts the processes you've enabled after reboots in the wiki discussing installation of the UI

**Comment by andersidahl** [comment]
![image](https://github.com/Bee-Mar/mmpm/assets/10434858/9f362320-e14f-40cb-b045-16b9a80cdf80)
MM is working as usual.

MMPM does not respond in SSH either:
![image](https://github.com/Bee-Mar/mmpm/assets/10434858/e8132ff4-3bed-421d-bd68-ac4c563ec1be)

**Comment by Bee-Mar** [comment]
Do you have the latest version (4.0.4) of MMPM? That bug should be resolved

**Comment by Bee-Mar** [comment]
I'd recommend a clean reinstall. 

python3 -m pip install --force-reinstall --no-cache-dir --upgrade mmpm

**Comment by andersidahl** [comment]
That and running the 'mmpm ui install -y' seems to have solved it. The UI is now responding. I see it has gotten a face lift, so will dig into that and check everything else!

Much appreciated for the switft replies and the awsome work you are doing!

**Comment by Bee-Mar** [comment]
Thanks! If you encounter any bugs, don't hesitate to post them

**Comment by Bee-Mar** [comment]
Also, if this particular issue is solved, I'll close the issue

**Comment by andersidahl** [comment]
Yes!

To add for anyone else experiencing this, I also had install the new module with "mmpm install MMM-mmpm" and then add that to the MagicMirror config file.

**Comment by andersidahl** [comment]
WebUI doesn't start/work after rebooting the PI, but re-running the mmpm ui install -y solves that. Not sure if a bug or if I have to add it to launch somewhere?
