### ISSUE TITLE
QUESTION: default branch develop

### ISSUE THREAD

**Issue by KristjanESPERANTO** [Bee-Mar/mmpm#177]
Out of curiosity: Why did you change the default branch to develop?

**Comment by Bee-Mar** [comment]
It was in a move to use "GitHub Flow", which in essence I had been doing this whole time. The master branch was effectively redundant for me, since all releases were based on tags. In hindsight that should have been something I warned you about. Apologies if it caused any issues in your pipeline.

**Comment by KristjanESPERANTO** [comment]
Don't worry about it! :slightly_smiling_face: I stumbled across it by chance and only wanted to know the reasons behind it.

My knowledge of GitHub Flow is very limited. There's no way to see what someone is doing with GitHub Flow in the repository, is there?

**Comment by Bee-Mar** [comment]
Not that I'm aware of. It's primarily a methodology, vs something you can "enable"

**Comment by KristjanESPERANTO** [comment]
Okay, I need to take a closer look at this. Thanks for the information and mmpm of course! :smiley:

**Comment by Bee-Mar** [comment]
No problem! Also, I'm not completely sure I'm doing it correctly, but I'm giving it a shot lol. Also thank you for maintaining the Docker image as well!
