### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by xIExodusIx** [Bee-Mar/mmpm#191]
**Describe the Bug** Not all installed modules are displayed. E.g. "MMM-fuel" it is included in "mmpm" and I installed it manually, but "mmpm" does not show it as installed. 

Is this an issue with the CLI or GUI? GUI

Is this something that should be put in the Wiki? maybe

A clear and concise description of what the bug is.  I don't think that this is real Bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`

- output from `python3 --version`

- Web Browser (firefox, chrome, safari, chromium, etc)

**MMPM Environment Settings**

- output from `mmpm env`

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by xIExodusIx** [comment]
Unfortunately, this does not work as hoped. Pleas take a look at MMM-HH-LocalTransport there you can see that all Bus Signs has the same width, all other signs (subway (U-Bahn), S-Bahn, Reginonal Bahn (RB) or Ferrys) have the same width as the Bus signs. Is there something you can do? All Hamburg lokal transport signs without Busses can be found here: https://de.wikipedia.org/wiki/Hamburger_Verkehrsverbund#:~:text=Der%20Hamburger%20Verkehrsverbund%20ist%20ein%20Verkehrs-

**Comment by Bee-Mar** [comment]
@xIExodusIx It will be a few weeks until I can look into the issue due to work and personal travel

**Comment by Bee-Mar** [comment]
@xIExodusIx have you attempted to reinstall it using MMPM directly?

**Comment by xIExodusIx** [comment]
Yes I did, but that has not changed something.  It is installed, but MMPM says it is not.

**Comment by Bee-Mar** [comment]
@xIExodusIx which version of MMPM do you have installed?

**Comment by xIExodusIx** [comment]
How can I find out wich version of MMPM is installed?
I found this Infos. 
MMPM Info:
Stars: 6
Open Questions: 1
Build: 2023-03-05
Last update: 2024-09-29
Fork: 1

Database Info:
Database Version: 4.1.2
Last updated: 2024-11-04 14:12:49

**Comment by Bee-Mar** [comment]
@xIExodusIx running "mmpm version"

**Comment by xIExodusIx** [comment]
Hello, thanks for helping,

my MMPM version is 4.1.2

**Comment by Bee-Mar** [comment]
@xIExodusIx unfortunately, I'm unable to reproduce this. Are you willing to try with a clean setup?

**Comment by xIExodusIx** [comment]
Yes sure, no Problem. I'm using your guide to uninstall and reinstall MMPM.

**Comment by xIExodusIx** [comment]
I have reinstalled MMPM using your guide.  But it is the same as before, nothing changed. The module "MMM-Fuel" is installed but MMPM says it is not. Installing it using MMPM changes nothing. 

The second Bug??? I found is when clicking on the eye to toggle modules I get a popup that says: Cant call modules, is MagigMirror running and is MMM-MMPM installed? 

Yes MagicMirror is running and MMM-MMPM ist installed in the MagicMirror/modules folder.

**Comment by Bee-Mar** [comment]
@xIExodusIx with respect to the second item you mentioned, have you configured your MagicMirror configuration file to include MMM-MMPM and have you also configured your MMPM environment settings properly? Providing that information as requested in the issue template would be very helpful

**Comment by xIExodusIx** [comment]
Hello, the second Bug??? was my fault, I corrected that all, and now it works. 
But the module "MMM-Fuel" wont show up as installed. I dont know if it is the module itself or mmp that has the problem.

**Comment by xIExodusIx** [comment]
I deleted the modul "MMM-Fuel" and installed it again using mmpm, and now it works and is shown in mmpm-ui as installed.

Thanks for helping, this thread can be closed.
