### ISSUE TITLE
Sort modules by created/last updated date

### ISSUE THREAD

**Issue by AndyHazz** [Bee-Mar/mmpm#192]
It would be great to help discover new or actively developed modules if there was a way to sort the module list by recently updated or created.

**Comment by khassel** [comment]
I recommend [this overview](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) for searching (I don't see it as a competition to this project) ...

You can sort by “last commit” using the button in the right corner

**Comment by AndyHazz** [comment]
I wasn't aware of that, nice! Just the job for catching up on what's new.

**Comment by Bee-Mar** [comment]
@AndyHazz @khassel this can certainly be added and wouldn't take much effort

**Comment by AndyHazz** [comment]
Well, it'd for sure be a nice QoL improvement to mmpm, even if the info is available elsewhere ...
