### ISSUE TITLE
BUG: mmpm log invalid choice

### ISSUE THREAD

**Issue by b-reich** [Bee-Mar/mmpm#193]
**Describe the Bug**

Fancing error.
The cli tell me to use `mmpm log` which doesnt exists

**To Reproduce**
1. mmpx upgrade (which failes)

**Expected behavior**
Doenst tell me a command which is not defined

**Screenshots**
![grafik](https://github.com/user-attachments/assets/de7efc66-7136-40a8-8d28-b68fdcac057d)
**Operating System, Python3 Version, and Web Browser**\

- output from `cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- output from `python3 --version`
```
Python 3.11.2
```

- Web Browser (firefox, chrome, safari, chromium, etc)
firefox

**MMPM Environment Settings**

- output from `mmpm env`
```
{
  "MMPM_MAGICMIRROR_ROOT": "/home/pi/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://192.168.1.181:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "",
  "MMPM_IS_DOCKER_IMAGE": false,
  "MMPM_LOG_LEVEL": "INFO"
}
```

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`
there is no `mmpm log --zip`
![grafik](https://github.com/user-attachments/assets/0dafd377-8412-4420-bdad-1c422f07b074)

**MagicMirror Config**

- your MagicMirror `config.js`

- not MagicMirror related

**Comment by Bee-Mar** [comment]
@b-reich thanks for finding this. I'll get that updated this weekend, and in the meantime the command is "mmpm logs"

**Comment by Bee-Mar** [comment]
@b-reich I've merged the change into develop and will be tagging a release this weekend. Once that's done I'll close the issue

**Comment by b-reich** [comment]
Thanks for caring. It's only a small thing, but an annoying experience, especially for newcomers.

**Comment by Bee-Mar** [comment]
@b-reich this has been updated in the most recent release

**Comment by Bee-Mar** [comment]
@b-reich closing this issue for now
