### ISSUE TITLE
MagicMirror not stopping

### ISSUE THREAD

**Issue by istvanfedak** [Bee-Mar/mmpm#23]
Hi,

I just wanted to start off by saying that this is an incredible module!

I couldn't stop the MagicMirror and return to the desktop while using Control Center.

Steps to recreate:
1. Fresh Raspbian Buster image
2. Installed MagicMirror using git clone & npm install
3. Followed installation instruction guides for mmpm and installed the module
4. Went to http://raspberrypi:7890
5. Clicked on Start MagicMirror
5. Clicked on Stop MagicMirror under Control Center

**Comment by Bee-Mar** [comment]
@istvanfedak Thank you! Also, can you check the log files and see if any error messages were produced? They'll be under `~/.config/mmpm/log`

**Comment by istvanfedak** [comment]
Here are all the log files

[mmpm-cli-interface.log](https://github.com/Bee-Mar/mmpm/files/4607309/mmpm-cli-interface.log)
[mmpm-gunicorn-access.log](https://github.com/Bee-Mar/mmpm/files/4607310/mmpm-gunicorn-access.log)
[mmpm-gunicorn-error.log](https://github.com/Bee-Mar/mmpm/files/4607311/mmpm-gunicorn-error.log)

**Comment by Bee-Mar** [comment]
@istvanfedak just curious, are you managing MagicMirror with `pm2`?

**Comment by istvanfedak** [comment]
No I haven't installed pm2, but I plan to install it

**Comment by Bee-Mar** [comment]
@istvanfedak gotcha. I was wondering if that was the issue after looking at the log files, but it doesn't appear to be. I'll have to revisit the processes being checked to see if MagicMirror is running and update some of the util functions

**Comment by istvanfedak** [comment]
@Bee-Mar let me know if you need anything else

**Comment by Bee-Mar** [comment]
@istvanfedak I'll be adding a fix for shortly. It looks like I omitted killing the processes associated with electron as well. I'm also adding the logic for `pm2`, so it'll work seamlessly when you switch over

**Comment by istvanfedak** [comment]
Hi,

I'm still having the same issue. I downloaded the pm2 manager and I set it to auto start the magic mirror.

I uninstalled mmpm and I reinstalled it in ~/MagicMirror/modules/ and used the one line install command.

Now the MagicMirror wont even start. Here are my log files:

[mmpm-cli-interface.log](https://github.com/Bee-Mar/mmpm/files/4641639/mmpm-cli-interface.log)
[mmpm-gunicorn-access.log](https://github.com/Bee-Mar/mmpm/files/4641640/mmpm-gunicorn-access.log)
[mmpm-gunicorn-error.log](https://github.com/Bee-Mar/mmpm/files/4641641/mmpm-gunicorn-error.log)

**Comment by istvanfedak** [comment]
Just fixed the issue.

Steps to reproduce
- remove the old pm2 process: `pm2 delete mm`
- rename the `mm.sh` script to `MagicMirror.sh`
- start the process: `pm2 MagicMirror.sh`
- save the state: `pm2 save`

@Bee-Mar maybe you could add a note in the Wiki on how to setup pm2 so that its compatible with your module

**Comment by Bee-Mar** [comment]
@istvanfedak thanks! I'll definitely add something to the wiki about this. And I still haven't gotten to your pull request, but plan on within the week

**Comment by Bee-Mar** [comment]
@istvanfedak I'll see if I can find a way of retrieving the name of the `pm2` process that's running the magicmirror, or possibly have an environment variable as an option
