### ISSUE TITLE
Add rotate screen button to Control Center

### ISSUE THREAD

**Issue by istvanfedak** [Bee-Mar/mmpm#24]
Hi,

I was wondering if a rotate screen button could be added to Control Center. It would give visual feedback as to what rotation the screen has and prompt the user after 3 seconds if they want to reboot the pi (the delay would give the user enough time to click the button multiple times until they get the desired rotation, every time they click the button the timer would reset).

After reboot the changes should take into effect! 

These are the instructions on how to rotate the screen of the raspberry pi:
- https://www.raspberrypi.org/forums/viewtopic.php?t=120793

Here's a bash script I wrote that rotates the screen of the RaspberryPi:

```bash
#!/bin/bash
# run with sudo
# reboot raspberry pi for changes to take effect

CONFIG='/boot/config.txt'

# save default configuration file
if [ ! -f $CONFIG.save ]; then
    cp $CONFIG $CONFIG.save
fi

# get the rotation of the file
ROTATION=$(tail -1 $CONFIG)

# override current config file to remove changes
cp $CONFIG.save $CONFIG

# rotate clause
if [ $ROTATION == 'display_rotate=0' ]; then
    echo 'display_rotate=1' >> $CONFIG
    echo 'display_rotate=1'
elif [ $ROTATION == 'display_rotate=1' ]; then
    echo 'display_rotate=2' >> $CONFIG
    echo 'display_rotate=2'
elif [ $ROTATION == 'display_rotate=2' ]; then
    echo 'display_rotate=3' >> $CONFIG
    echo 'display_rotate=3'
elif [ $ROTATION == 'display_rotate=3' ]; then
    echo 'display_rotate=0' >> $CONFIG
    echo 'display_rotate=0'
else
    echo 'display_rotate=1' >> $CONFIG
    echo 'display_rotate=1'
fi
```

You could spawn a process that executes this script and the output of the script would give you the current rotation of the screen.

If you need any help adding this enhancement, I'd be happy to help!

**Comment by Bee-Mar** [comment]
@istvanfedak This would definitely make a solid addition. Adding in the execution of this should be quite straight forward, however, if you'd like to take a stab at the enhancement yourself feel free. It's quite nice seeing people contribute with pull requests

**Comment by istvanfedak** [comment]
@Bee-Mar sounds good, I’ll give it a shot

**Comment by istvanfedak** [comment]
@Bee-Mar I'm not too familiar with angular or electron but would these be the changes needed to add the button?

in https://github.com/Bee-Mar/mmpm/blob/enhancement/display-modules-performance/gui/src/app/components/magic-mirror-control-center/magic-mirror-control-center.component.ts#L34

add button in tile:
{
    icon: "refresh",
    tooltip: "Rotate MagicMirror",
    cols: 1,
    rows: 1,
    url: "/rotate-magicmirror"
}

in https://github.com/Bee-Mar/mmpm/blob/develop/mmpm/api.py#L324
add:

```
@app.route(__api__('rotate-raspberrypi'), methods=[GET])
def rotate_raspberrypi() -> str:
    '''
    Rotate the RaspberryPi
    Parameters:
        None
    Returns:
        rotation (string): If the command fails, None is returned. 
                           If success, the return will reach the interface
    '''

    log.logger.info('Rotating RaspberryPi')
    utils.stop_magicmirror()
    return_code, rotation, _ = utils.run_cmd(['sudo', 'bash', 'rotate.sh'])
    # if success, it'll return a string defining the rotation
    
    return json.dumps(rotation) if bool(not return_code) else None
```

I still haven't figured out how to notify the user and tie in the response of the api call to the pop up message prompting the user to restart the mirror

Also where do you want me to store the rotate script?

**Comment by Bee-Mar** [comment]
@istvanfedak Would it be easier to set an environment variable for the user, and read that value rather than using an additional file? Something like `DISPLAY_ROTATION`? You could convert the shell script to a function within the `mmpm.utils`, and then read the environment variable in with `os.environ`.

**Comment by istvanfedak** [comment]
@Bee-Mar Yea I think a drop down menu would make it clear and not confuse the user. Sounds good I can convert the script to python. I can do a PR for the `mmpm.utils` function. I've never worked with angular, so if you could do the front end, it would be great! I plan to learn it some day

**Comment by istvanfedak** [comment]
I just did a pr adding `mmpm.utils.rotate_display` the function requires `os.environ['DISPLAY_ROTATION']` to one of the following values: `0, 1, 2 or 3`.

**Comment by Bee-Mar** [comment]
@istvanfedak I'll take a look at this shortly

**Comment by istvanfedak** [comment]
@Bee-Mar Awesome! I did notice that the function need root privilages in order to read and write to the `/boot/` directory. You could get around that with a script by spawning a child process that executes the script with sudo (as you do with shutdown and restart)

**Comment by Bee-Mar** [comment]
@istvanfedak I brought in your pull request to the develop branch yesterday. I'm doing a total rework of the cli options, and once that's all done and merged up into develop, i'll get your code fully integrated into the package

**Comment by istvanfedak** [comment]
Awesome! Thanks
