### ISSUE TITLE
is there a script/tool that helps me get back to installed system

### ISSUE THREAD

**Issue by sdetweil** [Bee-Mar/mmpm#26]
I didn't bookmark the page.. how do I get back there?

**Comment by Bee-Mar** [comment]
@sdetweil I can add a command line option to print that information out, but it'll be at the raspberry pi's IP, and port 7890

ie, 192.168.0.100:7890

**Comment by sdetweil** [comment]
i always install over ssh, so the web page probably won't open, or would open behind MM)
so I would have to launch from the ssh terminal window or the file window over the remote volume..
I have 8 MM's running on various platforms. 1 production, 1 near production (hardly ever taken down), and others on mac, pi0, odroid, jetson nano,  etc
just trying to find an easy way back.

**Comment by Bee-Mar** [comment]
it should be visible on all the devices you have mmpm installed on, unless you've blocked the ports

**Comment by Bee-Mar** [comment]
I'm also labelling this as an enhancement to add a command line option for displaying the GUI address

**Comment by Bee-Mar** [comment]
@sdetweil The feature I mentioned above has been added to the develop branch, as well as an option to list the enabled/disabled modules.
