### ISSUE TITLE
i have modules installed not in 3rd party list, but also not shown

### ISSUE THREAD

**Issue by sdetweil** [Bee-Mar/mmpm#27]
i have modules installed, but are not shown on MMPM screen..
the package.json file could take you to the github url.. owner...
(and git remote -v too)

at least show them.. 

also i have some disabled..   it would be great to know this. 
I had to add this feature to my upgrade script.. also have one module listed 11 times with different configs..

**Comment by Bee-Mar** [comment]
You can add those to the external modules, via `mmpm -X` or the equivalent `mmpm --add-ext-module-src` and manually enter the information there. I don't have any plans to add scraping directories for information.

**Comment by Bee-Mar** [comment]
@sdetweil Adding an option to display the enabled modules is something that's doable, and would be useful. I'll tag this as a enhancement for this reason.

**Comment by sdetweil** [comment]
sorry, one more question

mmpm -X 
Register external module source

what does that mean?  'source'  

is that source files (.js...) (as in located in the modules folder,  some local git repo, or folder
or the github/??? url location? 
and it github, why are u asking for title?

there is no help for the -X command

**Comment by Bee-Mar** [comment]
If you execute `mmpm -X` it will prompt you for the required information (the module title, repo url, author, and description). I should add more details to the help section for that command, but 'source' was probably not the best name, and should just be left as `--add-ext-module`

**Comment by sdetweil** [comment]
is there a way I can provide all the data, no prompts?  I will write a script to do the data mining to add the entries, too many systems to do manually

**Comment by Bee-Mar** [comment]
if you want to do it manually, you can add a file in `~/.config/mmpm` named `mmpm-external-sources.json`, and populate the json yourself.


The format would be
```json
{
  "External Module Sources": [
    {
      "Title": "<the module title>",
      "Repository": "<repo url>",
      "Author": "<author>",
      "Description": "<description>"
    }
  ]
}
```

If any of those other modules are using different branches, you can also bake the branch name into the "Repository" by using something like 

```json
{
  "External Module Sources": [
    {
      "Title": "MMPM",
      "Repository": "https://github.com/Bee-Mar/mmpm.git -b develop",
      "Author": "Bee-Mar",
      "Description": "Some description here"
    }
  ]
}
```

**Comment by sdetweil** [comment]
so there is one block inside the array for each added module?

**Comment by Bee-Mar** [comment]
There is one single array under "External Module Sources", with each object appended to that array. I updated the example above so it's more clear

**Comment by sdetweil** [comment]
ok, the file is not there by default.

**Comment by Bee-Mar** [comment]
@sdetweil correct, However it would be created the first time you were to register an external module. If you register new ones, it'll just get appended to. Once registered the modules would be displayed under the category of "External Module Sources" if you execute something like `mmpm -c` or `mmpm -a`, or perform a search for all of them using `mmpm -s "External Module Sources"`

**Comment by Bee-Mar** [comment]
@sdetweil if the modules are in private repos, or you're using ssh keys with your github account, they will still work

**Comment by sdetweil** [comment]
I created an empty file,  shows an empty list
I added an entry, 
refresh doesn't show it , click on external doesn't show it

**Comment by Bee-Mar** [comment]
you did not place the keys in the proper order from the example I provided

**Comment by sdetweil** [comment]
keys are keys.. non positional.. , the whole VALUE of keys

**Comment by sdetweil** [comment]
i made it this 
```
{
  "External Module Sources": [
  	{
  		"Title": "MyCovid19",
		"Repository": "https://github.com/sdetweil/MyCovid19",
      	"Author": "Sam" ,
      	"Description": "Sams module for virus tracking"
  	},
  	    {
      "Title": "MMPM",
      "Repository": "https://github.com/Bee-Mar/mmpm.git -b develop",
      "Author": "Bee-Mar",
      "Description": "Some description here"
    }
  ]
}
```

nothing shows

**Comment by Bee-Mar** [comment]
@sdetweil This was not designed to be done in way that was set up for scripting, so the design is what it currently is. The webpage and cli expect things to be in a certain order.

**Comment by Bee-Mar** [comment]
Is the file named properly? The json you provided above displays in the webpage for me just fine.

**Comment by sdetweil** [comment]
ok, missing 's' on the end of sources, but only get one entry 
![Screenshot at 2020-05-14 12-03-54](https://user-images.githubusercontent.com/1498142/81963727-1c190680-95db-11ea-9eb6-149f21c71c1d.png)
```
{
  "External Module Sources": [
  	{
  		"Title": "MyCovid19",
		"Repository": "https://github.com/sdetweil/MyCovid19",
      	"Author": "Sam" ,
      	"Description": "Sams module for virus tracking"
  	},
  	{
      "Title": "MMPM",
      "Repository": "https://github.com/Bee-Mar/mmpm.git -b develop",
      "Author": "Bee-Mar",
      "Description": "Some description here"
    }
  ]
}
```

**Comment by Bee-Mar** [comment]
Both the mmpm and mycovid19 modules display for me after copy and pasting exactly what you have on the screen into the `mmpm-external-module-sources.json`, saving it, and refreshing the page

**Comment by sdetweil** [comment]
never mind user error.. somehow I renamed the file and ended up with the old one (with the content)
and the new one (with only one entry)

works now

**Comment by Bee-Mar** [comment]
gotcha, glad it was resolved
