### ISSUE TITLE
Not showing any local package installed

### ISSUE THREAD

**Issue by julianCast** [Bee-Mar/mmpm#30]
Before installing mmpm I had some modules installed but I don´t see them in the local packages section.

For information: As I have magicMirrosOS, my modules are found on `~/magicmirror/mounts/modules`, and config `~/magicmirror/mounts/config`

Your config is hardcoded for regular magic mirror installation
https://github.com/Bee-Mar/mmpm/blob/298ee9d9ab3d75c480e8c17cee5982f1764cf4d0/mmpm/core.py#L691

**Comment by julianCast** [comment]
Your  utils files set the magic mirror root path like this, but for us with magicMirrorOS would be like this:

![Screenshot (47)](https://user-images.githubusercontent.com/559677/83358380-5a504d00-a373-11ea-8e30-f7b3a61ed16f.png)

**Comment by Bee-Mar** [comment]
@julianCast This is an environment variable you can set in your bashrc. The default value is set to `~/MagicMirror`

**Comment by Bee-Mar** [comment]
@julianCast Once you set the env variable and test it out, I'll close this issue

**Comment by julianCast** [comment]
Great! I'll set it tonight and  I'll let you know, thanks

**Comment by julianCast** [comment]
Ok, I did exactly what you said and it's working perfect now!
It's actually a MUST HAVE, good job with the config terminal 
Thank you so much.

**Comment by Bee-Mar** [comment]
You're welcome, and thank you! and keep an eye out for the next major update for `mmpm`, there will be quite a few new additions to the CLI and modifications to the GUI

**Comment by Bee-Mar** [comment]
@julianCast have you read the wiki pages that detail how to set this up?

https://github.com/Bee-Mar/mmpm#tldr-whats-the-installationremoval-process

https://github.com/Bee-Mar/mmpm/wiki/MMPM-Environment-Variables

https://github.com/Bee-Mar/mmpm/wiki/Installed-Modules-Are-Not-In-Local-Packages!

**Comment by julianCast** [comment]
So, after updating to the v2 Im getting again the 404 no modules installed.

![Screenshot (57)](https://user-images.githubusercontent.com/559677/88566202-fcb84400-d035-11ea-9d79-f64a795eb6f0.png)

**Comment by Bee-Mar** [comment]
that is the web interface of the old version. How did you install version 2.01?

**Comment by julianCast** [comment]
```
pip3 install --upgrade --no-cache-dir mmpm

mmpm install --gui
```

**Comment by julianCast** [comment]
Ok, reboot did apply the changes, but same error.
![Screenshot (58)](https://user-images.githubusercontent.com/559677/88566640-997ae180-d036-11ea-8a29-7c959c76d76e.png)

**Comment by Bee-Mar** [comment]
what displays when you run `mmpm -v` and `mmpm -h`

**Comment by Bee-Mar** [comment]
also, have you read the wiki page on how to configure the environment variables? the setup for those has changed completely.

https://github.com/Bee-Mar/mmpm/issues/30#issuecomment-664497689

**Comment by julianCast** [comment]
I  think it may be that my magic mirror is an OS, so docker compose.. so your MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE must be used. My mistake Im sure

**Comment by Bee-Mar** [comment]
make sure you edit the file using `mmpm open --env`. These are not shell environment variables anymore.

**Comment by julianCast** [comment]
Wow, you are right, big changes. Now is actually easier, once I edit the file Ill put here the data. Thanks!

**Comment by Bee-Mar** [comment]
sounds good

**Comment by julianCast** [comment]
So, after change the config file, mmpm only find 2 modules.

My config
> {
>   "MMPM_MAGICMIRROR_ROOT": "/home/pi/magicmirror/mounts",                                                                                                                                                                                                           
>    "MMPM_MAGICMIRROR_URI": "http://magicmirroros:8080/",
>   "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "",
>   "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": "/home/pi/magicmirror/run/docker-compose.yml",
>   "MMPM_IS_DOCKER_IMAGE": false
> }

GUI Only find 2modules

![Screenshot (61)](https://user-images.githubusercontent.com/559677/88569507-d21cba00-d03a-11ea-9990-59e06faecd53.png)


My modules content, has more than 2 modules:

![Screenshot (63)](https://user-images.githubusercontent.com/559677/88569776-39d30500-d03b-11ea-993f-926791f39a46.png)

**Comment by julianCast** [comment]
Ok , it is because of this https://github.com/Bee-Mar/mmpm/wiki/Help!-Installed-Modules-Are-Not-In-Local-Packages!

**Comment by Bee-Mar** [comment]
@julianCast once you've done the above, please let me know if everything displays properly

**Comment by julianCast** [comment]
After manual uninstalling the modules and installing using your mmpm noware shown in the local package. 👍 

The only thing missing is the "Actives modules" panel, I've done everything from https://github.com/Bee-Mar/mmpm/wiki/Status,-Hide,-Show-MagicMirror-Modules. I have magicmirrorOS (docker based), I've try setting `/home/pi/magicmirror/run/docker-compose.yml` as a URL or "" but no luck..

**Comment by Bee-Mar** [comment]
@julianCast please check that the `mmpm` module is actually installed in your modules directory. 

From the config you posted above, make sure `"/home/pi/magicmirror/mounts/modules/mmpm` exists after installing the MMPM MagicMirror module. Also, make sure you've added `{ module: "mmpm" }` to your `config.js`

**Comment by julianCast** [comment]
Yes, the mpmm folder is there
![Screenshot (65)](https://user-images.githubusercontent.com/559677/88578117-588bc880-d048-11ea-81e6-5681f3928052.png)
Yes, the module is in the config file
![Screenshot (67)](https://user-images.githubusercontent.com/559677/88578313-a1438180-d048-11ea-9d99-04871e66cc0d.png)

I have refresh everything but no working the active modules panel

**Comment by Bee-Mar** [comment]
please download the log files and attach them

**Comment by Bee-Mar** [comment]
@julianCast have you opened magicmirror in your browser after restarting magicmirror, then refreshed the MMPM control center?

**Comment by julianCast** [comment]
> @julianCast have you opened magicmirror in your browser after restarting magicmirror, then refreshed the MMPM control center?

Yep, I refreshed it and then the UI, and also did the command terminal. Even a full raspberry restart. 
I'll attach the logs asap

**Comment by Bee-Mar** [comment]
The address you have here:

```sh
 "MMPM_MAGICMIRROR_URI": "http://magicmirroros:8080/"
```

Is `magicmirroros` the address that's listed in your docker-compose file? 

Try replacing the `MMPM_MAGICMIRROR_URI` with the network ip address of the device you have MMPM installed on.

**Comment by Bee-Mar** [comment]
@julianCast also, i'm going to close this issue, since the primary reason for it being opened has been resolved. Feel free to ask anymore questions in this thread.

**Comment by julianCast** [comment]
> please download the log files and attach them

[mmpm-logs-2020-6-1.zip](https://github.com/Bee-Mar/mmpm/files/4984129/mmpm-logs-2020-6-1.zip)


> The address you have here:
> 
> ```shell
>  "MMPM_MAGICMIRROR_URI": "http://magicmirroros:8080/"
> ```
> 
> Is `magicmirroros` the address that's listed in your docker-compose file?
> 
> Try replacing the `MMPM_MAGICMIRROR_URI` with the network ip address of the device you have MMPM installed on. Meaning, replace `magicmirroros` with whatever IP address you're using to access the MMPM GUI.

I can access via browser with either "http://magicmirroros:8080/" or "http://192.168.1.118:8080/" but with none of them I could enable your feature (MMPM_MAGICMIRROR_URI).
"
![Screenshot (70)](https://user-images.githubusercontent.com/559677/88585868-ecaf5d00-d053-11ea-8b0d-d3bd949e994d.png)

**Comment by julianCast** [comment]
This log is interesting, after doing `mmpm mm-ctl --status` I get this:


```
2020-07-27 20:59:08,106.106 INFO core - display_magicmirror_modules_status: attempting to connect to '/mmpm' namespace within MagicMirror websocket
attempting to connect to '/mmpm' namespace within MagicMirror websocket
2020-07-27 20:59:08,110.110 INFO client - _connect_polling: Attempting polling connection to http://192.168.1.118:8080/socket.io/?transport=polling&EIO=3
Attempting polling connection to http://192.168.1.118:8080/socket.io/?transport=polling&EIO=3
2020-07-27 20:59:08,147.147 INFO client - _connect_polling: Polling connection accepted with {'sid': 'Jj2MGQreH3U_4sl9AAAr', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Polling connection accepted with {'sid': 'Jj2MGQreH3U_4sl9AAAr', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
2020-07-27 20:59:08,148.148 INFO client - _handle_eio_connect: Engine.IO connection established
Engine.IO connection established
2020-07-27 20:59:08,150.150 INFO client - _receive_packet: Received packet MESSAGE data 0
Received packet MESSAGE data 0
2020-07-27 20:59:08,153.153 INFO client - _handle_connect: Namespace / is connected
Namespace / is connected
2020-07-27 20:59:08,154.154 INFO client - _connect_websocket: Attempting WebSocket upgrade to ws://192.168.1.118:8080/socket.io/?transport=websocket&EIO=3
2020-07-27 20:59:08,157.157 INFO client - _send_packet: Sending packet MESSAGE data 0/mmpm
Attempting WebSocket upgrade to ws://192.168.1.118:8080/socket.io/?transport=websocket&EIO=3
Sending packet MESSAGE data 0/mmpm
2020-07-27 20:59:08,176.176 INFO client - _connect_websocket: WebSocket upgrade was successful
WebSocket upgrade was successful
2020-07-27 20:59:08,179.179 INFO client - _send_packet: Sending packet PING data None
Sending packet PING data None
2020-07-27 20:59:08,193.193 INFO client - _receive_packet: Received packet MESSAGE data 4/mmpm,"Invalid namespace"
Received packet MESSAGE data 4/mmpm,"Invalid namespace"
2020-07-27 20:59:08,203.203 INFO client - _handle_error: Connection to namespace /mmpm was rejected
2020-07-27 20:59:08,204.204 INFO client - _receive_packet: Received packet PONG data None
Connection to namespace /mmpm was rejected
Received packet PONG data None
2020-07-27 20:59:13,113.113 WARNING utils - background_timer_thread: Reached fith second of 10 second timeout for connecting to MagicMirror websocket
Reached fith second of 10 second timeout for connecting to MagicMirror websocket
```

**Comment by Bee-Mar** [comment]
@julianCast i'm wondering if this has something to do with the docker image you're using. Can you paste your docker-compose.yml?

**Comment by julianCast** [comment]
docker compose (/home/pi/magicmirror/run)
```
version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
      TZ: Europe/Berlin
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
    command:
      - npm
      - run
      - start
```


[config.zip](https://github.com/Bee-Mar/mmpm/files/4984223/config.zip)

**Comment by Bee-Mar** [comment]
using your config, and docker-compose file everything shows up on the active modules for me. Can you try doing a `docker-compose down`, then `docker-compose up -d`? I'm not sure if it's been getting restarted with `docker-compose restart instead`.

From the message `Received packet MESSAGE data 4/mmpm,"Invalid namespace"`, it seems like the MagicMirror isn't picking up on that module. I was able to establish the connection after doing `docker-compose down` followed by `docker-compose up -d`

**Comment by Bee-Mar** [comment]
something else I noticed is that from your config, the calendar url isn't defined, and it caused a runtime error in MagicMirror. After I removed the calendar module, everything worked fine.

**Comment by julianCast** [comment]
> something else I noticed is that from your config, the calendar url isn't defined, and it caused a runtime error in MagicMirror. After I removed the calendar module, everything worked fine.

Yes, I removed to calendar url before attaching it here  because it's a private url.

**Comment by Bee-Mar** [comment]
@julianCast have you tried performing the `docker-compose down; docker-compose up -d` steps? Also, when you start magicmirror, open it in your web browser, and press F12 on your keyboard to see the developer console. See if there are any run-time errors MagicMirror is encountering.

**Comment by julianCast** [comment]
> @julianCast have you tried performing the `docker-compose down; docker-compose up -d` steps? Also, when you start magicmirror, open it in your web browser, and press F12 on your keyboard to see the developer console. See if there are any run-time errors MagicMirror is encountering.

I did both commands in my path, it did remove and  recreate de mm, but no difference.
The dev console shows no error, only a  404 module no longer installed so I remove it from the config.

How weird, that is the only thing I cant achieve with your mmpm.

**Comment by Bee-Mar** [comment]
can you try MMPM with a default config file and see if that works? It'll help eliminate the possibility of any of your installed modules causing issues. If that works, slowly add your configuration back in, piece by piece.
