### ISSUE TITLE
Feature request: Add Tab for Custom.css editing

### ISSUE THREAD

**Issue by tkg61** [Bee-Mar/mmpm#31]
Any chance it would be easy to add the custom.css file as a tab for editing just as the config is? 

Thanks!

**Comment by Bee-Mar** [comment]
@tkg61 are you referring to custom CSS for the web interface?

**Comment by tkg61** [comment]
Sorry I mean MM module custom css file 

Magicmirror/config/config.css

**Comment by Bee-Mar** [comment]
ah, gotcha. Well, that it's almost certainly doable, but it'll be probably at least a couple weeks before that's implemented. I'm in the middle of a total rework of the CLI and web interface, but this definitely seems quite doable.

**Comment by tkg61** [comment]
No worries! Looking forward to the rework!

**Comment by Bee-Mar** [comment]
Thanks! It'll definitely be a lot cleaner and intuitive

**Comment by Bee-Mar** [comment]
@tkg61 this will be definitely be added in the upcoming version, which will hopefully be completely done in the next week or two

**Comment by Bee-Mar** [comment]
@tkg61 I'm going to go ahead and close this issue. I've implemented in the branch I've been working on that contains the massive changes
