### ISSUE TITLE
Manual dependency installation instructions outputs error.

### ISSUE THREAD

**Issue by stopspazzing** [Bee-Mar/mmpm#33]
On Fresh install on Raspberry Pi Zero W with Raspberry Pi OS (Full)

`curl -sL https://deb.nodesource.com/setup_10.x \| sudo -E bash -`

```
## Installing the NodeSource Node.js 10.x repo...


## You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js 4 and later.
```

Obviously I can get around this with source compiling or as suggested, binary tarballs, but wanted to make this known.

**Comment by Bee-Mar** [comment]
is this occurring during the installation of MMPM?

**Comment by stopspazzing** [comment]
Thankfully doesnt happen with your provided one liner. It only happens when someone attempts to do a manual install of the dependancies first, which I did. Seems it's listed on [https://docs.magicmirror.builders/getting-started/installation.html#manual-installation](https://docs.magicmirror.builders/getting-started/installation.html#manual-installation) also so doesn't seem like an issue with your manual instructions as they were copied from MM to begin with. Just odd no one noticed this before... guess this can be closed and I'll open a new issue in MM. Sorry to bother you!

**Comment by Bee-Mar** [comment]
@stopspazzing not a problem! It's definitely good to know for reference, and this is something MagicMirror should be made aware of
