### ISSUE TITLE
When using multiple pages, only fixed modules are shown as active

### ISSUE THREAD

**Issue by requiemmg** [Bee-Mar/mmpm#35]
See the title. Only fixed modules are shown as active in the MMPM GUI Control Center with MMM-pages.

![grafik](https://user-images.githubusercontent.com/11157808/88456162-c2a34280-ce7b-11ea-9086-462b949c9baa.png)

**Comment by Bee-Mar** [comment]
can you provide your `config.js` so I can try to replicate this?

**Comment by requiemmg** [comment]
Mailed it to your protonmail-address as it is a bit lenghty.
Basically, top reproduce: set up MMM-Pages with 2 or more pages, assign modules, assign fixed modules.

**Comment by Bee-Mar** [comment]
@requiemmg just saw it come through. Could you resend it as an attachment? Copying and pasting it into the body of the email distorted the placement of lines when trying to place it into a file.

**Comment by requiemmg** [comment]
done

**Comment by Bee-Mar** [comment]
Cool, I’ll take a look at it tomorrow when I have a chance. It’ll probably be at least a week before I push a new version to contain a bug fix since I released the new version yesterday and want to see if there are other fixes I can include.

**Comment by Bee-Mar** [comment]
@requiemmg using your config and a clean install of MagicMirror, all the modules display for me in the Control Center. Would it possible for you to try backing up your config file, reinstalling your modules, then trying it again?

**Comment by requiemmg** [comment]
Well, I actually have a clean install of MM, as I was having troubles with freezing Raspis in the past.
Now, I've set up my 2 R3B+, both are running smooth and without freeizing issues. Also, mmpm 1.x and 2.x are running fine, just the issue mentioned. Beside MagicMirror, only LightsOut (www.green-it-software.com) client is running on the machines. Fresh Raspian Buster images.
I used @samdetweil's installation script for initial setup.

**Comment by Bee-Mar** [comment]
you should definitely remove the installation of mmpm 1.x, that'll cause conflicts with execution

**Comment by requiemmg** [comment]
"make uninstall" was actually the first thing I did before installing MMPM2

**Comment by Bee-Mar** [comment]
still looking into this

**Comment by Bee-Mar** [comment]
are there possibly any run-time issues with MagicMirror? If you open your browser to the MagicMirror URL and open the developer console in your browser by pressing F12 (it most likely is F12 if you have firefox or chrome), do any errors display?

**Comment by requiemmg** [comment]
I can't see such errors. I've installed MMM-Logging, made a complete uninstall of MMPM again and installed MMPM from scratch, before that I cleared the logs with pm2.
I will check and send you relevant logs if I see something. (Or if the problem persists, maybe you see something that I am missing)

**Comment by Bee-Mar** [comment]
sounds good, keep me updated

**Comment by Bee-Mar** [comment]
@requiemmg any update?

**Comment by requiemmg** [comment]
No, I have a new problem with MMPM on my main/test mirror (which is funny because the other mirror is actually is a CLONE) - i get NGINX Bad Gateway error. Uninstalled, uninstalled virtualemnv, reinstalled - works. As soon as I reboot - nginx bad gateway. ALready wrote in the forums, no answers to that.

**Comment by Bee-Mar** [comment]
so, a bad gateway would usually be due to a port being in use already, or for some reason the `gunicorn` process isn't starting. If you could run `sudo systemctl status mmpm mmpm-webssh` and `journalctl -xe`, then post the output I should be able to spot what's going on.

**Comment by requiemmg** [comment]
Of course:

pi@SmartMirror2:~ $ sudo systemctl status mmpm mmpm-webssh
● mmpm.service - MMPM Gunicorn daemon
   Loaded: loaded (/etc/systemd/system/mmpm.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-08-02 18:14:08 CEST; 1h 32min ago
 Main PID: 407 (gunicorn)
   Status: "Gunicorn arbiter booted"
    Tasks: 2 (limit: 1604)
   Memory: 38.9M
   CGroup: /system.slice/mmpm.service
           ├─ 407 /usr/bin/python3 /home/pi/.local/bin/gunicorn --reload --worker-class eventlet --bind localhost:7891 m
           └─3098 /usr/bin/python3 /home/pi/.local/bin/gunicorn --reload --worker-class eventlet --bind localhost:7891 m

Aug 02 18:14:08 SmartMirror2 gunicorn[407]: [2020-08-02 18:14:08 +0200] [407] [INFO] Listening at: http://127.0.0.1:7891
Aug 02 18:14:08 SmartMirror2 gunicorn[407]: [2020-08-02 18:14:08 +0200] [407] [INFO] Using worker: eventlet
Aug 02 18:14:08 SmartMirror2 systemd[1]: Started MMPM Gunicorn daemon.
Aug 02 18:14:08 SmartMirror2 gunicorn[407]: [2020-08-02 18:14:08 +0200] [980] [INFO] Booting worker with pid: 980
Aug 02 18:15:03 SmartMirror2 gunicorn[407]: [2020-08-02 18:15:03 +0200] [407] [CRITICAL] WORKER TIMEOUT (pid:980)
Aug 02 18:15:03 SmartMirror2 gunicorn[407]: [2020-08-02 18:15:03 +0200] [980] [INFO] Worker exiting (pid: 980)
Aug 02 18:15:03 SmartMirror2 gunicorn[407]: [2020-08-02 18:15:03 +0200] [1035] [INFO] Booting worker with pid: 1035
Aug 02 19:01:14 SmartMirror2 gunicorn[407]: [2020-08-02 19:00:59 +0200] [407] [CRITICAL] WORKER TIMEOUT (pid:1035)
Aug 02 19:01:14 SmartMirror2 gunicorn[407]: [2020-08-02 19:01:14 +0200] [1035] [INFO] Worker exiting (pid: 1035)
Aug 02 19:01:25 SmartMirror2 gunicorn[407]: [2020-08-02 19:01:25 +0200] [3098] [INFO] Booting worker with pid: 3098

● mmpm-webssh.service - MMPM WebSSH daemon
   Loaded: loaded (/etc/systemd/system/mmpm-webssh.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-08-02 18:13:41 CEST; 1h 33min ago
 Main PID: 402 (wssh)
    Tasks: 1 (limit: 1604)
   Memory: 8.4M
   CGroup: /system.slice/mmpm-webssh.service
           └─402 /usr/bin/python3 /home/pi/.local/bin/wssh --address=localhost --port=7893

Aug 02 18:13:41 SmartMirror2 systemd[1]: Started MMPM WebSSH daemon.
Aug 02 18:14:03 SmartMirror2 wssh[402]: [I 200802 18:14:03 settings:125] WarningPolicy
Aug 02 18:14:03 SmartMirror2 wssh[402]: [I 200802 18:14:03 main:39] Listening on localhost:7893 (http)
Aug 02 18:18:52 SmartMirror2 systemd[1]: /etc/systemd/system/mmpm-webssh.service:4: Failed to parse unsigned value, igno
lines 1-35/35 (END)


and


pi@SmartMirror2:~ $ journalctl -xe
-- The job identifier is 875.
Aug 02 19:46:50 SmartMirror2 sudo[4583]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/systemctl status
Aug 02 19:46:50 SmartMirror2 sudo[4583]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Aug 02 19:47:02 SmartMirror2 xrdp[698]: (698)(1996077168)[INFO ] Socket 12: AF_INET6 connection received from ::ffff:127
Aug 02 19:47:02 SmartMirror2 xrdp[698]: (698)(1996077168)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:127.0.0.1 port 3389)
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[ERROR] Cannot read private key file /etc/xrdp/key.pem: Permi
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[DEBUG] TLSv1.3 enabled
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[DEBUG] TLSv1.2 enabled
Aug 02 19:47:02 SmartMirror2 xrdp[4602]: (4602)(1996077168)[DEBUG] Closed socket 12 (AF_INET6 ::ffff:127.0.0.1 port 3389
Aug 02 19:47:50 SmartMirror2 sshd[4555]: Received disconnect from 192.168.0.100 port 65322:11: disconnected by user
Aug 02 19:47:50 SmartMirror2 sshd[4555]: Disconnected from user pi 192.168.0.100 port 65322
Aug 02 19:47:50 SmartMirror2 sshd[4545]: pam_unix(sshd:session): session closed for user pi
Aug 02 19:47:50 SmartMirror2 sudo[4583]: pam_unix(sudo:session): session closed for user root
Aug 02 19:47:50 SmartMirror2 systemd-logind[308]: Session c4 logged out. Waiting for processes to exit.
Aug 02 19:47:50 SmartMirror2 systemd[1]: session-c4.scope: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit session-c4.scope has successfully entered the 'dead' state.
Aug 02 19:47:50 SmartMirror2 systemd-logind[308]: Removed session c4.
-- Subject: Session c4 has been terminated
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID c4 has been terminated.
Aug 02 19:48:00 SmartMirror2 sshd[4617]: Accepted password for pi from 192.168.0.100 port 65457 ssh2
Aug 02 19:48:00 SmartMirror2 sshd[4617]: pam_unix(sshd:session): session opened for user pi by (uid=0)
Aug 02 19:48:01 SmartMirror2 systemd[1]: Started Session c5 of user pi.
-- Subject: A start job for unit session-c5.scope has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit session-c5.scope has finished successfully.
--
-- The job identifier is 940.
Aug 02 19:48:01 SmartMirror2 systemd-logind[308]: New session c5 of user pi.
-- Subject: A new session c5 has been created for user pi
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID c5 has been created for the user pi.
--
-- The leading process of the session is 4617.
lines 2549-2597/2597 (END)

**Comment by Bee-Mar** [comment]
okay, so i think I know what's going on. You say you have a virtualenv right? I see that the systemd file is pointing to your gunicorn executable in `/home/pi/.local/bin`, which is not inside a virtualenv. If you are operating MMPM within a virtualenv, try installing the GUI by running `mmpm install --gui`, then see if that is pointing to the same location.

**Comment by Bee-Mar** [comment]
also, i'm not sure why, but there's an unsigned value on line 4 of the systemd file for webssh apparently based on that message. That's pretty odd

**Comment by Bee-Mar** [comment]
@requiemmg do you happen to have discord?

**Comment by requiemmg** [comment]
Hi,

I have my own Teamspeak server and I might setup discord, but not tonight. Something is FUBAR on my installation on this mirror and I will restore from a former backup when MMPM2 GUI was running fine.
For virtualenv: I uninstalled it today in a new try to get everything up and runinng. Did so because your installation wiki manpages have changed, and I reinstalled without virtualenv.

As I said - I will use a backup from some days ago to solve the problem for today.

**Comment by Bee-Mar** [comment]
@requiemmg sounds good, and yeah, I'm in the process of separating things out so the instructions are more digestable. I'm going to add a separate tab with instructions for a virtualenv installation.

**Comment by requiemmg** [comment]
Update: no update. After restoring my second MM, both GUI frontends are working again. Both only show the fixed modules as active, the per-page-modules defined in MMM-Pages are not being shown as active.
No errors in my logs.

**Comment by Bee-Mar** [comment]
@requiemmg This is definitely baffling. Do you happen to have any kind of router setup or firewall settings that are atypical?

**Comment by requiemmg** [comment]
No, not at all.
The bug does not annoy me as everything else is working as intended, but it's definetely strange.

**Comment by Bee-Mar** [comment]
@requiemmg well, at least that's good to know, but it's still really odd
