### ISSUE TITLE
MMPM not detecting Magic Mirror upgrade

### ISSUE THREAD

**Issue by tkg61** [Bee-Mar/mmpm#36]
When running “mmpm update” it reports no upgrade needed for my 2.11 install when i am getting an alert that 2.12 is available. 

<img width="1366" alt="MagicMirror Package Manager" src="https://user-images.githubusercontent.com/3945114/88488469-4d0ea380-cf5b-11ea-9a40-01d6b577ffcd.png">

Any suggestions?

**Comment by tkg61** [comment]
<img width="1366" alt="MagicMirror Package Manager" src="https://user-images.githubusercontent.com/3945114/88488585-2604a180-cf5c-11ea-8d42-65a94a2a1c33.png">

Here is a screenshot of the logs

**Comment by Bee-Mar** [comment]
is `MMPM_MAGICMIRROR_ROOT` set properly in your `mmpm env`?

**Comment by Bee-Mar** [comment]
also, out of curiosity, what application is checking for updates to MagicMirror besides MMPM? I have an idea of what kind of mechanism might be causing this issue, but I'll need the names of other applications that are checking.

**Comment by tkg61** [comment]
Yup, the root is set to be /home/pi/MagicMirror

The Magic mirror application itself is doing the check and using the [update notification](https://github.com/MichMich/MagicMirror/tree/master/modules/default/updatenotification) module 

Here is the output, basically nothing, so it makes sense why its not seeing it :) : 

<img width="1366" alt="MagicMirror Package Manager" src="https://user-images.githubusercontent.com/3945114/88493023-ed28f480-cf7c-11ea-8994-d26c458cca65.png">

**Comment by tkg61** [comment]
So maybe the update notification is doing it? I don’t recall running the command myself, i think before i upgraded MMPM i tried running its upgrade command To upgrade MM but it hadn’t done anything so maybe I’m just in a weird limbo state and need to see what happens next MM update?

**Comment by Bee-Mar** [comment]
well....here's the culprit in the update notification module 

https://github.com/MichMich/MagicMirror/blob/018cb9152689b1f1f262e6f3bfbf71cc99a9e59c/modules/default/updatenotification/node_helper.js#L75

```js
		var self = this;
		simpleGits.forEach((sg) => {
			sg.git.fetch().status((err, data) => {
				data.module = sg.module;
				if (!err) {
					sg.git.log({ "-1": null }, (err, data2) => {
						if (!err && data2.latest && "hash" in data2.latest) {
							data.hash = data2.latest.hash;
							self.sendSocketNotification("STATUS", data);
						}
					});
				}
			});
		});

```

this is running a normal `git fetch`, which retrieves the changes made to the repo. I may need to make a pull request to MagicMirror to change this. If it were running as `git fetch --dry-run`, MagicMirror could still detect there are updates available, but without retrieving the changes.

`git fetch`, fetches the changes, but doesn't apply them. `git pull`, fetches and applies the changes

**Comment by Bee-Mar** [comment]
@tkg61 I submitted a pull request to MagicMirror for this

**Comment by Bee-Mar** [comment]
@tkg61 until the merge request is accepted, I would suggest removing the `updatenotification` module from your config.js if you would like for the updates to be handled through MMPM.

**Comment by Bee-Mar** [comment]
@tkg61 as an update, the pull request I made for MagicMirror has been merged into the develop branch, so the issue should get resolved whenever that's integrated into the next release

**Comment by khassel** [comment]
fyi: MM releases are only quarterly, next is Oct. 1.

**Comment by Bee-Mar** [comment]
@khassel yep, it'll be a little bit. The only bandaid right now would be for people to remove or comment out the `updatenotification` module from their config.js. That'll prevent MagicMirror from running `git fetch` and siphoning the remote git data

**Comment by Barokai** [comment]
just in case others are as curious as i am - here is the link to the mentioned MagicMirror pull request: https://github.com/MichMich/MagicMirror/pull/2100
:)
