### ISSUE TITLE
Install w/ virtualenv yields "mmpm is not installed"

### ISSUE THREAD

**Issue by sonicgoose** [Bee-Mar/mmpm#37]
Followed the instructions for installing with a virtual environment but "sudo mmpm install --gui" yields the response "mmpm is not installed." Have tried several times.

**Comment by Bee-Mar** [comment]
You should run `sudo mmpm install --gui`, when you run `mmpm install --gui` you'll be prompted for your root password, if one is present. When you run `sudo mmpm install --gui`, it looks for the `mmpm` executable on the root user's PATH, which won't exist in the virtualenv.

**Comment by sonicgoose** [comment]
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 https://deb.nodesource.com/node_10.x buster InRelease
Get:3 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Fetched 15.0 kB in 2s (7,038 B/s)    
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get install python3 nginx-full
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nginx-full is already the newest version (1.14.2-2+deb10u1).
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 415 not upgraded.
pi@raspberrypi:~ $ pip3 install --user virtualenv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: virtualenv in ./.local/lib/python3.7/site-packages (20.0.28)
Requirement already satisfied: appdirs<2,>=1.4.3 in /usr/lib/python3/dist-packages (from virtualenv) (1.4.3)
Requirement already satisfied: distlib<1,>=0.3.1 in ./.local/lib/python3.7/site-packages (from virtualenv) (0.3.1)
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python3/dist-packages (from virtualenv) (1.12.0)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in ./.local/lib/python3.7/site-packages (from virtualenv) (1.7.0)
Requirement already satisfied: filelock<4,>=3.0.0 in ./.local/lib/python3.7/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv) (3.1.0)
pi@raspberrypi:~ $ echo "export PATH=$PATH:~/.venv/bin" >> ~/.bashrc
pi@raspberrypi:~ $ source ~/.bashrc ~/.venv/bin/activate
pi@raspberrypi:~ $ pip3 install mmpm
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: mmpm in ./.local/lib/python3.7/site-packages (2.1)
Requirement already satisfied: flask==1.1.1 in ./.local/lib/python3.7/site-packages (from mmpm) (1.1.1)
Requirement already satisfied: gunicorn>=20.0.4 in ./.local/lib/python3.7/site-packages (from mmpm) (20.0.4)
Requirement already satisfied: python-socketio[client]>=4.6.0 in ./.local/lib/python3.7/site-packages (from mmpm) (4.6.0)
Requirement already satisfied: eventlet==0.25.1 in ./.local/lib/python3.7/site-packages (from mmpm) (0.25.1)
Requirement already satisfied: pygments>=2.3.1 in /usr/lib/python3/dist-packages (from mmpm) (2.3.1)
Requirement already satisfied: argcomplete>=1.11.1 in ./.local/lib/python3.7/site-packages (from mmpm) (1.12.0)
Requirement already satisfied: colorama>=0.4.3 in ./.local/lib/python3.7/site-packages (from mmpm) (0.4.3)
Requirement already satisfied: bs4>=0.0.1 in ./.local/lib/python3.7/site-packages (from mmpm) (0.0.1)
Requirement already satisfied: Flask-Cors>=3.0.8 in ./.local/lib/python3.7/site-packages (from mmpm) (3.0.8)
Requirement already satisfied: webssh>=1.5.1 in ./.local/lib/python3.7/site-packages (from mmpm) (1.5.2)
Requirement already satisfied: flask-socketio>=4.2.1 in ./.local/lib/python3.7/site-packages (from mmpm) (4.3.1)
Requirement already satisfied: argparse>=1.1 in ./.local/lib/python3.7/site-packages (from mmpm) (1.4.0)
Requirement already satisfied: requests==2.23.0 in ./.local/lib/python3.7/site-packages (from mmpm) (2.23.0)
Requirement already satisfied: Jinja2>=2.10.1 in ./.local/lib/python3.7/site-packages (from flask==1.1.1->mmpm) (2.11.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (0.24)
Requirement already satisfied: click>=5.1 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in ./.local/lib/python3.7/site-packages (from flask==1.1.1->mmpm) (1.0.1)
Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn>=20.0.4->mmpm) (40.8.0)
Requirement already satisfied: python-engineio>=3.13.0 in ./.local/lib/python3.7/site-packages (from python-socketio[client]>=4.6.0->mmpm) (3.13.1)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from python-socketio[client]>=4.6.0->mmpm) (1.12.0)
Requirement already satisfied: websocket-client>=0.54.0; extra == "client" in ./.local/lib/python3.7/site-packages (from python-socketio[client]>=4.6.0->mmpm) (0.57.0)
Requirement already satisfied: dnspython>=1.15.0 in ./.local/lib/python3.7/site-packages (from eventlet==0.25.1->mmpm) (2.0.0)
Requirement already satisfied: monotonic>=1.4 in ./.local/lib/python3.7/site-packages (from eventlet==0.25.1->mmpm) (1.5)
Requirement already satisfied: greenlet>=0.3 in ./.local/lib/python3.7/site-packages (from eventlet==0.25.1->mmpm) (0.4.16)
Requirement already satisfied: importlib-metadata<2,>=0.23; python_version == "3.7" in ./.local/lib/python3.7/site-packages (from argcomplete>=1.11.1->mmpm) (1.7.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4>=0.0.1->mmpm) (4.7.1)
Requirement already satisfied: paramiko>=2.3.1 in ./.local/lib/python3.7/site-packages (from webssh>=1.5.1->mmpm) (2.7.1)
Requirement already satisfied: tornado>=4.5.0 in /usr/lib/python3/dist-packages (from webssh>=1.5.1->mmpm) (5.1.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (2018.8.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (2.6)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->flask==1.1.1->mmpm) (1.1.0)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.7/site-packages (from importlib-metadata<2,>=0.23; python_version == "3.7"->argcomplete>=1.11.1->mmpm) (3.1.0)
Requirement already satisfied: bcrypt>=3.1.3 in ./.local/lib/python3.7/site-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (3.1.7)
Requirement already satisfied: pynacl>=1.0.1 in ./.local/lib/python3.7/site-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (1.4.0)
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (2.6.1)
Requirement already satisfied: cffi>=1.1 in ./.local/lib/python3.7/site-packages (from bcrypt>=3.1.3->paramiko>=2.3.1->webssh>=1.5.1->mmpm) (1.14.0)
Requirement already satisfied: pycparser in ./.local/lib/python3.7/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.3.1->webssh>=1.5.1->mmpm) (2.20)
pi@raspberrypi:~ $ mmpm --migrate
-bash: /home/pi/.venv/bin/mmpm: No such file or directory
pi@raspberrypi:~ $ mmpm install --gui
-bash: /home/pi/.venv/bin/mmpm: No such file or directory
pi@raspberrypi:~ $

**Comment by Bee-Mar** [comment]
It's very unclear was what I'm looking at with all of the redacted text, and from the commands I see above, there's nothing that shows the virtualenv was ever created. It doesn't look like you created a virtualenv, because it says the `./.local/lib/python3.7/site-packages (from mmpm) (1.1.1)` requirement is already met. This says mmpm is installed in your `--local` path

**Comment by Bee-Mar** [comment]
please recreate it with the following:

```sh
rm -rf ~/.venv
python3 -m venv ~/.venv
source ~/.venv/bin/activate
pip3 install mmpm

```

**Comment by Bee-Mar** [comment]
@sonicgoose also, i just realized there was a typo in the readme, it shouldn't be `source ~/.bashrc ~/.venv/bin/activate`. They should be source separately, which is now reflected in the readme.

**Comment by sonicgoose** [comment]
Finally got it running. I noticed you had me skip over both of these:

# OPTION 1: you can add the venv to your PATH
$ echo "export PATH=$PATH:~/.venv/bin" >> ~/.bashrc

# OPTION 2: create an alias
$ echo "alias mmpm=~/.venv/bin/mmpm" >> ~/.bashrc

I had tried both in the past with no success.

Now — how do I access the gui web gui from a remote workstation? Seems to work only from the pi on which it is installed.

**Comment by Bee-Mar** [comment]
I removed the alias recommendation and the bashrc sourcing from the wiki after realizing it probably just adds confusion. The gui address will be a the ip address of the device hosting your magicmirror and is running on port 7890, and you should be able to get it with `mmpm list --gui-url`.

If your MagicMirror host is running on 192.168.0.10, the GUI will be located at `http://192.168.0.10:7890`

**Comment by Bee-Mar** [comment]
when you say remote workstation, do you mean external to your local network?

**Comment by sonicgoose** [comment]
No, on my local network. It does work with the lan url but does not show the list of active modules, despite having set the ipwhitelist correctly.

**Comment by Bee-Mar** [comment]
follow the instructions here: https://github.com/Bee-Mar/mmpm/wiki/Status,-Hide,-Show-MagicMirror-Modules

**Comment by Bee-Mar** [comment]
I'm going to close this issue since the issue posted is resolved, but feel free to ask anymore questions in this thread.
