### ISSUE TITLE
Version in GUI and/or CLI?

### ISSUE THREAD

**Issue by amarand** [Bee-Mar/mmpm#39]
Is there a way to determine which version of MMPM I have installed on my system?

It would be nice to have a -v or --version command on the CLI, but also a "version"/"info" button somewhere in the GUI as well.

Thanks!

**Comment by Bee-Mar** [comment]
@amarand there is in the CLI, and I definitely will be adding one for the GUI in the next update.

You can list the version in the CLI with `mmpm -v` or `mmpm --version`
