### ISSUE TITLE
error on execution of pip3 install

### ISSUE THREAD

**Issue by kjgoodwin299** [Bee-Mar/mmpm#41]
Working on my first magic mirror installation. I did a clean install of raspberry pi os and then installed magic mirror and successfully was able to start up. I now moved on to install MMPM and I’m receiving the following error when I execute pip3 install --upgrade --no-cache-dir mmpm:

Command “/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e41bnr3i --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple – setuptools>=40.8.0 wheel “cffi>=1.1; python_implementation != ‘PyPy’”” failed with error code 1 in None

Complete newbie here so any help is greatly appreciated. I assume I’m doing something wrong but thought I would ask for guidance rather than banging my head on the wall!

**Comment by Bee-Mar** [comment]
What version of Python3 and pip or pip3 do you have installed?

Please post the output from the following commands:
`python3 --version`
`pip3 --version`
`pip --version`

**Comment by kjgoodwin299** [comment]
Thanks for the help Bee-Mar, I'm sure I'm missing something.  here is the output.
pi@raspberrypi:~ $ python3 --version
Python 3.7.3
pi@raspberrypi:~ $ pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
pi@raspberrypi:~ $ pip --version
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

**Comment by Bee-Mar** [comment]
Can you also post the file that will result from this?

`python3 -m pip install -v --user mmpm > mmpm-install-output.log`

You can drag and drop the `mmpm-install-output.log` file into a comment box.

**Comment by kjgoodwin299** [comment]
[mmpm-install-output.log](https://github.com/Bee-Mar/mmpm/files/5099972/mmpm-install-output.log)

**Comment by Bee-Mar** [comment]
@kjgoodwin299 From the output, the only error I'm seeing is that you're missing the `ffi.h` header file. You can install the headers for that package with `sudo apt install libffi-dev`. There might be other missing dependencies that emerge after installing that, but at least it'll most likely move things along.

Why that isn't present on your system already is interesting though

**Comment by kjgoodwin299** [comment]
That did the trick.  Interesting problem, the install was done off a fresh full raspberry pi os that had been updated and then magic mirror installed, so about as clean as it gets.  No idea what caused it.  Thanks so much for your help!

**Comment by Bee-Mar** [comment]
@kjgoodwin299 no problem! yeah, it is odd. I've tested the mmpm installation a few times after fresh raspbian installs, and never encountered that issue
