### ISSUE TITLE
Not all package are shown and updated

### ISSUE THREAD

**Issue by josiy3** [Bee-Mar/mmpm#45]
Hi, i've the problem that "mmpm update" only show 2 modules and not all. What can I do?
env variables are correct. I've no idea what the problem is. All modules function properly on my mirror.

Can you help?
Thanks

**Comment by Bee-Mar** [comment]
@josiy3 please re-create the issue using the bug report template. There isn't any useful information for me to go off from what you've just stated.

**Comment by Bee-Mar** [comment]
@josiy3 please re-open this issue with more information provided by filling out the bug template after clicking "New issue"
