### ISSUE TITLE
mmpm don't update all modules

### ISSUE THREAD

**Issue by josiy3** [Bee-Mar/mmpm#46]
**Describe the Bug**

Is this an issue with the CLI or GUI?

Is this something that should be put in the Wiki?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`

- output from `python3 --version`

- Web Browser (firefox, chrome, safari, chromium, etc)

**MMPM Environment Settings**

- output from `mmpm env`

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by josiy3** [comment]
Describe the Bug

Is this an issue with the CLI or GUI?
* on both

Is this something that should be put in the Wiki?
* i dont think so


A clear and concise description of what the bug is.
with "mmpm update" only two modules and the magicmirror itself updated. All other modules are ignored 

To Reproduce 
*yes, the same result everytime i try it

Steps to reproduce the behavior:
* console: mmpm update 

Expected behavior
A clear and concise description of what you expected to happen.
* all modules will be updated
Screenshots
If applicable, add screenshots to help explain your problem.
![MM_1](https://user-images.githubusercontent.com/56740986/92304511-ed0a1480-ef7e-11ea-8183-248025567682.png)
![MM_2](https://user-images.githubusercontent.com/56740986/92304512-eda2ab00-ef7e-11ea-8b2e-33b20f7663a3.png)


Operating System, Python3 Version, and Web Browser
(Please complete the following information)

    output from cat /etc/os-release
![MM_3](https://user-images.githubusercontent.com/56740986/92304513-f7c4a980-ef7e-11ea-9608-3c01e17413a2.png)


    output from python3 --version
![MM_4](https://user-images.githubusercontent.com/56740986/92304517-fbf0c700-ef7e-11ea-9278-cf0e0ead9dd0.png)


    Web Browser (firefox, chrome, safari, chromium, etc)

MMPM Environment Settings

    output from mmpm env
![MM_5](https://user-images.githubusercontent.com/56740986/92304518-ff844e00-ef7e-11ea-8f7b-6de5206e0a05.png)


MMPM Log Files

    Attach the file produced Download MMPM log files within the Control Center of the GUI or from the mmpm log --zip
[mmpm-logs-2020-9-5.zip](https://github.com/Bee-Mar/mmpm/files/5178015/mmpm-logs-2020-9-5.zip)


MagicMirror Config

    your MagicMirror config.js
[config.txt](https://github.com/Bee-Mar/mmpm/files/5178016/config.txt)

**Comment by josiy3** [comment]
Can you help?

**Comment by Bee-Mar** [comment]
@josiy3 please check out this page ( https://github.com/Bee-Mar/mmpm/wiki/MMPM-Isn't-Displaying-Available-Upgrades! ) on the wiki and see if it may help

Also, not related to the issue, but you should set `MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE` to

`MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE: ""` 

instead of 

`MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE: "."` 

in your environment configuration

**Comment by josiy3** [comment]
@Bee-Mar thanks! I try it with the docker env variables. 
Your first help to comment the update notification out i've tried before. Nothing changed.

**Comment by josiy3** [comment]
Hi, i've tried it but nothing changed. Any other ideas?

**Comment by Bee-Mar** [comment]
@josiy3 if you run `mmpm list -i`, are all of your installed packages listed?

**Comment by josiy3** [comment]
@Bee-Mar : No, only two modules are shown.

**Comment by Bee-Mar** [comment]
@josiy3 and you originally installed all the modules using mmpm? sorry for all the piecemeal questions

**Comment by josiy3** [comment]
No, I install the modules and after that (mirror works 2 years for me :-) )

**Comment by josiy3** [comment]
@Bee-Mar you have another solution?

**Comment by Bee-Mar** [comment]
@josiy3 i haven't looked into this for a couple days, but it's been tough to pin down. I also haven't been able to reproduce it on my end
