### ISSUE TITLE
No updates found

### ISSUE THREAD

**Issue by requiemmg** [Bee-Mar/mmpm#47]
When I am on the command line, "mmpm update" will not find any updates ever.
Even when marketplace is refreshed from the GUI and even when an updatenotification is showing.
Using current MMPM version.

**Comment by Bee-Mar** [comment]
@requiemmg this is a duplicate of a currently open issue. Please post all relevant information on the thread here:

https://github.com/Bee-Mar/mmpm/issues/45

I’ve taken a break on working on stuff lately, but will get back on these issues later this afternoon.

**Comment by Bee-Mar** [comment]
@requiemmg closing this issue since it’s a duplicate
