### ISSUE TITLE
BUG: cannt start... + Initializing MagicMirror 3rd party packages database Traceback (most recent call last): and TypeError....

### ISSUE THREAD

**Issue by robudus** [Bee-Mar/mmpm#49]
**Describe the Bug**

Is this an issue with the CLI or GUI? with the installation

Is this something that should be put in the Wiki?

**To Reproduce**
pi@smartmirror:~ $ mmpm --guided-setup
Welcome to MMPM's guided setup!

I'll help you setup your environment variables, and install additional features. Pressing CTRL-C will cancel the entire process.
There are 6 to 12 questions, depending on your answers. Let's get started.

What is the absolute path to the root of your MagicMirror installation (ie. /home/pi/MagicMirror)? /home/pi/MagicMirror
Did you install MMPM as a Docker image, or using docker-compose? [yes/y] or [no/n]: n
Did you install MagicMirror using docker-compose? [yes/y] or [no/n]: n
Are you currently using PM2 with your MagicMirror? [yes/y] or [no/n]: y
What is the name of the PM2 process for MagicMirror? MagicMirror
Is http://127.0.1.1:8080 the address used to open MagicMirror in your browser?  [yes/y] or [no/n]: n
What is the URL used to access MagicMirror (ie. http://192.168.0.3:8080)? http://192.168.7.159:8080
Have you ever installed any version of MMPM < 2.01? [yes/y] or [no/n]: n
Would you like to install the MMPM GUI (web interface)? [yes/y] or [no/n]: y
Would you like to hide/show MagicMirror modules through MMPM? [yes/y] or [no/n]: y
Would you like to install tab-autocomplete for the MMPM CLI? [yes/y] or [no/n]: n
Are you sure you want to install the MMPM module? [yes/y] or [no/n]: yes
+ Creating MMPM module in MagicMirror modules directory ✓
Run `mmpm open --config` and add { module: "mmpm" } to the modules array, then restart MagicMirror if running
Are you sure you want to install the MMPM GUI? This requires sudo permission. [yes/y] or [no/n]: yes
+ MMPM SystemD service not active, nothing to do ✓
+ MMPM-WebSSH SystemD service not active, nothing to do ✓
+ Force removing NGINX and SystemD configs ✓
+ Reloading SystemdD daemon ✓
+ Restarting NGINX SystemD service ✓
MMPM GUI Removed!
+ Copying NGINX and SystemdD service configs ✓
+ Cleaning confiuration files and resetting SystemdD daemons
✓
+ Reloading SystemdD daemon ✓
+ Enabling MMPM SystemdD daemon ✓
✘
ERROR: Failed to start MMPM SystemD service. See `mmpm log` for details
Remove the MMPM GUI? [yes/y] or [no/n]: n
pi@smartmirror:~ $
pi@smartmirror:~ $
pi@smartmirror:~ $ mmpm log
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    title = mmpm.utils.sanitize_name(td_soup[idx].contents[0].contents[0])
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/utils.py", line 257, in sanitize_name
    return sub('[//]', '', orig_name)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
pi@smartmirror:~ $
pi@smartmirror:~ $
pi@smartmirror:~ $ mmpm install --gui
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    title = mmpm.utils.sanitize_name(td_soup[idx].contents[0].contents[0])
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/utils.py", line 257, in sanitize_name
    return sub('[//]', '', orig_name)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
pi@smartmirror:~ $ mmpm list --gui-url
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    title = mmpm.utils.sanitize_name(td_soup[idx].contents[0].contents[0])
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/utils.py", line 257, in sanitize_name
    return sub('[//]', '', orig_name)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
pi@smartmirror:~ $

**Expected behavior**
I cant start mmpm

I have installed with 
$ python3 -m pip install --user pipx
$ pipx install mmpm

**Screenshots**

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- output from `python3 --version`
Python 3.7.3
- Web Browser (firefox, chrome, safari, chromium, etc)

**MMPM Environment Settings**

- output from `mmpm env`
pi@smartmirror:~ $ mmpm env
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    title = mmpm.utils.sanitize_name(td_soup[idx].contents[0].contents[0])
  File "/home/pi/.local/pipx/venvs/mmpm/lib/python3.7/site-packages/mmpm/utils.py", line 257, in sanitize_name
    return sub('[//]', '', orig_name)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`
std sample config.js from first start. MM is running great and cann be startet in Firefox browser at mypc.

Please help... i have installed all twice an clean.

I try third with:
$ sudo apt install libffi-dev nginx-full -y
$ python3 -m pip install --upgrade --no-cache-dir mmpm
$ mmpm --guided-setup

it was sucessfull but if i try mmpm list -gui-url the same error

pi@smartmirror:~/MagicMirror/modules $ python3 -m pip install --upgrade --no-cache-dir mmpm
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mmpm
  Downloading https://files.pythonhosted.org/packages/b3/3d/81821c7cdd6faeb71edcecbad675c69823202e152ea221c62d483d8d1871/mmpm-2.04-py3-none-any.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 6.0MB/s
Requirement already satisfied, skipping upgrade: argcomplete>=1.11.1 in /home/pi/.local/lib/python3.7/site-packages (from mmpm) (1.12.0)
Collecting Flask-Cors>=3.0.8 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/69/7f/d0aeaaafb5c3c76c8d2141dbe2d4f6dca5d6c31872d4e5349768c1958abc/Flask_Cors-3.0.9-py2.py3-none-any.whl
Collecting eventlet==0.25.1 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/ef/01/83454d11bac9015f34e93cf11efcae169390ddf2df97cb73ca86de6465ed/eventlet-0.25.1-py2.py3-none-any.whl (222kB)
    100% |████████████████████████████████| 225kB 5.5MB/s
Collecting gunicorn>=20.0.4 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 5.9MB/s
Collecting python-socketio[client]>=4.6.0 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/3d/97/00741edd49788510b834b60a1a4d0afb2c4942770c11b8e0f6e914371718/python_socketio-4.6.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 4.9MB/s
Collecting argparse>=1.1 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting flask==1.1.1 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 5.6MB/s
Collecting flask-socketio>=4.2.1 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/8a/fa/ea1df958bd76a4a55b20dd87593839adf893e1fae0095b449fecdf325f21/Flask_SocketIO-4.3.1-py2.py3-none-any.whl
Collecting requests==2.23.0 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 4.9MB/s
Collecting colorama>=0.4.3 (from mmpm)
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pygments>=2.3.1 in /usr/lib/python3/dist-packages (from mmpm) (2.3.1)
Collecting bs4>=0.0.1 (from mmpm)
  Downloading https://www.piwheels.org/simple/bs4/bs4-0.0.1-py3-none-any.whl
Collecting webssh>=1.5.1 (from mmpm)
  Downloading https://www.piwheels.org/simple/webssh/webssh-1.5.2-py2.py3-none-any.whl (162kB)
    100% |████████████████████████████████| 163kB 2.3MB/s
Requirement already satisfied, skipping upgrade: importlib-metadata<2,>=0.23; python_version == "3.7" in /home/pi/.local/lib/python3.7/site-packages (from argcomplete>=1.11.1->mmpm) (1.7.0)
Requirement already satisfied, skipping upgrade: Six in /usr/lib/python3/dist-packages (from Flask-Cors>=3.0.8->mmpm) (1.12.0)
Collecting monotonic>=1.4 (from eventlet==0.25.1->mmpm)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting greenlet>=0.3 (from eventlet==0.25.1->mmpm)
  Downloading https://www.piwheels.org/simple/greenlet/greenlet-0.4.17-cp37-cp37m-linux_armv7l.whl (47kB)
    100% |████████████████████████████████| 51kB 759kB/s
Collecting dnspython>=1.15.0 (from eventlet==0.25.1->mmpm)
  Downloading https://files.pythonhosted.org/packages/90/49/cb426577c28ca3e35332815b795a99e467523843fc83cc85ca0d6be2515a/dnspython-2.0.0-py3-none-any.whl (208kB)
    100% |████████████████████████████████| 215kB 5.6MB/s
Requirement already satisfied, skipping upgrade: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn>=20.0.4->mmpm) (40.8.0)
Collecting python-engineio>=3.13.0 (from python-socketio[client]>=4.6.0->mmpm)
  Downloading https://files.pythonhosted.org/packages/4a/b0/602e549c6d735eb487f186b35e0b82e61c89459f57d1c24d5c7be6f56d05/python_engineio-3.13.2-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 4.6MB/s
Collecting websocket-client>=0.54.0; extra == "client" (from python-socketio[client]>=4.6.0->mmpm)
  Downloading https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 2.3MB/s
Collecting Jinja2>=2.10.1 (from flask==1.1.1->mmpm)
  Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 4.4MB/s
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (0.24)
Collecting Werkzeug>=0.15 (from flask==1.1.1->mmpm)
  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)
    100% |████████████████████████████████| 307kB 6.0MB/s
Requirement already satisfied, skipping upgrade: click>=5.1 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (7.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (2018.8.24)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (2.6)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4>=0.0.1->mmpm) (4.7.1)
Collecting paramiko>=2.3.1 (from webssh>=1.5.1->mmpm)
  Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)
    100% |████████████████████████████████| 215kB 4.8MB/s
Collecting tornado>=4.5.0 (from webssh>=1.5.1->mmpm)
  Downloading https://www.piwheels.org/simple/tornado/tornado-6.0.4-cp37-cp37m-linux_armv7l.whl (428kB)
    100% |████████████████████████████████| 430kB 5.2MB/s
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /home/pi/.local/lib/python3.7/site-packages (from importlib-metadata<2,>=0.23; python_version == "3.7"->argcomplete>=1.11.1->mmpm) (3.2.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->flask==1.1.1->mmpm) (1.1.0)
Requirement already satisfied, skipping upgrade: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (2.6.1)
Collecting pynacl>=1.0.1 (from paramiko>=2.3.1->webssh>=1.5.1->mmpm)
  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.4.0-cp37-cp37m-linux_armv7l.whl (605kB)
    100% |████████████████████████████████| 614kB 7.2MB/s
Collecting bcrypt>=3.1.3 (from paramiko>=2.3.1->webssh>=1.5.1->mmpm)
  Downloading https://www.piwheels.org/simple/bcrypt/bcrypt-3.2.0-cp37-cp37m-linux_armv7l.whl (57kB)
    100% |████████████████████████████████| 61kB 1.5MB/s
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko>=2.3.1->webssh>=1.5.1->mmpm)
  Downloading https://www.piwheels.org/simple/cffi/cffi-1.14.3-cp37-cp37m-linux_armv7l.whl (345kB)
    100% |████████████████████████████████| 348kB 3.5MB/s
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.3.1->webssh>=1.5.1->mmpm)
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 4.0MB/s
Installing collected packages: Jinja2, Werkzeug, flask, Flask-Cors, monotonic, greenlet, dnspython, eventlet, gunicorn, python-engineio, requests, websocket-client, python-socketio, argparse, flask-socketio, colorama, bs4, pycparser, cffi, pynacl, bcrypt, paramiko, tornado, webssh, mmpm
Successfully installed Flask-Cors-3.0.9 Jinja2-2.11.2 Werkzeug-1.0.1 argparse-1.4.0 bcrypt-3.2.0 bs4-0.0.1 cffi-1.14.3 colorama-0.4.3 dnspython-2.0.0 eventlet-0.25.1 flask-1.1.1 flask-socketio-4.3.1 greenlet-0.4.17 gunicorn-20.0.4 mmpm-2.4 monotonic-1.5 paramiko-2.7.2 pycparser-2.20 pynacl-1.4.0 python-engineio-3.13.2 python-socketio-4.6.0 requests-2.23.0 tornado-6.0.4 websocket-client-0.57.0 webssh-1.5.2
pi@smartmirror:~/MagicMirror/modules $ mmpm --guided-setup
Welcome to MMPM's guided setup!

I'll help you setup your environment variables, and install additional features. Pressing CTRL-C will cancel the entire process.
There are 6 to 12 questions, depending on your answers. Let's get started.

What is the absolute path to the root of your MagicMirror installation (ie. /home/pi/MagicMirror)? /home/pi/MagicMirror
Did you install MMPM as a Docker image, or using docker-compose? [yes/y] or [no/n]: n
Did you install MagicMirror using docker-compose? [yes/y] or [no/n]: n
Are you currently using PM2 with your MagicMirror? [yes/y] or [no/n]: y
What is the name of the PM2 process for MagicMirror? MagicMirror
Is http://127.0.1.1:8080 the address used to open MagicMirror in your browser?  [yes/y] or [no/n]: n
What is the URL used to access MagicMirror (ie. http://192.168.0.3:8080)? https://192.168.7.159:8080
Have you ever installed any version of MMPM < 2.01? [yes/y] or [no/n]: n
Would you like to install the MMPM GUI (web interface)? [yes/y] or [no/n]: y
Would you like to hide/show MagicMirror modules through MMPM? [yes/y] or [no/n]: y
Would you like to install tab-autocomplete for the MMPM CLI? [yes/y] or [no/n]: n
Are you sure you want to install the MMPM module? [yes/y] or [no/n]: yes
+ Creating MMPM module in MagicMirror modules directory ✓
Run `mmpm open --config` and add { module: "mmpm" } to the modules array, then restart MagicMirror if running
Are you sure you want to install the MMPM GUI? This requires sudo permission. [yes/y] or [no/n]: yes
+ Disabling MMPM SystemD service ✓
+ MMPM-WebSSH SystemD service not active, nothing to do ✓
+ MMPM-WebSSH SystemD service not enabled, nothing to do ✓
+ Force removing NGINX and SystemD configs ✓
+ Reloading SystemdD daemon ✓
+ Restarting NGINX SystemD service ✓
MMPM GUI Removed!
+ Copying NGINX and SystemdD service configs ✓
+ Cleaning confiuration files and resetting SystemdD daemons
✓
+ Reloading SystemdD daemon ✓
+ Enabling MMPM SystemdD daemon ✓
+ Restarting NGINX SystemD service ✓
MMPM GUI installed! See `mmpm list --gui-url` for the URI, or run `mmpm open --gui` to launch

Based on your responses, your environment variables have been set as:
{
  "MMPM_MAGICMIRROR_ROOT": "/home/pi/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "https://192.168.7.159:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}

Run `mmpm open --env` to edit the variable values

Done!

Please review the above output for any additional suggested instructions.

And the Error

pi@smartmirror:~/MagicMirror/modules $ mmpm list --gui-url
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    title = mmpm.utils.sanitize_name(td_soup[idx].contents[0].contents[0])
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 257, in sanitize_name
    return sub('[//]', '', orig_name)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
pi@smartmirror:~/MagicMirror/modules $

**Comment by marslane** [comment]
there is update on packages page (https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules/_compare/bff50b77d8ebe9647dd381a1dc94e2c9441e86ea...854ab5277f1f2cb32804eed6623afa111dd2d52f)
so the parser has problems with this line ~~MMM-GoogleAssistant~~

until parser is fixed, i added lazy local fix on: **core.py:1214**

try:
      title = mmpm.utils.sanitize_name(td_soup[idx].contents[0].contents[0])
 except:
     title = "missing name"

**Comment by Bee-Mar** [comment]
@marslane thanks for catching that! Would you like to make a merge request for that fix? If not, I can go ahead and make the change as well.

**Comment by Bee-Mar** [comment]
@marslane actually, I'll try just manually editing the 3rd Party Modules page to see if that'll fix the issue

**Comment by Bee-Mar** [comment]
@marslane @robudus I made a quick fix for this issue, and pushed it to develop. Once those tests finish, I'll merge it into the master branch, and it will be available on PyPI. The `<del>` tag generated by someone adding strikethrough marks on the 3rd Party Packages page caused this problem. It should be resolved within the hour
