### ISSUE TITLE
Running mmpm error

### ISSUE THREAD

**Issue by M08IUS0NE** [Bee-Mar/mmpm#5]
Hello!

I just finished installing mmpm into my Rasbian Buster build on RPi 3+ and ran into a snag. Any attempts to call mmpm from the terminal is met with an error.

Tabulate package not found. Pip installing with --user flag
=====================================

Traceback (most recent call last):
    File "/usr/local/bin/mmpm", line 43, in <module>
          import tabulate
ModuleNotFoundError: No module named 'tabulate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
     File "/usr/local/bin/mmpm", line 47, in <module>
         pip.main(["install", "--user", "tabulate"])
AttributeError: module 'pip' has no attribute 'main'

This seems like it could be an easy fix but I can't tell. I followed instructions but it doesn't seem to want to play.

**Comment by Bee-Mar** [comment]
This is possibly due to you needing to upgrade `pip`. You can try `pip install --upgrade pip` or `pip3 install --upgrade pip3`, or `hash -d pip3` or `hash -d pip`

**Comment by M08IUS0NE** [comment]
Thanks for the fast response! Attempts to run `pip3 install --upgrade pip3` are met with:
ERROR: Could not find a version that satisfies the requirement pip3 (from verisons: none)
ERROR: No matching distribution found for pip3

However running 'which pip3', I get a response pointing to a pip3 repository.

**Comment by M08IUS0NE** [comment]
Also: may be related, may not be: I don't believe the hidden json file ever installed. checked the directory and there wasn't anything with that file name, hidden or not.

**Comment by Bee-Mar** [comment]
Yeah, if the modules aren't loading, then the code that creates the json file will never be reached. It sound like you don't have `pip3` installed, based on your last message. Try running `sudo apt install python3-pip` ... I think that's the command. You can search for it with `apt search pip3`

**Comment by M08IUS0NE** [comment]
Hmmm... interesting. Running `apt search pip3` is yielding no results. Tested against `apt search pip` just to make sure the search was functioning and it is. Running `sudo apt install python3-pip` returns a comment that the newest versions is already installed. Running `python3 -m pip install --upgrade pip` says the requirements are already up-to-date: pip in /usr/local/lib/python3.7/dist-packages
Running `python -m pip install --upgrade pip` returns same information but directory is ./.local/lib/python2.7/site-packages

Thank you again for your prompt responses. I'm VERY new to anything Linux and hoped to noodle my way through most issues but this one has got me good.

**Comment by Bee-Mar** [comment]
That is odd, I'll keep looking into this and see what else it could be. I'm going to look into compiling this into a cython module, so it'll hopefully just be a binary download.

**Comment by Bee-Mar** [comment]
You can also try installing `python3-tabulate` with `sudo apt install python3-tabulate`, and look into installing the modules from the apt repo if any other don't work

**Comment by M08IUS0NE** [comment]
I ran `sudo apt install python3-tabulate` and then ran `mmpm` and it looks like it worked! Unsure why the python3-tabulate module didn't install originally or if maybe just restarting my pi helped too but it's working now! Thank you for all your help! 😄

**Comment by Bee-Mar** [comment]
Interesting, well, I'm glad it worked! I'll update the README to contain the instructions for installing the required Python modules from the apt repo in case someone else has the same issue as you.
