### ISSUE TITLE
BUG: flask-socketio Python requirment error on install

### ISSUE THREAD

**Issue by JoshuaShelswell** [Bee-Mar/mmpm#57]
right off a fresh install

flask-socketio 4.3.2 has requirement python-socketio<5,>=4.3.0, but you'll have python-socketio 5.0.1 which is incompatible.

seems like you need to clean stuff up

**Comment by Bee-Mar** [comment]
@JoshuaShelswell this actually sounds like an issue with a python package you already have installed that has other requirements. I'd install mmpm in virtualenv.

**Comment by JoshuaShelswell** [comment]
i did another fresh install and same error, its nothing i installed, you probably dont have something up to date with your program, im sure everyone has this error, its not just me

**Comment by JoshuaShelswell** [comment]
followed the virtualenv instructions and still this same error

flask-socketio 4.3.2 has requirement python-socketio<5,>=4.3.0, but you'll have python-socketio 5.0.1 which is incompatible.

not really sure if it effects the running of the program or not

**Comment by Bee-Mar** [comment]
@JoshuaShelswell glad you were able to get it working. I've also updated the readme's quickstart install instructions to include adding `~/.local/bin` to the user's bashrc. I'm going to close this issue since it's working for you, but let me know if you encounter any other issues.
