### ISSUE TITLE
Wrong css path?

### ISSUE THREAD

**Issue by khassel** [Bee-Mar/mmpm#58]
Hi,

before building the docker image for the new release I stumbled over [this line](https://github.com/Bee-Mar/mmpm/commit/825b8d82e76d3ac0e0f00af9d0b4ca6b44b38d0c#diff-d3368be5dfb6a93c672a0d2ecaa7313a5007b9787b69469d6a58d9304725e0d4R419):

````
MAGICMIRROR_CSS_DIR: str = os.path.join(get_env(mmpm.consts.MMPM_MAGICMIRROR_ROOT_ENV), 'custom')
````

I would expect:

````
MAGICMIRROR_CSS_DIR: str = os.path.join(get_env(mmpm.consts.MMPM_MAGICMIRROR_ROOT_ENV), 'css')
````

Can you take a look?

Thanks,

Karsten.

**Comment by Bee-Mar** [comment]
@khassel you are correct. I missed that when updating yesterday. I'll push the change now.

**Comment by Bee-Mar** [comment]
@khassel the build is running now
