### ISSUE TITLE
ERROR: Quick installation Issue (CLI)

### ISSUE THREAD

**Issue by Niklas1191** [Bee-Mar/mmpm#59]
When i come to mmpm --guided-setup i get this error below. (Also tried it with sudo as suggested in MM discord)

Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 6, in <module>
    from mmpm.__main__ import main
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 4, in <module>
    from mmpm.mmpm import main as _main_
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 6, in <module>
    import mmpm.utils
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 15, in <module>
    import mmpm.consts
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/consts.py", line 58, in <module>
    MMPM_MAGICMIRROR_URI_ENV: f'http://{gethostbyname(gethostname())}:8080',
socket.gaierror: [Errno -2] Name or service not known

Requested logs below.

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

Python 3.7.3

Stock MM config.

Rpi v4 + Poe-hat

**Comment by Bee-Mar** [comment]
Can you rerun 'mmpm --guided-setup' and copy your responses to each question? It might help me understand where the error occurred. Usually that error would be thrown whenever you don't have an internet connection.

**Comment by Niklas1191** [comment]
That is what i get once i run the command, I do not get anyquestions to respond to.

 

Niklas Bill

___________________________________

Digisign AB

Drivhjulsvägen 22B

126 30 HÄGERSTEN

Tel: +46 8 681 17 72

Mail: niklas@digisign.se

___________________________________

This email may contain confidential information. If you are not the intended recipient 

(or have received this email in error) please notify the sender immediately and delete 

this email. Any unauthorized copying, disclosure or distribution of the material in this 

email is strictly forbidden. 

 

* Please consider the environment before printing this email and any associated attachments.

 

 

Från: Brandon Marlowe <notifications@github.com>
Svara till: Bee-Mar/mmpm <reply@reply.github.com>
Datum: onsdag 16 december 2020 16:36
Till: Bee-Mar/mmpm <mmpm@noreply.github.com>
Kopia: Niklas Bill <niklas@digisign.se>, Author <author@noreply.github.com>
Ämne: Re: [Bee-Mar/mmpm] ERROR: Quick installation Issue (CLI) (#59)

 

Can you rerun 'mmpm --guided-setup' and copy your responses to each question? It might help me understand where the error occurred. Usually that error would be thrown whenever you don't have an internet connection.

**Comment by Bee-Mar** [comment]
I'll be able to look at this on my laptop in a few hours, but have you attempted to reinstall mmpm?


If not, you can use the command below:

python3 -m pip install --upgrade --force-reinstall mmpm

**Comment by Niklas1191** [comment]
Did not work. See the full CLI below. (I’m going to try again with sudo and see if that works.)

 

pi@rpinews:~/MagicMirror/config $ python3 -m pip install --upgrade --force-reinstall mmpm

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple

Collecting mmpm

  Downloading https://files.pythonhosted.org/packages/20/75/feddd43fcead24956aab0d0b1b5d9acb8409567ce51c59dac8f73d2d118e/mmpm-2.09-py3-none-any.whl (2.9MB)

    100% |████████████████████████████████| 2.9MB 148kB/s 

Collecting colorama>=0.4.3 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl

Collecting python-socketio[client]>=4.6.0 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/16/69/cee745aa3aaebc6e91fd2bf90d1a2f1dc308637f44e91e4dc4db42c2b202/python_socketio-5.0.3-py2.py3-none-any.whl (51kB)

    100% |████████████████████████████████| 61kB 3.3MB/s 

Collecting eventlet==0.25.1 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/ef/01/83454d11bac9015f34e93cf11efcae169390ddf2df97cb73ca86de6465ed/eventlet-0.25.1-py2.py3-none-any.whl (222kB)

    100% |████████████████████████████████| 225kB 1.6MB/s 

Collecting flask==1.1.1 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)

    100% |████████████████████████████████| 102kB 2.8MB/s 

Collecting argcomplete>=1.11.1 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/e3/d0/ee7fc6ceac8957196def9bfa3b955d02163058defd3edd51ef7b1ff2769e/argcomplete-1.12.2-py2.py3-none-any.whl

Collecting requests==2.23.0 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)

    100% |████████████████████████████████| 61kB 3.0MB/s 

Collecting pygments>=2.3.1 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/85/c5/c437c383d5917fae9782eb6588bec8aff931afe13c76b9e8c03dacee9beb/Pygments-2.7.3-py3-none-any.whl (950kB)

    100% |████████████████████████████████| 952kB 267kB/s 

Collecting flask-socketio>=4.2.1 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/63/f8/79e2be4aae0d6be2b0c295f6d0720b676d64ed26847dc523eac0600a2961/Flask_SocketIO-5.0.0-py2.py3-none-any.whl

Collecting webssh>=1.5.1 (from mmpm)

  Downloading https://www.piwheels.org/simple/webssh/webssh-1.5.3-py2.py3-none-any.whl (165kB)

    100% |████████████████████████████████| 174kB 1.1MB/s 

Collecting gunicorn>=20.0.4 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)

    100% |████████████████████████████████| 81kB 3.7MB/s 

Collecting Flask-Cors>=3.0.8 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/69/7f/d0aeaaafb5c3c76c8d2141dbe2d4f6dca5d6c31872d4e5349768c1958abc/Flask_Cors-3.0.9-py2.py3-none-any.whl

Collecting argparse>=1.1 (from mmpm)

  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl

Collecting bs4>=0.0.1 (from mmpm)

  Downloading https://www.piwheels.org/simple/bs4/bs4-0.0.1-py3-none-any.whl

Collecting python-engineio>=4 (from python-socketio[client]>=4.6.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/c4/29/efdb97d117b0f6538b046b576e33c1cbd59b4d1c2959cf8d0f8089a8f1b4/python_engineio-4.0.0-py2.py3-none-any.whl (50kB)

    100% |████████████████████████████████| 51kB 3.2MB/s 

Collecting bidict>=0.21.0 (from python-socketio[client]>=4.6.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/67/d4/eaf9242722bf991e0955380dd6168020cb15a71cc0d3cc2373f4911b1f1d/bidict-0.21.2-py2.py3-none-any.whl

Collecting websocket-client>=0.54.0; extra == "client" (from python-socketio[client]>=4.6.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl (200kB)

    100% |████████████████████████████████| 204kB 2.0MB/s 

Collecting six>=1.10.0 (from eventlet==0.25.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl

Collecting dnspython>=1.15.0 (from eventlet==0.25.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/90/49/cb426577c28ca3e35332815b795a99e467523843fc83cc85ca0d6be2515a/dnspython-2.0.0-py3-none-any.whl (208kB)

    100% |████████████████████████████████| 215kB 2.0MB/s 

Collecting greenlet>=0.3 (from eventlet==0.25.1->mmpm)

  Downloading https://www.piwheels.org/simple/greenlet/greenlet-0.4.17-cp37-cp37m-linux_armv7l.whl (47kB)

    100% |████████████████████████████████| 51kB 604kB/s 

Collecting monotonic>=1.4 (from eventlet==0.25.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl

Collecting Jinja2>=2.10.1 (from flask==1.1.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl (125kB)

    100% |████████████████████████████████| 133kB 3.0MB/s 

Collecting itsdangerous>=0.24 (from flask==1.1.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl

Collecting Werkzeug>=0.15 (from flask==1.1.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298kB)

    100% |████████████████████████████████| 307kB 1.4MB/s 

Collecting click>=5.1 (from flask==1.1.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)

    100% |████████████████████████████████| 92kB 3.8MB/s 

Collecting importlib-metadata<4,>=0.23; python_version == "3.7" (from argcomplete>=1.11.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/7a/85/ac225e35048e050a6351b6f1251cdb2b6060092f2c6840aff1d6319941b1/importlib_metadata-3.3.0-py3-none-any.whl

Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.23.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl (127kB)

    100% |████████████████████████████████| 133kB 3.0MB/s 

Collecting chardet<4,>=3.0.2 (from requests==2.23.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)

    100% |████████████████████████████████| 143kB 2.9MB/s 

Collecting idna<3,>=2.5 (from requests==2.23.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)

    100% |████████████████████████████████| 61kB 3.6MB/s 

Collecting certifi>=2017.4.17 (from requests==2.23.0->mmpm)

  Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)

    100% |████████████████████████████████| 153kB 2.7MB/s 

Collecting paramiko>=2.3.1 (from webssh>=1.5.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)

    100% |████████████████████████████████| 215kB 2.0MB/s 

Collecting tornado>=4.5.0 (from webssh>=1.5.1->mmpm)

  Downloading https://www.piwheels.org/simple/tornado/tornado-6.1-cp37-cp37m-linux_armv7l.whl (428kB)

    100% |████████████████████████████████| 430kB 985kB/s 

Collecting setuptools>=3.0 (from gunicorn>=20.0.4->mmpm)

  Downloading https://files.pythonhosted.org/packages/3d/f2/1489d3b6c72d68bf79cd0fba6b6c7497df4ebf7d40970e2d7eceb8d0ea9c/setuptools-51.0.0-py3-none-any.whl (785kB)

    100% |████████████████████████████████| 788kB 514kB/s 

Collecting beautifulsoup4 (from bs4>=0.0.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/d1/41/e6495bd7d3781cee623ce23ea6ac73282a373088fcd0ddc809a047b18eae/beautifulsoup4-4.9.3-py3-none-any.whl (115kB)

    100% |████████████████████████████████| 122kB 3.0MB/s 

Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask==1.1.1->mmpm)

  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.1.1-cp37-cp37m-linux_armv7l.whl

Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata<4,>=0.23; python_version == "3.7"->argcomplete>=1.11.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl

Collecting zipp>=0.5 (from importlib-metadata<4,>=0.23; python_version == "3.7"->argcomplete>=1.11.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl

Collecting pynacl>=1.0.1 (from paramiko>=2.3.1->webssh>=1.5.1->mmpm)

  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.4.0-cp37-cp37m-linux_armv7l.whl (605kB)

    100% |████████████████████████████████| 614kB 662kB/s 

Collecting bcrypt>=3.1.3 (from paramiko>=2.3.1->webssh>=1.5.1->mmpm)

  Downloading https://www.piwheels.org/simple/bcrypt/bcrypt-3.2.0-cp37-cp37m-linux_armv7l.whl (57kB)

    100% |████████████████████████████████| 61kB 3.6MB/s 

Collecting cryptography>=2.5 (from paramiko>=2.3.1->webssh>=1.5.1->mmpm)

  Downloading https://www.piwheels.org/simple/cryptography/cryptography-3.3.1-cp37-cp37m-linux_armv7l.whl (782kB)

    100% |████████████████████████████████| 788kB 562kB/s 

Collecting soupsieve>1.2; python_version >= "3.0" (from beautifulsoup4->bs4>=0.0.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/02/fb/1c65691a9aeb7bd6ac2aa505b84cb8b49ac29c976411c6ab3659425e045f/soupsieve-2.1-py3-none-any.whl

Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko>=2.3.1->webssh>=1.5.1->mmpm)

  Downloading https://www.piwheels.org/simple/cffi/cffi-1.14.4-cp37-cp37m-linux_armv7l.whl (346kB)

    100% |████████████████████████████████| 348kB 1.2MB/s 

Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.3.1->webssh>=1.5.1->mmpm)

  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)

    100% |████████████████████████████████| 112kB 3.0MB/s 

Installing collected packages: colorama, python-engineio, bidict, urllib3, chardet, idna, certifi, requests, six, websocket-client, python-socketio, dnspython, greenlet, monotonic, eventlet, MarkupSafe, Jinja2, itsdangerous, Werkzeug, click, flask, typing-extensions, zipp, importlib-metadata, argcomplete, pygments, flask-socketio, pycparser, cffi, pynacl, bcrypt, cryptography, paramiko, tornado, webssh, setuptools, gunicorn, Flask-Cors, argparse, soupsieve, beautifulsoup4, bs4, mmpm

  Found existing installation: colorama 0.4.4

    Uninstalling colorama-0.4.4:

      Successfully uninstalled colorama-0.4.4

  Found existing installation: python-engineio 4.0.0

    Uninstalling python-engineio-4.0.0:

      Successfully uninstalled python-engineio-4.0.0

  Found existing installation: bidict 0.21.2

    Uninstalling bidict-0.21.2:

      Successfully uninstalled bidict-0.21.2

  Found existing installation: requests 2.23.0

    Uninstalling requests-2.23.0:

      Successfully uninstalled requests-2.23.0

  Found existing installation: websocket-client 0.57.0

    Uninstalling websocket-client-0.57.0:

      Successfully uninstalled websocket-client-0.57.0

  Found existing installation: python-socketio 5.0.2

    Uninstalling python-socketio-5.0.2:

      Successfully uninstalled python-socketio-5.0.2

  Found existing installation: dnspython 2.0.0

    Uninstalling dnspython-2.0.0:

      Successfully uninstalled dnspython-2.0.0

  Found existing installation: greenlet 0.4.17

    Uninstalling greenlet-0.4.17:

      Successfully uninstalled greenlet-0.4.17

  Found existing installation: monotonic 1.5

    Uninstalling monotonic-1.5:

      Successfully uninstalled monotonic-1.5

  Found existing installation: eventlet 0.25.1

    Uninstalling eventlet-0.25.1:

      Successfully uninstalled eventlet-0.25.1

  Found existing installation: Jinja2 2.11.2

    Uninstalling Jinja2-2.11.2:

      Successfully uninstalled Jinja2-2.11.2

  Found existing installation: Werkzeug 1.0.1

    Uninstalling Werkzeug-1.0.1:

      Successfully uninstalled Werkzeug-1.0.1

  Found existing installation: Flask 1.1.1

    Uninstalling Flask-1.1.1:

      Successfully uninstalled Flask-1.1.1

  Found existing installation: typing-extensions 3.7.4.3

    Uninstalling typing-extensions-3.7.4.3:

      Successfully uninstalled typing-extensions-3.7.4.3

  Found existing installation: zipp 3.4.0

    Uninstalling zipp-3.4.0:

      Successfully uninstalled zipp-3.4.0

  Found existing installation: importlib-metadata 3.3.0

    Uninstalling importlib-metadata-3.3.0:

      Successfully uninstalled importlib-metadata-3.3.0

  Found existing installation: argcomplete 1.12.2

    Uninstalling argcomplete-1.12.2:

      Successfully uninstalled argcomplete-1.12.2

  Found existing installation: Flask-SocketIO 5.0.0

    Uninstalling Flask-SocketIO-5.0.0:

      Successfully uninstalled Flask-SocketIO-5.0.0

  Found existing installation: pycparser 2.20

    Uninstalling pycparser-2.20:

      Successfully uninstalled pycparser-2.20

  Found existing installation: cffi 1.14.4

    Uninstalling cffi-1.14.4:

      Successfully uninstalled cffi-1.14.4

  Found existing installation: PyNaCl 1.4.0

    Uninstalling PyNaCl-1.4.0:

      Successfully uninstalled PyNaCl-1.4.0

  Found existing installation: bcrypt 3.2.0

    Uninstalling bcrypt-3.2.0:

      Successfully uninstalled bcrypt-3.2.0

  Found existing installation: paramiko 2.7.2

    Uninstalling paramiko-2.7.2:

      Successfully uninstalled paramiko-2.7.2

  Found existing installation: webssh 1.5.3

    Uninstalling webssh-1.5.3:

      Successfully uninstalled webssh-1.5.3

  Found existing installation: gunicorn 20.0.4

    Uninstalling gunicorn-20.0.4:

      Successfully uninstalled gunicorn-20.0.4

  Found existing installation: Flask-Cors 3.0.9

    Uninstalling Flask-Cors-3.0.9:

      Successfully uninstalled Flask-Cors-3.0.9

  Found existing installation: argparse 1.4.0

    Uninstalling argparse-1.4.0:

      Successfully uninstalled argparse-1.4.0

  Found existing installation: bs4 0.0.1

    Uninstalling bs4-0.0.1:

      Successfully uninstalled bs4-0.0.1

  Found existing installation: mmpm 2.7

    Uninstalling mmpm-2.7:

      Successfully uninstalled mmpm-2.7

Successfully installed Flask-Cors-3.0.9 Jinja2-2.11.2 MarkupSafe-1.1.1 Werkzeug-1.0.1 argcomplete-1.12.2 argparse-1.4.0 bcrypt-3.2.0 beautifulsoup4-4.9.3 bidict-0.21.2 bs4-0.0.1 certifi-2020.12.5 cffi-1.14.4 chardet-3.0.4 click-7.1.2 colorama-0.4.4 cryptography-3.3.1 dnspython-2.0.0 eventlet-0.25.1 flask-1.1.1 flask-socketio-5.0.0 greenlet-0.4.17 gunicorn-20.0.4 idna-2.10 importlib-metadata-3.3.0 itsdangerous-1.1.0 mmpm-2.9 monotonic-1.5 paramiko-2.7.2 pycparser-2.20 pygments-2.7.3 pynacl-1.4.0 python-engineio-4.0.0 python-socketio-5.0.3 requests-2.23.0 setuptools-51.0.0 six-1.15.0 soupsieve-2.1 tornado-6.1 typing-extensions-3.7.4.3 urllib3-1.25.11 websocket-client-0.57.0 webssh-1.5.3 zipp-3.4.0

pi@rpinews:~/MagicMirror/config $ mmpm --guided-setup

Traceback (most recent call last):

  File "/home/pi/.local/bin/mmpm", line 6, in <module>

    from mmpm.__main__ import main

  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 4, in <module>

    from mmpm.mmpm import main as _main_

  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 6, in <module>

    import mmpm.utils

  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 15, in <module>

    import mmpm.consts

  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/consts.py", line 58, in <module>

    MMPM_MAGICMIRROR_URI_ENV: f'http://{gethostbyname(gethostname())}:8080',

socket.gaierror: [Errno -2] Name or service not known

 

 

Niklas Bill

___________________________________

Digisign AB

Drivhjulsvägen 22B

126 30 HÄGERSTEN

Tel: +46 8 681 17 72

Mail: niklas@digisign.se

___________________________________

This email may contain confidential information. If you are not the intended recipient 

(or have received this email in error) please notify the sender immediately and delete 

this email. Any unauthorized copying, disclosure or distribution of the material in this 

email is strictly forbidden. 

 

* Please consider the environment before printing this email and any associated attachments.

 

 

Från: Brandon Marlowe <notifications@github.com>
Svara till: Bee-Mar/mmpm <reply@reply.github.com>
Datum: onsdag 16 december 2020 16:36
Till: Bee-Mar/mmpm <mmpm@noreply.github.com>
Kopia: Niklas Bill <niklas@digisign.se>, Author <author@noreply.github.com>
Ämne: Re: [Bee-Mar/mmpm] ERROR: Quick installation Issue (CLI) (#59)

 

Can you rerun 'mmpm --guided-setup' and copy your responses to each question? It might help me understand where the error occurred. Usually that error would be thrown whenever you don't have an internet connection.

**Comment by Niklas1191** [comment]
Sudo did not do anything either.

It looks like it struggle to set the environment? Have Raspbian changed anything around this?

MM runs at 8080, should i change MM to run another port if MMPM needs it? Or should it be the same?

 

Niklas Bill

___________________________________

Digisign AB

Drivhjulsvägen 22B

126 30 HÄGERSTEN

Tel: +46 8 681 17 72

Mail: niklas@digisign.se

___________________________________

This email may contain confidential information. If you are not the intended recipient 

(or have received this email in error) please notify the sender immediately and delete 

this email. Any unauthorized copying, disclosure or distribution of the material in this 

email is strictly forbidden. 

 

* Please consider the environment before printing this email and any associated attachments.

 

 

Från: Brandon Marlowe <notifications@github.com>
Svara till: Bee-Mar/mmpm <reply@reply.github.com>
Datum: onsdag 16 december 2020 20:23
Till: Bee-Mar/mmpm <mmpm@noreply.github.com>
Kopia: Niklas Bill <niklas@digisign.se>, Author <author@noreply.github.com>
Ämne: Re: [Bee-Mar/mmpm] ERROR: Quick installation Issue (CLI) (#59)

 

I'll be able to look at this on my laptop in a few hours, but have you attempted to reinstall mmpm?

If not, you can use the command below:

python3 -m pip install --upgrade --force-reinstall mmpm

**Comment by Bee-Mar** [comment]
@Niklas1191 you shouldn't need to change the port. I'll take a look into this over the weekend after the holiday
