### ISSUE TITLE
Pip error?

### ISSUE THREAD

**Issue by WolfShadowheart** [Bee-Mar/mmpm#6]
Traceback (most recent call last):
  File "/usr/local/bin/mmpm", line 44, in <module>
    pip.main(["install", "--user", package])
AttributeError: module 'pip' has no attribute 'main'

I followed the instructions however I'm unable to get any of the mmpm commands to work, this is the only response I get!

**Comment by handwrittenjello** [comment]
I am also getting the same issue.  I installed on another Pi a few days ago and didn't have this issue

**Comment by handwrittenjello** [comment]
There was a previous issue and I resolved it by:

https://github.com/Bee-Mar/mmpm/issues/5#issuecomment-513429374

**Comment by WolfShadowheart** [comment]
Interesting! I wonder if it has something to do with how the Pi itself had installed? 

Edit: I see your linked comment, I will go and try that out! Thanks so much for finding that, I apologize that I didn't find it the first time!
