### ISSUE TITLE
Cannot Retrieve Modules

### ISSUE THREAD

**Issue by swvalenti194** [Bee-Mar/mmpm#60]
RPi has config correct with "0.0.0.0" and ip whitelist array empty []

Still can't detect modules running

Any ideas?

![Capture](https://user-images.githubusercontent.com/43345060/102558901-88da0f00-409c-11eb-935d-ec2892742ca4.PNG)

**Comment by Bee-Mar** [comment]
That is not the correct IP address. 0.0.0.0 is a meta address, you need the absolute address of the device running MagicMirror. The device's IP may be something like 192.168.X.X, or 10.0.X.X or something else possibly. For example, if the device running MagicMirror has an IP address of 192.168.0.71, that should be the value rather than 0.0.0.0

**Comment by swvalenti194** [comment]
I have the value of RPi in mmpm env table http://10.30.1.223:8080

**Comment by Dionice** [comment]
Same issue. Cannot retrieve modules.
mmpm log:
2020/12/18 01:32:24 [error] 2115#2115: *96 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.29, server: _, request: "GET /api/mmpm/environment-vars HTTP/1.1", upstream: "http://[::1]:7891/api/mmpm/environment-vars", host: "192.168.0.50:7890", referrer: "http://192.168.0.50:7890/"

**Comment by Bee-Mar** [comment]
Is your MagicMirror running?

**Comment by swvalenti194** [comment]
Yes sir

**Comment by Dionice** [comment]
> Is your MagicMirror running?

Yes 
![image](https://user-images.githubusercontent.com/13300036/102561181-b181f900-40dc-11eb-821c-4587c188f88d.png)

**Comment by Bee-Mar** [comment]
@swvalenti194 
> That is not the correct IP address. 0.0.0.0 is a meta address, you need the absolute address of the device running MagicMirror. The device's IP may be something like 192.168.X.X, or 10.0.X.X or something else possibly. For example, if the device running MagicMirror has an IP address of 192.168.0.71, that should be the value rather than 0.0.0.0

Sorry, should have been more clear. I read that too quickly and assumed you meant 0.0.0.0 was the IP you had in your mmpm env configuration.

**Comment by Bee-Mar** [comment]
@Dionice from the log files, all the API requests seem to fail. You should try restarting the nginx service on the device running MMPM.

`sudo systemctl restart nginx.service`

**Comment by Bee-Mar** [comment]
@swvalenti194 @Dionice have you both added MMPM to the module list in your MagicMirror `config.js`?

**Comment by swvalenti194** [comment]
Yes sir

**Comment by Bee-Mar** [comment]
@swvalenti194 can you attach your log files as well.

mmpm log --zip

**Comment by swvalenti194** [comment]
[mmpm-logs-2020-12-19.zip](https://github.com/Bee-Mar/mmpm/files/5719456/mmpm-logs-2020-12-19.zip)
 Here you go

**Comment by swvalenti194** [comment]
Not sure why or how but it shows up now, somehow mmpm was named y and I changed name to mmpm and it worked.

**Comment by Dionice** [comment]
For me issue is still reproducible:

`2020-12-22 13:11:11,750.750 INFO core - display_magicmirror_modules_status: attempting to connect to '/mmpm' namespace within MagicMirror websocket
attempting to connect to '/mmpm' namespace within MagicMirror websocket
2020-12-22 13:11:11,779.779 ERROR utils - error_msg: Failed to connect to MagicMirror, closing socket. Is MagicMirror running?
Failed to connect to MagicMirror, closing socket. Is MagicMirror running?
2020-12-22 13:11:11,780.780 ERROR core - display_magicmirror_modules_status: connect_error() takes 0 positional arguments but 1 was given
connect_error() takes 0 positional arguments but 1 was given
2020-12-22 13:11:11,781.781 INFO utils - socketio_client_disconnect: attempting to disconnect from MagicMirror websocket
attempting to disconnect from MagicMirror websocket
2020-12-22 13:11:16,761.761 WARNING utils - background_timer_thread: Reached fith second of 10 second timeout for connecting to MagicMirror websocket
Reached fith second of 10 second timeout for connecting to MagicMirror websocket
2020-12-22 13:11:21,768.768 WARNING utils - background_timer_thread: Reached 10 second timeout for connecting to MagicMirror websocket. Closing connection
Reached 10 second timeout for connecting to MagicMirror websocket. Closing connection
2020-12-22 13:11:21,776.776 INFO utils - socketio_client_disconnect: attempting to disconnect from MagicMirror websocket
attempting to disconnect from MagicMirror websocket`

**Comment by swvalenti194** [comment]
mmpm update doesn't recognize that there is an update for remote control?

`
pi@raspberrypi:~ $ mmpm update
Checking MMM-Remote-Control [package] for updates ✓
Checking MMM-DarkSkyForecast [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MMM-RTSPStream [package] for updates ✓
Checking MMM-EventHorizon [package] for updates ✓
Checking MMM-News [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
All packages are up to date
pi@raspberrypi:~ $
`
![Capture](https://user-images.githubusercontent.com/43345060/103094566-ed7cf880-45cb-11eb-9eb5-787889b496fc.PNG)

**Comment by Bee-Mar** [comment]
@swvalenti194 I'll take a look into this on over the weekend after the holiday is over. Also, the update may not be detected based on how MMM-Remote-Control handles its update checks. Which, is something that'll need to be investigated.

**Comment by shotbyapony** [comment]
> Not sure why or how but it shows up now, somehow mmpm was named y and I changed name to mmpm and it worked.

care to elaborate? i am getting the same problem

**Comment by khassel** [comment]
I found 2 problems concerning this issue:
- the installation as module is different to all other modules. mmpm expects only 2 files in `.modules/mmpm` folder (you can install it with `mmpm install --as-module`), not the complete mmpm repo. So if you install mmpm as module going into `modules` folder and doing `git clone ...` this will not work.
- the current mmpm release will not work with the new magicmirror release v2.14.0. I will provide a PR for this.

**Comment by JoyyoJ123** [comment]
> Not sure why or how but it shows up now, somehow mmpm was named y and I changed name to mmpm and it worked.

Hi, I'm facing the same issue: MM is working correctly but mmpm is not displaying modules. Command "mmpm mm-ctl --status" shows correctly the installed modules?

Can you please tell where did you found mmpm named "y" ?

**Comment by swvalenti194** [comment]
In the /home/pi directory.  For some reason on the install script when I hit "y" to one of the questions it named the mmpm folder to "y"   That make sense?

**Comment by JoyyoJ123** [comment]
In my /home/pi directory, i neither have an y folder nor a mmpm one.
The only mmpm folder i found is : /home/pi/.config/mmpm. But it looks correctly named.

Thank you anyway.

**Comment by khassel** [comment]
> MM is working correctly but mmpm is not displaying modules ( Command "mmpm mm-ctl --status" shows correctly the installed modules )

I'm interested in more info's about your setup (mm version and mmpm version).

And may you can look into the web console of your browser while loading the mmpm gui (ctrl+shift+i) if there are any errors or warnings. Thanks.

**Comment by JoyyoJ123** [comment]
Raspberry Pi 4 4GB
Raspbian GNU/Linux 10 (buster)
Node.js  Ver 14.15.4
MagicMirror2 Ver 2.14.0
mmpm-2.9

"mmpm mm-ctl --status" shows the "default" modules. But, not those installed by mmpm from the repository.

Below is my modules section in config.js :
`modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
        {
			module: "mmpm",
		},`

**Comment by Bl4CkGuuN** [comment]
Same error for me, have you found something so far?

**Comment by swvalenti194** [comment]
Not ideal, but you can delete all your modules and then install them via mmpm marketplace which should do the trick.

**Comment by Bee-Mar** [comment]
@Bl4CkGuuN @JoyyoJ123 what @swvalenti194 recommended should work. The reason that needs to be done is still something that's escaped me. MMPM should be able to pick up any existing repositories saved in your `MagicMirror/modules` directory

**Comment by JoyyoJ123** [comment]
If i select a module from the marketplace, it gets registered in "local modules" section. But remains unavailable in mmpm main page.

**Comment by r3z3** [comment]
Hi, exactly the same problem here...

**Comment by r3z3** [comment]
I can see this in my _/var/log/nginx/mmpm-error.log_

2021/01/19 10:55:00 [error] 1295#1295: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.94, server: _, request: "GET /api/mmpm/environment-vars HTTP/1.1", upstream: "http://[::1]:7891/api/mmpm/environment-vars", host: "192.168.1.98:7890", referrer: "http://192.168.1.98:7890/"

**Comment by Bl4CkGuuN** [comment]
@Bee-Mar I already installed every module via the marketplace expect the default ones.

With `mmpm mm-ctl --status` I'm able too see all the installed modules...

**Comment by r3z3** [comment]
I think that it's an IPV6 adress problem.
I tried to install MagicMirror whith different methods but I was never able to obtain the list of the actives modules on the CLI.
I works with the command line but I don't mind.

**Comment by r3z3** [comment]
Any ideas?

**Comment by khassel** [comment]
may we are discussing several problems in this thread ...

**For those who are using magic mirror version v2.14.0** and have problems to retrieve the modules via the gui: There is no chance to get this working without patching client (mmpm) or server (mm). Reason is mm v2.14.0 is the first release using socket.io v3 and mmpm is using socket.io-client v2.

You can 
- downgrade mm to v2.13.0 or 
- wait for the next release v2.15.0 coming in April or
- use the develop branch of mm (where this is already patched)

**Comment by JoyyoJ123** [comment]
Thanks.

**Comment by r3z3** [comment]
> may we are discussing several problems in this thread ...
> 
> **For those who are using magic mirror version v2.14.0** and have problems to retrieve the modules via the gui: There is no chance to get this working without patching client (mmpm) or server (mm). Reason is mm v2.14.0 is the first release using socket.io v3 and mmpm is using socket.io-client v2.
> 
> You can
> 
> * downgrade mm to v2.13.0 or
> * wait for the next release v2.15.0 coming in April or
> * use the develop branch of mm (where this is already patched)

**Comment by r3z3** [comment]
Yes, thanks a lot, I works like a charm with the develop branch of mm !

**Comment by rivierauk** [comment]
Hi all, sorry to hi-jack the thread!
I have the same issue as above, but are you able to explain how to upgrade to the 'develop branch' please?
Currently running 2.14.0 on RPi4
Thanks

**Comment by swvalenti194** [comment]
2.15 fixed this issue
