### ISSUE TITLE
pi@raspberrypi:~ $ mmpm --guided-setup bash: mmpm: Kommando nicht gefunden.

### ISSUE THREAD

**Issue by Marcus04102000** [Bee-Mar/mmpm#62]
pi@raspberrypi:~ $ mmpm --guided-setup
bash: mmpm: Kommando nicht gefunden.

I have completed the first two steps of the installation and tried "mmpm --guided-setup" but it did not find the mmpm command

**Comment by Bee-Mar** [comment]
You'll need to make sure ~/.local/bin is in your PATH.

Run the command below:

echo 'export PATH="$PATH:~/.local/bin"' >> ~/.bashrc
