### ISSUE TITLE
Unable to retrieve active modules 

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Bee-Mar/mmpm#64]
Hello,

I have the error:

`Please make sure MagicMirror is running, the MMPM_MAGICMIRROR_URI is correct, and the ipWhitelist in your MagicMirror config.js includes 0.0.0.0, or the ipWhitelist is an empty array.`

I opened MagicMirror in the Browser and also the MMPM_MAGICMIRROR_URI is correct.
The ipWhitelist Array is empty.

Any Ideas?

**Comment by khassel** [comment]
duplicate of #60 ?

**Comment by Bl4CkGuuN** [comment]
Oh yeah, my bad
