### ISSUE TITLE
Unable to retrieve active modules

### ISSUE THREAD

**Issue by Brand0n1** [Bee-Mar/mmpm#67]
I get the following error when I try to use the GUI associated with my magic mirror.

```
Unable to retrieve active modules error


Please make sure MagicMirror is running, the MMPM_MAGICMIRROR_URI is correct, and the ipWhitelist in your MagicMirror config.js includes 0.0.0.0, or the ipWhitelist is an empty array.

You may need to open MagicMirror in your browser to activate the connection.
```

Everything else seems to load up fine other than the modules. I have already set my "MMPM_MAGICMIRROR_URI " to the IP address of my pi as well as changing the address in the MagicMirror (config.js) to be "0.0.0.0" I also added the address "0.0.0.0" 
into the ipWhitelist in the (config.js). I have also added mmpm into the module list.

Modules:

> 	modules: [
> 		{
> 		module: "mmpm",
> 		},
> 		{
> 			module: "alert",
> 		},
> 		{
> 			module: "updatenotification",
> 			position: "top_bar"
> 		},
> 		{
> 			module: "clock",
> 			position: "top_left"
> 		},
> 		{
> 			module: "calendar",
> 			header: "US Holidays",
> 			position: "top_left",
> 			config: {
> 				calendars: [
> 					{
> 						symbol: "calendar-check",
> 						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
> 				]
> 			}
> 		},
> 		{
> 			module: "compliments",
> 			position: "lower_third"
> 		},
> 		{
> 			module: "currentweather",
> 			position: "top_right",
> 			config: {
> 				location: "New York",
> 				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
> 				appid: "YOUR_OPENWEATHER_API_KEY"
> 			}
> 		},
> 		{
> 			module: "weatherforecast",
> 			position: "top_right",
> 			header: "Weather Forecast",
> 			config: {
> 				location: "New York",
> 				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
> 				appid: "YOUR_OPENWEATHER_API_KEY"
> 			}
> 		},
> 		{
> 			module: "newsfeed",
> 			position: "bottom_bar",
> 			config: {
> 				feeds: [
> 					{
> 						title: "New York Times",
> 						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
> 					}
> 				],
> 				showSourceTitle: true,
> 				showPublishDate: true,
> 				broadcastNewsFeeds: true,
> 				broadcastNewsUpdates: true
> 			}
> 		},
> 	]
> };

**Comment by Brand0n1** [comment]
It's not solved and looks unactive

**Comment by Bee-Mar** [comment]
@Brand0n1 this has been moderately inactive lately, however the issue is being worked on now. This will be solved before the next MagicMirror release in April.

**Comment by Brand0n1** [comment]
okay thank you I guess, sucks that it can't be fixed until april

**Comment by swvalenti194** [comment]
Confirmed 2.15 fixed this issue

**Comment by IgorBass73** [comment]
So I have even after complete reinstallation with MM 2.15 and mmpm 2.09 the problem still. the Active modules are still not displayed.Can someone help me, 
is there a solution and it would be nice if he posts this !

**Comment by swvalenti194** [comment]
I don't have a comma after "mmpm" in my config...idk but grasping at straws to help ya maybe take that out and restart MM

**Comment by IgorBass73** [comment]
> 
> 
> I don't have a comma after "mmpm" in my config...idk but grasping at straws to help ya maybe take that out and restart MM

**Comment by IgorBass73** [comment]
Still does not work for me the same problem, modules are still not displayed :-( even after removing comma and restart.

**Comment by michael-zock** [comment]
I'm in the same boat.

**Comment by IgorBass73** [comment]
Hmmm apparently I'm too stupid , but I have now completely reinstalled the Pi but still have the same problem :-(

MM 2.15
mmpm 2.11
[mmpm-logs-2021-4-5.zip](https://github.com/Bee-Mar/mmpm/files/6480945/mmpm-logs-2021-4-5.zip)
