### ISSUE TITLE
BUG: or (my) inability... Initializing MagicMirror 3rd party packages database Traceback (most recent call last):

### ISSUE THREAD

**Issue by interessted** [Bee-Mar/mmpm#68]
I have reinstalled raspbian and magicmirror 5 times now. The mirror runs without problems. the installation of mmpm also works so far without error messages. however, if I call any mmpm command after the installation, such as mmpm open --env, I get this error message:

pi@raspberrypi:~/MagicMirror $ mmpm open --env
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    current_tag = td_soup[idx].contents[0].contents[0]
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 742, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'contents'

just mmpm works:
pi@raspberrypi:~/MagicMirror $ mmpm
usage: mmpm <subcommand> [option(s)]

The MagicMirror Package Manager CLI simplifies the installation, removal, and
general maintenance of MagicMirror packages

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         display MMPM version number
  --guided-setup        run the guided setup/installation of the GUI,
                        environment variables, and other features
  --migrate             migrate legacy file names and database keys. Only
                        required once if prior version of MMPM is < 1.25

MMPM subcommands:
  use `mmpm <subcommand> --help` to see more details

  {search,install,remove,update,upgrade,db,list,open,show,add-ext-pkg,log,mm-ctl,env}
    search              search for MagicMirror packages
    install             install MagicMirror packages
    remove              remove locally installed packages
    update              check for updates for installed packages, MMPM, and
                        MagicMirror
    upgrade             upgrade packages, MMPM, and/or MagicMirror, if
                        available
    db                  refresh or display basic details about the database
    list                list items such as installed packages, packages
                        available, available upgrades, etc
    open                quickly open config files, documentation, wikis, and
                        MagicMirror itself
    show                show details about one or more packages
    add-ext-pkg         manually add MagicMirror packages to your local
                        database
    log                 display, tail, or zip the MMPM log files
    mm-ctl              commands to control the MagicMirror
    env                 display the MMPM environment variables and their
                        value(s)

Visit https://github.com/Bee-Mar/mmpm/wiki for more details

also the --help for the commands: for e.g.
pi@raspberrypi:~/MagicMirror $ mmpm open --help
usage: 
  mmpm open [--config] [--css] [--gui] [--mm-wiki] [--mmpm-wiki]

optional arguments:
  -h, --help     show this help message and exit
  --config       open MagicMirror config/config.js file in your $EDITOR
  --css          open MagicMirror css/custom.css file (if it exists) in your
                 $EDITOR
  --gui          open the MMPM GUI in your default browser
  --magicmirror  open MagicMirror in your default browser (uses the
                 MMPM_MAGICMIRROR_URI address)
  --mm-wiki      open the MagicMirror GitHub wiki in your default browser
  --mm-docs      open the MagicMirror documentation in your default browser
  --mmpm-wiki    open the MMPM GitHub wiki in your default browser
  --env          open the MMPM run-time environment variables JSON
                 configuration file in your $EDITOR

But as another example the call of:
pi@raspberrypi:~/MagicMirror $ mmpm update
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1112, in load_packages
    packages = retrieve_packages()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1214, in retrieve_packages
    current_tag = td_soup[idx].contents[0].contents[0]
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 742, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'contents'

Please help, I seem to be overlooking something, but I have no idea what.

Cheers
Keep on going ! When it's running it's a great tool!!
J.

**Comment by Bee-Mar** [comment]
This is most likely an issue with the MagicMirror 3rd Party Module page being updated. I'll have to investigate later today after work.

**Comment by lordscarlet** [comment]
Yep., I just installed Magic Mirror and this for the first time tonight and I can confirm the same error.

**Comment by erikvoznak** [comment]
same here, I am building 2nd MM and after fresh install I am getting same error. on first MM I have mmpm version 2.09 and same version on 2nd one. hovewer on 1st pm2 version is v4.4.1 and on 2nd is v4.5.5. maybe that is the issue?

**Comment by Gustavomonteiro66** [comment]
Same here, exactly same error.

**Comment by Bee-Mar** [comment]
@erikvoznak @lordscarlet @Gustavomonteiro66 getting on this right now. The fix should be quick

**Comment by Bee-Mar** [comment]
@lordscarlet @Gustavomonteiro66 @erikvoznak @interessted give it a shot now. There was a rogue new line in the description of a module on the 3rd party modules page

**Comment by erikvoznak** [comment]
> @lordscarlet @Gustavomonteiro66 @erikvoznak @interessted give it a shot now. There was a rogue new line in the description of a module on the 3rd party modules page

it works, thank you man.

**Comment by Bee-Mar** [comment]
Cool, I'm going to close this issue
