### ISSUE TITLE
Cant connect with MagicMirror

### ISSUE THREAD

**Issue by max6129** [Bee-Mar/mmpm#69]
var config = {
	address: "0.0.0.0", 	
	port: 8080,
	basePath: "/", 	
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "0.0.0.0"], 	
	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true
	
mmpm still wont connect, i gave the corect url, i have the mirror running in browser.
	
is there something i forgot to do?

**Comment by Bee-Mar** [comment]
This is a known issue, related to a version of socket.io MagicMirror is using. A fix is on the way.

**Comment by Bee-Mar** [comment]
@max6129 a new version of mmpm has just been released, which should solve this issue
