### ISSUE TITLE
BUG: mmpm upgrade fails with "FileNotFoundError: [Errno 2] No such file or directory: ''"

### ISSUE THREAD

**Issue by erikvoznak** [Bee-Mar/mmpm#70]
mmpm upgrade fails with "FileNotFoundError: [Errno 2] No such file or directory: ''"

Is this an issue with the CLI or GUI?

cli issue

Is this something that should be put in the Wiki?

YES

mmpm update runs well:

 mmpm update
Checking MMM-Button [package] for updates ✓
Checking MMM-Buttons [package] for updates ✓
Checking MMM-connection-status [package] for updates ✓
Checking MMM-network-signal [package] for updates ✓
Checking MMM-OnScreenMenu [package] for updates ✓
Checking MMM-pages [package] for updates ✓
Checking MMM-page-indicator [package] for updates ✓
Checking MMM-Page-Selector [package] for updates ✓
Checking MMM-Remote-Control-Repository [package] for updates ✓
Checking MMM-Remote-Control [package] for updates ✓
Checking MMM-GoogleMapsTraffic [package] for updates ✓
Checking MMM-imhdsk [package] for updates ✓
Checking MMM-LocalTemperature [package] for updates ✓
Checking MMM-OpenWeatherMapForecast [package] for updates ✓
Checking MMM-weatherforecast [package] for updates ✓
Checking MMM-soccer [package] for updates ✓
Checking MMM-SystemStats [package] for updates ✓
Checking MMM-APOD [package] for updates ✓
Checking MMM-BackgroundSlideshow [package] for updates ✓
Checking MMM-GooglePhotos [package] for updates ✓
Checking MMM-ImageSlideshow [package] for updates ✓
Checking MMM-Meniny [package] for updates ✓
Checking MMM-NowPlayingOnSpotify [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
1 upgrade is available. Run `mmpm list --upgradable` for details

mmpm upgrade fails with:

Upgrade MMM-Remote-Control (https://github.com/Jopyth/MMM-Remote-Control) now? [yes/y] or [no/n]: y
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 149, in main
    mmpm.core.upgrade_available_packages_and_applications(args.assume_yes, additional_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 222, in upgrade_available_packages_and_applications
    error = upgrade_package(pkg)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 126, in upgrade_package
    os.chdir(package.directory)
FileNotFoundError: [Errno 2] No such file or directory: ''

in the logs;

2021-04-06 10:38:53,289.289 INFO core - check_for_mmpm_updates: Checking for newer version of MMPM. Current version: 2.09
Checking for newer version of MMPM. Current version: 2.09
2021-04-06 10:38:53,289.289 INFO utils - run_cmd: Executing process `curl https://raw.githubusercontent.com/Bee-Mar/mmpm/master/mmpm/mmpm.py` in foreground
Executing process `curl https://raw.githubusercontent.com/Bee-Mar/mmpm/master/mmpm/mmpm.py` in foreground
2021-04-06 10:38:53,804.804 INFO core - check_for_mmpm_updates: No newer version of MMPM found > 2.09 available. The current version is the latest
No newer version of MMPM found > 2.09 available. The current version is the latest
2021-04-06 10:38:59,430.430 INFO core - load_packages: Backing up database file as /home/pi/.config/mmpm/MagicMirror-3rd-party-packages-db.json.bak
Backing up database file as /home/pi/.config/mmpm/MagicMirror-3rd-party-packages-db.json.bak
2021-04-06 10:38:59,433.433 INFO core - load_packages: Back up of database complete
Back up of database complete
2021-04-06 10:39:19,000.000 INFO core - load_packages: Backing up database file as /home/pi/.config/mmpm/MagicMirror-3rd-party-packages-db.json.bak
Backing up database file as /home/pi/.config/mmpm/MagicMirror-3rd-party-packages-db.json.bak
2021-04-06 10:39:19,003.003 INFO core - load_packages: Back up of database complete
Back up of database complete
2021-04-06 10:39:19,015.015 ERROR utils - error_msg: Gunicorn access log file not found
Gunicorn access log file not found
2021-04-06 10:39:19,016.016 ERROR utils - error_msg: Gunicorn error log file not found
Gunicorn error log file not found

**Expected behavior**

upgrade of packages or magicmirror.

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

python3 --version
Python 3.7.3

**MMPM Environment Settings**

{
  "MMPM_MAGICMIRROR_ROOT": "/home/pi/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://127.0.1.1:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "PM2 v4.5.5: God Daemon (/home/pi/.pm2)",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}

**Comment by erikvoznak** [comment]
nope, issue still there.

another observation is that first run of mmpm update shown some error that it cannot communicate with git, and it run loooong time. second run was much quicker it also told me that there are upgrades, but upgrade failed again.

pi@mirrorsklabina:~ $ mmpm update
Checking MMM-Button [package] for updates ✓
Checking MMM-Buttons [package] for updates ✓
Checking MMM-connection-status [package] for updates ✓
Checking MMM-network-signal [package] for updates ✓
Checking MMM-OnScreenMenu [package] for updates ✓
Checking MMM-pages [package] for updates ✓
Checking MMM-page-indicator [package] for updates ✓
Checking MMM-Page-Selector [package] for updates ✓
Checking MMM-Remote-Control-Repository [package] for updates ✓
Checking MMM-Remote-Control [package] for updates ✓
Checking MMM-Remote-Control [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-GoogleMapsTraffic [package] for updates ✓
Checking MMM-imhdsk [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-LocalTemperature [package] for updates ✓
Checking MMM-OpenWeatherMapForecast [package] for updates ✓
Checking MMM-weatherforecast [package] for updates ✓
Checking MMM-soccer [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-SystemStats [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-APOD [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-BackgroundSlideshow [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-GooglePhotos [package] for updates ✘
ERROR: Unable to communicate with git server
Checking MMM-ImageSlideshow [package] for updates ✓
Checking MMM-Meniny [package] for updates ✓
Checking MMM-NowPlayingOnSpotify [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
All packages are up to date
pi@mirrorsklabina:~ $ mmpm update
Checking MMM-Button [package] for updates ✓
Checking MMM-Buttons [package] for updates ✓
Checking MMM-connection-status [package] for updates ✓
Checking MMM-network-signal [package] for updates ✓
Checking MMM-OnScreenMenu [package] for updates ✓
Checking MMM-pages [package] for updates ✓
Checking MMM-page-indicator [package] for updates ✓
Checking MMM-Page-Selector [package] for updates ✓
Checking MMM-Remote-Control-Repository [package] for updates ✓
Checking MMM-Remote-Control [package] for updates ✓
Checking MMM-GoogleMapsTraffic [package] for updates ✓
Checking MMM-imhdsk [package] for updates ✓
Checking MMM-LocalTemperature [package] for updates ✓
Checking MMM-OpenWeatherMapForecast [package] for updates ✓
Checking MMM-weatherforecast [package] for updates ✓
Checking MMM-soccer [package] for updates ✓
Checking MMM-SystemStats [package] for updates ✓
Checking MMM-APOD [package] for updates ✓
Checking MMM-BackgroundSlideshow [package] for updates ✓
Checking MMM-GooglePhotos [package] for updates ✓
Checking MMM-ImageSlideshow [package] for updates ✓
Checking MMM-Meniny [package] for updates ✓
Checking MMM-NowPlayingOnSpotify [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
2 upgrades are available. Run `mmpm list --upgradable` for details
pi@mirrorsklabina:~ $ mmpm upgrade
Upgrade MMM-soccer (https://github.com/fewieden/MMM-soccer) now? [yes/y] or [no/n]: y
Upgrade MMM-BackgroundSlideshow (https://github.com/darickc/MMM-BackgroundSlideshow) now? [yes/y] or [no/n]: y
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 149, in main
    mmpm.core.upgrade_available_packages_and_applications(args.assume_yes, additional_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 222, in upgrade_available_packages_and_applications
    error = upgrade_package(pkg)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 126, in upgrade_package
    os.chdir(package.directory)
FileNotFoundError: [Errno 2] No such file or directory: ''
pi@mirrorsklabina:~ $

**Comment by Bee-Mar** [comment]
Can you try deleting your MagicMirror modules manually, and reinstalling them using MMPM?

**Comment by erikvoznak** [comment]
this is how I upgrade modules now. I move them and then install them using your mmpm. so installation works fine. but upgrade is not working.

**Comment by jamesvcc** [comment]
I have the same issue I believe.
The module was installed using mmm and has previously been upgraded via mmm - just now it seems to stop.

Terminal output below:

pi@music:~ $ mmpm upgrade
Upgrade MMM-Spotify (https://github.com/skuethe/MMM-Spotify) now? [yes/y] or [no/n]: yes
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 149, in main
    mmpm.core.upgrade_available_packages_and_applications(args.assume_yes, additional_args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 222, in upgrade_available_packages_and_applications
    error = upgrade_package(pkg)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 126, in upgrade_package
    os.chdir(package.directory)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by Bee-Mar** [comment]
@jamesvcc @erikvoznak I'll look into this shortly. Sorry, have had a lot of personal things going on.

**Comment by r4nd1-gh** [comment]
Hi, File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 126, in upgrade_package
os.chdir(package.directory) prints me e.g. Upgrade MMM-COVID19-AMPEL (https://github.com/magic21nrw/MMM-COVID19-AMPEL) now? [yes/y] or [no/n]: y
{'title': 'MMM-COVID19-AMPEL', 'author': 'magic21nrw', 'repository': 'https://github.com/magic21nrw/MMM-COVID19-AMPEL', 'description': 'German Ampel for Incidence Value for your City', 'directory': ''} you can see "directory" is empty, which should not be.

**Comment by r4nd1-gh** [comment]
Hey, have solved it for me this way:
added following 2 lines in /home/pi/.local/lib/python3.7/site-packages/mmpm/core.py:
```
MAGICMIRROR_MODULES_DIR: str = os.path.normpath(os.path.join(get_env(mmpm.consts.MMPM_MAGICMIRROR_ROOT_ENV), 'modules'))
package.directory = os.path.join(MAGICMIRROR_MODULES_DIR, package.title)
```
on lines 125/126 in function upgrade_package before the line with `os.chdir(package.directory)`

**Comment by Bee-Mar** [comment]
@r4nd1-gh can you try reinstalling `MMM-COVID19-AMPEL`? Without adding your suggested lines the directory prints out correctly for me

**Comment by Bee-Mar** [comment]
@r4nd1-gh I stand corrected, there were fixes I was working on and something similar was actually already in place to fix this issue. I switched back to master branch, added your fix and it is indeed working. Sorry about that

**Comment by Bee-Mar** [comment]
@r4nd1-gh @jamesvcc  @erikvoznak there is a fix I'm trying to push for the active modules along with this to the master branch shortly. Once my tokens are updated and the build is working on the develop branch there will be a new version pushed for download

**Comment by Bee-Mar** [comment]
@khassel just an FYI, I'll be pushing a new version within the day

**Comment by Bee-Mar** [comment]
@erikvoznak @jamesvcc @r4nd1-gh the 2.12 was uploaded to PyPi last night which contains the fix
