### ISSUE TITLE
Include GUI Address in Quick Start Guide

### ISSUE THREAD

**Issue by baghtal** [Bee-Mar/mmpm#72]
Please add a line to the quick installation guide that the default URL to access is 127.0.0.1:7890. I had to dig through this page, the wiki page, the mmpm --help guide until i came across mmpm -l g. This was really not a great way to get started with the package. Now that i've deciphered how to access it it looks great!

**Comment by jamesheaver** [comment]
I don't even know where you found that port number to begin with. Even searching the wiki for the "7890" specifcally, doesn't show it appearing anywhere useful.

This issue was the only way I managed to find it and actually access the GUI

**Comment by Bee-Mar** [comment]
@baghtal @jamesheaver there is a built in command to display the URL of the GUI.

https://github.com/Bee-Mar/mmpm/wiki/Command-Line-Options#--gui-url----g

`mmpm list --gui-url`
