### ISSUE TITLE
BUG: Wiki documentation issue

### ISSUE THREAD

**Issue by SemperDiscere** [Bee-Mar/mmpm#73]
**Describe the Bug**
Functional error in mmpm Wiki
The closed Curly above the mmpm module should be an open curly.
Copy/Paste of the code causes a failure to load.

Is this an issue with the CLI or GUI? Wiki

Is this something that should be put in the Wiki? Yes

In the second Code Block

```
    }
      module: "mmpm"
    }
```
```
    {
      module: "mmpm"
    }
```
**To Reproduce**
1. Go to Wiki
2. Click on Status, Hide, Show MagicMirror Modules
3. Scroll down to 2nd Code Block

**Comment by Bee-Mar** [comment]
Haha thanks, I just corrected it.
