### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by dannydp79** [Bee-Mar/mmpm#76]
When loading MMPM I get the error that it's unable to retrieve active modules.

I've verified that the URI is correct, I am able to open the URI locally on the Raspberry PI without issue. The path seems fine as I'm able to edit config files in MMPM. I've tried addresssing it in the config as localhost, the IP of the pi (192.168.0.124), 0.0.0.0, and 127.

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- output from `python3 --version`
Python 3.7.3

- Web Browser (firefox, chrome, safari, chromium, etc)

Chromium

**MMPM Environment Settings**

- output from `mmpm env`
{
  "MMPM_MAGICMIRROR_ROOT": "/home/pi/MagicMirror",
  "MMPM_MAGICMIRROR_URI": "http://localhost:8080",
  "MMPM_MAGICMIRROR_PM2_PROCESS_NAME": "MagicMirror",
  "MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE": ".",
  "MMPM_IS_DOCKER_IMAGE": false
}

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/getting-started/configuration.html#general
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "0.0.0.0", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: [], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 12,
	units: "imperial",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module:"MMPM",
		},
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
[mmpm-logs-2021-6-3.zip](https://github.com/Bee-Mar/mmpm/files/6858617/mmpm-logs-2021-6-3.zip)

**Comment by Kanostic** [comment]
I am also having this issue.

Unable to retrieve active modules error


Please make sure MagicMirror is running, the MMPM_MAGICMIRROR_URI is correct, and the ipWhitelist in your MagicMirror config.js includes 0.0.0.0, or the ipWhitelist is an empty array.

You may need to open MagicMirror in your browser to activate the connection.

**Comment by Bee-Mar** [comment]
@Kanostic @dannydp79 have you both followed the instructions to install the MMPM MagicMirror module? This is required to retrieve the active modules

https://github.com/Bee-Mar/mmpm/wiki/Status,-Hide,-Show-MagicMirror-Modules

**Comment by dannydp79** [comment]
Sorry Brandon for now I've just given up on MMPM (this request was 
submitted some time ago)

------ Original Message ------
From: "Brandon Marlowe" ***@***.***>
To: "Bee-Mar/mmpm" ***@***.***>
Cc: "dannydp79" ***@***.***>; "Mention" 
***@***.***>
Sent: 9/16/2021 1:54:01 PM
Subject: Re: [Bee-Mar/mmpm] BUG: (#76)

>
***@***.*** ***@***.***

**Comment by Kanostic** [comment]
Pretty much the same with me. I tried following the guides.

**Comment by Bee-Mar** [comment]
@dannydp79 @istvanfedak @Kanostic @khassel @herostrat this should now be resolved in the 2.12 version uploaded last night

**Comment by Bee-Mar** [comment]
I'm closing this issue because other users have been able to get the "active modules" feature working with the new update.
