### ISSUE TITLE
BUG: Only the first instance of a module can be toggled by the 'Active Modules' selector

### ISSUE THREAD

**Issue by adamsjdavid** [Bee-Mar/mmpm#77]
**Describe the Bug**

[The GUI code for toggling module visibility](https://github.com/Bee-Mar/mmpm/blob/41262fac7b2be3cc3fce9a43c3b64aa411072975/gui/src/app/components/magic-mirror-control-center/magic-mirror-control-center.component.ts#L119) currently relies on only the module name field when determining which module to toggle.

In a default MagicMirror2 build, the mirror uses two separate instances of the "weather" module - one to display current conditions and one to display forecast conditions.

Since these instances are both named "weather", the MMPM visibility toggle enters an unexpected state. Although one toggle is generated per module, the weather toggles all control the first weather module. There is no way to control the second, third, etc module of the same name since the code implicitly expects module names to be unique.

**To Reproduce**

1. Add two instances of a specific module to your configuration
2. In the MMPM GUI, attempt to disable the modules
3. Notice that only the first is enabled/disabled. It is impossible to address additional modules with the same name.

**Expected behavior**

A second, third, ... module of the same name should be addressable via the 'Active Modules' section.

**Screenshots**

In the screenshot below, you can see that I have disabled all modules; however, one weather module remains on the display. Because the existing logic does not allow addressing beyond the first instance of a module, this module cannot be toggled on/off.

<img width="1146" alt="Screen Shot 2021-08-15 at 1 36 09 AM" src="https://user-images.githubusercontent.com/19543948/129468310-6c164e40-89ad-4c10-a78a-44986b281d8f.png">

**MagicMirror Config**
(Some modules removed for brevity)
```
let config = {
  address: "0.0.0.0",
  port: 8080,
  basePath: "/",
  ipWhitelist: [],

  useHttps: false,
  httpsPrivateKey: "",
  httpsCertificate: "",

  language: "en",
  locale: "en-US",
  logLevel: ["INFO", "LOG", "WARN", "ERROR"],
  timeFormat: 24,
  units: "imperial",

  modules: [{
      module: "mmpm",
    },
    {
      module: "alert",
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "clock",
      position: "top_left"
    },
    {
      module: "weather",
      position: "top_right",
      config: {
        weatherProvider: "openweathermap",
        type: "current",
        location: "Johnson City",
        locationID: "4633419",
        apiKey: "------"
      }
    },
    {
      module: "weather",
      position: "top_right",
      header: "Weather Forecast",
      config: {
        weatherProvider: "openweathermap",
        type: "forecast",
        location: "Johnson City",
        locationID: "4633419",
        apiKey: "-----"
      }
    },
  ]
};
```

**Comment by Bee-Mar** [comment]
@adamsjdavid I'll take a look at this shortly

**Comment by Bee-Mar** [comment]
@adamsjdavid this duplicate entry seems like a bug on the side of the MagicMirror developer. In the documentation, there's a usage example and only one entry is displayed. I'm quite certain you can just remove one of the "weather" entries and everything should still display as expected on MagicMirror

https://docs.magicmirror.builders/modules/weather.html#usage

**Comment by Bee-Mar** [comment]
@adamsjdavid download the latest version of MMPM and run the commands below. This issue should be resolved.

pip install --upgrade mmpm
mmpm install --gui
mmpm install --as-module

**Comment by Bee-Mar** [comment]
I'm closing this issue because other users have been able to get the "active modules" feature working with the new update.
