### ISSUE TITLE
soupsieve not installed error

### ISSUE THREAD

**Issue by KrunchMuffin** [Bee-Mar/mmpm#8]
`/home/pi/.local/lib/python2.7/site-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'`

> pi@raspberrypi:~ $ pip3 install soupsieve
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: soupsieve in /usr/lib/python3/dist-packages (1.8)
pi@raspberrypi:~ $ pip install soupsieve
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: soupsieve in ./.local/lib/python2.7/site-packages (1.9.5)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in ./.local/lib/python2.7/site-packages (from soupsieve) (1.6.1)

what am I missing?

**Comment by Bee-Mar** [comment]
@KrunchMuffin try re-running with the `--user` flag:

`pip3 install --user soupsieve`

Based on the error message, it looks like you have `soupsieve` for python3 already built in`/usr/lib`, however you have it installed for python2 in `$HOME/.local/lib`, and that may be why it's not finding the dependency for python3

**Comment by KrunchMuffin** [comment]
Same issue after running that.

> pi@raspberrypi:~ $ sudo pip3 install --user soupsieve
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: soupsieve in /usr/lib/python3/dist-packages (1.8)
pi@raspberrypi:~ $ mmpm -l
/home/pi/.local/lib/python2.7/site-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'

**Comment by KrunchMuffin** [comment]
crap, I think I may have installed some things w/o `sudo` that may explain why 2.7 is in `/home/pi/`
