### ISSUE TITLE
MMPM

### ISSUE THREAD

**Issue by firefighter4892** [Bee-Mar/mmpm#80]
I cannot get my 'active modules' to connect/load in the MMPM GUI.  I am a beginner and don't know what other files to change to get this to work.  Thanks in advanced.

**Comment by Bee-Mar** [comment]
This should be resolved with the release I just published. Try upgrading mmpm to version 2.12

`pip install --upgrade mmpm; mmpm install --gui`

**Comment by Bee-Mar** [comment]
@firefighter4892 have you had a chance to try this?

**Comment by Bee-Mar** [comment]
I'm closing this issue because other users have been able to get the "active modules" feature working with the new update.

**Comment by firefighter4892** [comment]
Sorry for not replying earlier, holidays have been busy. I still could not
get it to work.  About half of the modules I have tried I have not been
able to get to work.  All that happens is the screen goes black.  When I
delete the code, it goes back to working as normal.  I don't know what else
to try, but thanks for reaching out.  Hope your holidays are going well,
-Ryan
