### ISSUE TITLE
BUG: unable to retrieve active modules

### ISSUE THREAD

**Issue by je4928** [Bee-Mar/mmpm#83]
After re-install of mmpm module activre modules no longer appear.  It appears that the latest version of mmpm is no longer on githuib.  Version on github is 2.12 and this issue was supposed to be fixed in version 2.15.

**Comment by Bee-Mar** [comment]
Following the reinstall of MMPM, you'll also need to run:

mmpm install --as-module

**Comment by je4928** [comment]
Thank you. That resolved my issue,
