### ISSUE TITLE
Bash: MMPM: Command not found

### ISSUE THREAD

**Issue by Adiventure** [Bee-Mar/mmpm#86]
`  WARNING: The script chardetect is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wsdump is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flask is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wssh is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script gunicorn is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mmpm is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Flask-Cors-3.0.10 argcomplete-2.0.0 argparse-1.4.0 bcrypt-3.2.0 bidict-0.21.4 bs4-0.0.1 cffi-1.15.0 chardet-3.0.4 dnspython-1.16.0 eventlet-0.30.1 flask-1.1.1 flask-socketio-5.1.1 greenlet-1.1.2 gunicorn-20.1.0 mmpm-2.12 paramiko-2.9.2 pycparser-2.21 pynacl-1.5.0 python-engineio-4.3.1 python-socketio-5.5.1 requests-2.23.0 tornado-6.1 urllib3-1.25.11 websocket-client-1.2.3 webssh-1.5.3
pi@Pi-Mirror:~ $ mmpm --guided-setup
bash: mmpm: command not found
`

Followed install instructions however was stopped at the MMPM setup stage. I'm assuming this is related to the prior warnings, however I'm too ignorant to resolve on my own.

Running on the latest stable Magic MIrror, and fresh install on a Pi 3b.

**Comment by Bee-Mar** [comment]
The first line of that message indicates the issue. You don't have "~/.local/bin" as part of your PATH environment variable.

You can solve this easily with the command below:

echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc

**Comment by Adiventure** [comment]
You're a gentleman and a scholar.

Curious how that comes to be.

I did that command, and repeated the prior command, however I am still getting the command not found result.
`pi@Pi-Mirror:~ $ echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
pi@Pi-Mirror:~ $ mmpm --guided-setup
bash: mmpm: command not found
pi@Pi-Mirror:~ $ python3 -m pip install --upgrade --no-cache-dir mmpm
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: mmpm in ./.local/lib/python3.9/site-packages (2.12)
Collecting mmpm
  Downloading mmpm-2.12-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 5.5 MB/s 
  Downloading https://www.piwheels.org/simple/mmpm/mmpm-2.11-py3-none-any.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 406 kB/s 
Requirement already satisfied: gunicorn>=20.1.0 in ./.local/lib/python3.9/site-packages (from mmpm) (20.1.0)
Requirement already satisfied: flask==1.1.1 in ./.local/lib/python3.9/site-packages (from mmpm) (1.1.1)
Requirement already satisfied: bs4>=0.0.1 in ./.local/lib/python3.9/site-packages (from mmpm) (0.0.1)
Requirement already satisfied: Flask-Cors>=3.0.8 in ./.local/lib/python3.9/site-packages (from mmpm) (3.0.10)
Requirement already satisfied: webssh>=1.5.1 in ./.local/lib/python3.9/site-packages (from mmpm) (1.5.3)
Requirement already satisfied: pygments>=2.3.1 in /usr/lib/python3/dist-packages (from mmpm) (2.7.1)
Collecting argparse>=1.1
  Downloading https://www.piwheels.org/simple/argparse/argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: flask-socketio>=5.0.1 in ./.local/lib/python3.9/site-packages (from mmpm) (5.1.1)
Requirement already satisfied: argcomplete>=1.11.1 in ./.local/lib/python3.9/site-packages (from mmpm) (2.0.0)
Requirement already satisfied: eventlet==0.30.1 in ./.local/lib/python3.9/site-packages (from mmpm) (0.30.1)
Requirement already satisfied: python-socketio[client]>=5.0.4 in ./.local/lib/python3.9/site-packages (from mmpm) (5.5.1)
Requirement already satisfied: requests==2.23.0 in ./.local/lib/python3.9/site-packages (from mmpm) (2.23.0)
Requirement already satisfied: colorama>=0.4.3 in /usr/lib/python3/dist-packages (from mmpm) (0.4.4)
Requirement already satisfied: greenlet>=0.3 in ./.local/lib/python3.9/site-packages (from eventlet==0.30.1->mmpm) (1.1.2)
Requirement already satisfied: dnspython<2.0.0,>=1.15.0 in ./.local/lib/python3.9/site-packages (from eventlet==0.30.1->mmpm) (1.16.0)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from eventlet==0.30.1->mmpm) (1.16.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (2.11.3)
Requirement already satisfied: click>=5.1 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (7.1.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/lib/python3/dist-packages (from flask==1.1.1->mmpm) (1.1.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.local/lib/python3.9/site-packages (from requests==2.23.0->mmpm) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.23.0->mmpm) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.local/lib/python3.9/site-packages (from requests==2.23.0->mmpm) (3.0.4)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4>=0.0.1->mmpm) (4.9.3)
Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn>=20.1.0->mmpm) (52.0.0)
Requirement already satisfied: bidict>=0.21.0 in ./.local/lib/python3.9/site-packages (from python-socketio[client]>=5.0.4->mmpm) (0.21.4)
Requirement already satisfied: python-engineio>=4.3.0 in ./.local/lib/python3.9/site-packages (from python-socketio[client]>=5.0.4->mmpm) (4.3.1)
Requirement already satisfied: websocket-client>=0.54.0 in ./.local/lib/python3.9/site-packages (from python-socketio[client]>=5.0.4->mmpm) (1.2.3)
Requirement already satisfied: tornado>=4.5.0 in ./.local/lib/python3.9/site-packages (from webssh>=1.5.1->mmpm) (6.1)
Requirement already satisfied: paramiko>=2.3.1 in ./.local/lib/python3.9/site-packages (from webssh>=1.5.1->mmpm) (2.9.2)
Requirement already satisfied: pynacl>=1.0.1 in ./.local/lib/python3.9/site-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (1.5.0)
Requirement already satisfied: bcrypt>=3.1.3 in ./.local/lib/python3.9/site-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (3.2.0)
Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko>=2.3.1->webssh>=1.5.1->mmpm) (3.3.2)
Requirement already satisfied: cffi>=1.1 in ./.local/lib/python3.9/site-packages (from bcrypt>=3.1.3->paramiko>=2.3.1->webssh>=1.5.1->mmpm) (1.15.0)
Requirement already satisfied: pycparser in ./.local/lib/python3.9/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.3.1->webssh>=1.5.1->mmpm) (2.21)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->bs4>=0.0.1->mmpm) (2.2.1)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
pi@Pi-Mirror:~ $ mmpm --guided-setup
bash: mmpm: command not found
`

**Comment by Bee-Mar** [comment]
You may need to source your bashrc to make the changes effective. You do that by opening a new terminal window or running:
 "source ~/.bashrc" in your current window

**Comment by Adiventure** [comment]
Thank you. How is it that these get messed up in the first place?

**Comment by Bee-Mar** [comment]
@Adiventure On a fresh installation of pretty much all versions of Linux I'm aware of, `~/.local/bin` isn't part of the `PATH`. A lot of users get tripped up on that when things like Python, NPM, Ruby packages and other executables get stored in `~/.local/bin`

**Comment by Adiventure** [comment]
Great, thank you.
