### ISSUE TITLE
Can't rotate Screen

### ISSUE THREAD

**Issue by OneGaming36** [Bee-Mar/mmpm#87]
When trying to rotate the screen of my MagicMirror through MMPM I get the following error message from MMPM:
"Unable to determine the current rotation setting. An initial value must exist in your /boot/config.txt for MMPM to modify."

Since I had no idea what to do, I searched for a solution through Google.
Someone has been talking about adding "display_rotate=1" to /boot/config.txt.
After doing so, there is no error message when trying to rotate the screen anymore. Just MMPM telling me to reboot the raspi for the changes to take effect.

Yet the screen still doesn't rotate. What should I do to get this working?

**Comment by Bee-Mar** [comment]
@OneGaming36 this is odd. I'll look into this over the weekend

**Comment by khassel** [comment]
@OneGaming36 which OS-Version are u running? 32bit or 64 bit? bullseye or buster?

**Comment by OneGaming36** [comment]
Buster 32bit.

**Comment by Bee-Mar** [comment]
@OneGaming36 version 4.0.0 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
