### ISSUE TITLE
ERROR: The directory '/home/$user/MagicMirror/modules' does not exist. Have you installed MagicMirror properly?

### ISSUE THREAD

**Issue by accountnumber3** [Bee-Mar/mmpm#9]
modules directory is hard-coded, I don't keep my modules there. Can I get a `--module-dir` option?

**Comment by Bee-Mar** [comment]
Fair enough. I may add in a settings file that store that sort of information.

**Comment by Bee-Mar** [comment]
@accountnumber3 on the develop branch, there's support for a different installation location. If you set an environment variable named `MMPM_MAGICMIRROR_ROOT` to the absolute path of your MagicMirror installation, the cli will pick that up and use it as the location for installation and removal. Keep in mind this is on the develop branch, so you may encounter some bugs.

**Comment by vKnmnn** [comment]
Hi, I installed  MagicMirror via docker, using a specific path as a bind mount to be able to install modules. this new feature comes in very handy.

i set MMPM_MAGIGMIRROR_ROOT to "/docker/magicmirror"

```
/docker/magicmirror
├── config
└── modules
    └── default

```

Nonetheless, mmpm reports 
```
mmpm -i MMM-NowPlayingOnSpotify
ERROR: The MMM-NowPlayingOnSpotify module already exists. To remove the module, run 'mmpm -r MMM-NowPlayingOnSpotify'
```
```
mmpm -r MMM-NowPlayingOnSpotify
ERROR: No modules are currently installed.
```

this is after a brand new install of mmpm

**Comment by Bee-Mar** [comment]
Does that directory exist anywhere in your modules directory?

**Comment by vKnmnn** [comment]
no, the modules directory was empty apart from the "default" directory and the README

**Comment by Bee-Mar** [comment]
hmm, I haven't had time to look into this until this morning, but will spend more time today. This is very odd.

**Comment by Bee-Mar** [comment]
@vKnmnn If you have a chance, see if the latest update may resolve any of these issues. If not, i'll have to do some more digging

**Comment by vKnmnn** [comment]
yes, i am gonna try right away. you have been busy, i see.

**Comment by Bee-Mar** [comment]
@vKnmnn what sort of errors?

**Comment by vKnmnn** [comment]
well i'm on arch linux, so it's some errors about apt not being available :)
never mind, i hat pip3 already installed so i just out-commented it. that's an issue to tackle when you're packaging this for distros.

I installed the new version and i was able to install packages into an empty directory. so it seems this issue has been fixed.
Thank you.

**Comment by Bee-Mar** [comment]
@vKnmnn that's something I'm planning on doing soon, but thanks for the heads up about some users running MagicMirror on arch! Feel free to give feedback on the new interface as well. Since everything appears to be working now, i'll go ahead and close this.
