### ISSUE TITLE
Fresh install, can't connect to active modeuls 

### ISSUE THREAD

**Issue by dannydp79** [Bee-Mar/mmpm#90]
Ok so I’ve got a new install, clean fresh on LTS Ubuntu

I’m getting the Unable to retrieve active modules error message. I have checked my config and the whitelist is just open [] so should (and does) let anyone in. I’ve verified I can get to the URL from both the server and local workstations on the same network.

I can’t see anything in my config that’s messing it up, so hoping a guru will know.

[mmpm-logs-2022-1-2 (1).zip](https://github.com/Bee-Mar/mmpm/files/8080850/mmpm-logs-2022-1-2.1.zip)
![mmpm](https://user-images.githubusercontent.com/87725801/154291748-dbe004cb-c451-4b4f-9c8f-0414d924affa.PNG)

**Comment by Bee-Mar** [comment]
@dannydp79 have you had a chance to look through those instructions?

**Comment by Bee-Mar** [comment]
@dannydp79 have you have any more time to try that out?

**Comment by Bee-Mar** [comment]
@dannydp79 I'm going to close this issue due to inactivity. Re-open if you still have issues
